### ISSUE TITLE
Documentations revision: 

### ISSUE THREAD

**Issue by pbuttigieg** [GenomicsStandardsConsortium/mixs#10]
Over at [MIxS-syntax-data-types](https://github.com/GenomicsStandardsConsortium/mixs/wiki/7.-MIxS-syntax-data-types), I suggest we update:

>{term}: ontology term, consists of alphabetic characters

to  

**{term}**: An ontology term (i.e. a class), identified by the class label and its unique ID in CURIE format (i.e. "[namespace:[numericCode]]". For example:
 `soil biocrust [ENVO:01000910]`
Multiple terms should be pipe separated:
`anoxic water [ENVO:01000173]|eutrophic water [ENVO:00002224]`

**Comment by pyilmaz** [comment]
Thanks for the suggestion, I will update those. The document was written before we agreed to change the EnvO descriptors. For consistency, I will change all {term} types to the new syntax.

**Comment by pyilmaz** [comment]
Updated here: https://genomicsstandardsconsortium.github.io/mixs/mixs-data-type/
We'll move all content from wiki to the github.io pages and close the wiki
