### ISSUE TITLE
update binning software definition and expected values

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#107]
**Current term details**
```
Term name - binning software
Term ID - MIXS:0000078
Structured comment name - bin_software
Definition - Tool(s) used for the extraction of genomes from metagenomic datasets
Expected value - enumeration
Value syntax - [metabat\|maxbin\|concoct\|groupm\|esom\|metawatt\|combination\|other]
Example - concoct and maxbin
Preferred unit - 
Package(s) - MIMAGS, MIUVIG
```
**Suggested update(s)**
```
Term name - binning software
Term ID - MIXS:0000078
Structured comment name - bin_software
Definition - Tool(s) used for the extraction of genomes from metagenomic datasets, where possible include a PID of the tool(s) used.
Expected value - names and versions of software(s) used 
Value syntax - {software};{version}{PID}
Example - MetaCluster-TA (RRID:SCR_004599), MaxBin (biotools:maxbin)
Preferred unit - 
Package(s) - MIMAGS, MIUVIG
```

**Additional context**
All software-related terms should have a more uniform value syntax where we require the name and version, and I think where possible a PID for the software should be included, I have suggested RRIDs as thats the one I'm familiar with, but there are other options including the [bio.tools](https://bio.tools/) project by Elixir.

**Comment by 79-6d** [comment]
Referring to related thread in TDWG: https://github.com/tdwg/attribution/issues/38

Some points from the thread that I find interesting to mention:

>  For software as agent I think what you want to identify is the instance of the software, not (only) the software project and version. The instance is very comparable to a human, there is only one and it may have a unique configuration/set of settings ...

I find this comment very true ...

> [Persistent identifiers for software](https://docs.softwareheritage.org/devel/swh-model/persistent-identifiers.html) have been designed. Not sure how frequently these are used ...

I am keen towards having certain form of persistent identifier for this field, but I wonder if this is often available?

**Comment by only1chunts** [comment]
Great to link up with similar work in TDWG, thanks.
Personally, I think going as far as the individual machine (or indeed laboratory staff member) doing the experiment is a step too far as many software tools will be run on VMs or on cloud instances that are not persistent in any way. The best we can hope for is a software name and version.
Giving the option to include a PID of the software will allow for its inclusion and possibly encourage uptake of the use of PIDs for tools.

**Comment by 79-6d** [comment]
I see! You have a point! Thanks for mentioning that!

If tools running on VMs/cloud instances are not persistent then I agree that we should go for the simpler solution. In that case, I agree with everything you said, so software name, version and PID (do you mean PID = Persistent Identifier?) and I don't have anything else to add. 

Thank you so much!

**Comment by lschriml** [comment]
Make the change in the spreadsheet. 
Term name - binning software
Term ID - MIXS:0000078
Structured comment name - bin_software
Definition - Tool(s) used for the extraction of genomes from metagenomic datasets, where possible include a PID of the tool(s) used.
Expected value - names and versions of software(s) used 
Value syntax - {software};{version}{PID}
Example - MetaCluster-TA (RRID:SCR_004599), MaxBin (biotools:maxbin)
Preferred unit - 
Package(s) - MIMAGS, MIUVIG

**Comment by lschriml** [comment]
Updated in MIxS 6 core, MIMAGS, MIUVIG
