### ISSUE TITLE
host common name - update to definition?

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#108]
**Current term details**
Please supply the current details of the term that you would like to update:
```
Term name - host common name 
Term ID - MIXS:0000248
Structured comment name - host_common_name
Definition - Common name of the host, e.g. Human
Expected value - common name
Value syntax -{tex}
Example -mussel
Preferred unit - 
Package(s) - multiple
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):
```
Term name - host common name 
Term ID - MIXS:0000248
Structured comment name - host_common_name
**Definition - common name of the symbiotic host organism under study, e.g. Gordian worm**
Expected value - common name
Value syntax -{tex}
Example -mussel
Preferred unit - 
Package(s) - multiple including new Symbiont associated package
```

**Additional context**
The new symbiont associated package suggested this new definition.

**Comment by lschriml** [comment]
Note: host common name is in both the 'plant-associated' and 'host-associated' packages:

**Comment by 79-6d** [comment]
Is there a reason that common name is used instead of scientific name? 
Personally I would prefer scientific name because it gives more information and it can also be used to look for more taxa information with taxonomic backbones (e.g. Catalogue of Life, World Register of Marine Species)

**Comment by lschriml** [comment]
@79-6d 
--> Let's discuss the addition of a 'host taxonomic name' in the next CIG

Currently, MIxS includes the field, host_taxid

Cheers,
Lynn

**Comment by lschriml** [comment]
I think it would be of more general use to keep the definition, unchanged.

**Comment by only1chunts** [comment]
agreed no need for change.
