### ISSUE TITLE
host status of association with symbiont in Host-associated package

### ISSUE THREAD

**Issue by ndheilly** [GenomicsStandardsConsortium/mixs#110]
as described in Symbiont-associate MIxS package manuscript going to be submitted soon: "The new term added to the host-associated package “host status of association with symbiont” provides a more comprehensive item to refer to associations with symbionts." It is therefore complementary to the existing term "host disease status"

For us to assess a new term request we require the following details:
```
Term name - host status of association with symbiont
Structured comment name - host_symbiont_stat
Definition - whether the host is associated or not with symbionts (e.g. parasites) screened as part of the study (taxid, common name or species name); indicate the association status; Can include multiple symbiotic organisms
Expected value - name
Value syntax - {text};[not associated|associated]
Example - [provide and example value]
Preferred unit - NA
Package(s) - Host-associated; Human-associated; plant-associated; human-vaginal; human-skin; human-oral; human-gut
```

**Additional context**
Add any other context about the new term here.

**Comment by lschriml** [comment]
[MIxS-SA google doc](https://docs.google.com/spreadsheets/d/1k_3lZ5zEF4SQBFe0eem_vpjt26mIdcKh2La2xCx3BJE/edit#gid=185552950)

Discussed this new term for addition to the host-associated package, during this month's CIG call. 
@ndheilly - follow up questions: 
                 - please clarify, it this term intended to: capture symbionts found via sequencing or screening? 

                 - Regarding 'host infection status': 
                              - to capture the information about the symbiont infecting the host, 
                              what about a term called: "host symbiotic organism"
                          - Not sure you would need to then have a field that is specifying if the host is infected or not.

                           - what about 'host infection organism' being: 
                                      Host infection status, specifying the infecting organism (e.g.taxonomic name).  
                           - this term could then be used to specify any infecting organism, where the sample is from a 'host'

            
               **CIG Review notes:** 
               - Agree it should go in host package if softened a bit. 
                         - If they require screens, then it should go in the symbiont package.
           
               - Is it only filled in if there is a screening? 
               - Do you want to include known infections that aren't necessarily screened for? 
               - Might be found after the sample collection (e.g., via sequencing).

Cheers,
Lynn

**Comment by ndheilly** [comment]
The PMP found the term 'host disease status" in the host-associated package problematic because it is limited to disease-causing organisms, and to symptomatic cases. It is defined as follow: " list of diseases with which the host has been diagnosed; can include multiple diagnoses. the value of the field depends on host; for humans the terms should be chosen from DO (Disease Ontology) at http://www.disease-ontology.org, other hosts are free text "

Our objective, with adding the term "host status of association with symbiont" or "host-symbiont_stat" is to provide a term openly complementary that can be used when the host is screened for non-disease causing organisms, or is found asymptomatic. 
Can be changed to host_infection_status" if the CIG prefer this term, as long as the definition is clearly open to all symbionts and is not limited to disease-causing species  (i.e. pathogens).

I agree that these may be discovered serendipitously without running a specific screening. Would you like to add this to the definition?

The term needs to be added to the host-associated package because it can be useful even when the authors do not sequence the symbiont itself. The symbiont-associated packages focuses on microbes associated with symbionts. I do not understand how this term should go into the symbiont package ?!?

**Comment by lschriml** [comment]
@ndheilly 

I propose: 

host_symbiont: The taxonomic name of the organism(s) living in mutualistic, commensalistic, or parasitic symbiosis with the host. 
 
Cheers,
Lynn

**Comment by only1chunts** [comment]
@lschriml , I like your proposal, it seems to cover the requirements and is clear enough for anyone to use. 
I think making it more specific to the actual host organism may be prudent otherwise it may be used to hold general knowledge about organisms that are known to be symbiotic with the host species.

```
Term name - observed host symbionts
Structured comment name - host_symbiont
Definition - The taxonomic name of the organism(s) found living in mutualistic, commensalistic, or parasitic symbiosis with the specific host.
Expected value - {species name} or {common name}
Value syntax - {text}
Example - flukeworms
Package(s) - Host-associated; Human-associated; plant-associated; human-vaginal; human-skin; human-oral; human-gut
```

**Comment by ndheilly** [comment]
OK.
We will update the MIxS symbiont-associated manuscript accordingly. Thanks

**Comment by lschriml** [comment]
@only1chunts - agreed, I've added this new term to packages: 
           Host-associated; Human-associated; plant-associated; human-vaginal; human-skin; human-oral; human-gut

Cheers,
Lynn
