### ISSUE TITLE
Field to express (re)use restrictions are/were in effect

### ISSUE THREAD

**Issue by pbuttigieg** [GenomicsStandardsConsortium/mixs#111]
**New term details**

The intention of these terms is to note if 1) the associated sequence record is or has been under any form of embargo and 2) when such embargoes are expected to expire. This will allow users to flag or exclude data that may lead to complications 

The description of this field should indicate that it is non-binding, and that the hosting systems policies and management routines are authoritative (e.g. in case the submitter updates the embargo period). 

```
Term name - usage restrictions
Structured comment name - use_restrictions
Definition - This field specifies if any usage restrictions on the associated sequence records exist. This field is non-binding, and users should refer to their repository's policies as authoritative. However, the field does allow an indication of whether extra care is needed with reuse, regardless of repository.
Expected value - [TRUE,FALSE]
Value syntax - {Boolean}
Example - TRUE
Package(s) - core
```

```
Term name - expected end of usage restrictions
Structured comment name - use_restrictions_end
Definition - This field specifies the date/time on which any and all usage restrictions on the data are expected to expire. If the data is released without restrictions, leave this field blank and enter "FALSE" in the use_restrictions field. This field is non-binding, and only serves as an indicator that any reuse should proceed with care.
Expected value - ISO 8601 date/time
Value syntax - {date}
Example - 2022-02-22T00:00:01+00:00
Package(s) - core
```

**Additional context**

As far as I understand the situation: 

Recent coordination breakdowns between JGI and the INSDC ([1](https://retractionwatch.com/2021/02/17/no-malicious-intent-authors-retract-week-old-paper-based-on-embargoed-data/), [2](https://twitter.com/merenbey/status/1360065794579836929)) have led to researchers inadvertently using sequence data that was embargoed under JGI, but not so under INSDC resources. 

With 1) data systems becoming more complex without interoperation 2) researchers integrated ever more records into synthetic analyses, making manual checks and detective work on every record prohibitive, 3) editorial teams - apparently unable to understand where the issue is - associating ethical breaches with authors that acted in good faith [3](https://advances.sciencemag.org/content/7/8/eabh0587) and 4) no guarantee that the hosting systems are respecting their own users' embargo requests (where those are valid), there is a clear need to link metadata about embargos directly to the data itself. 

The GSC, as a neutral and system-independent entity, can take a step to improve transparency by adding a mandatory field as described above.

**Comment by lschriml** [comment]
The GSC board discussed this issue this week, decided not to add a new term on use/reuse restrictions at this time.
Lynn

**Comment by only1chunts** [comment]
i'm closing this issue now as we dont need to carry out any action for v6 release. if we need to revisit in the future we can either re-open or start a fresh issue.

**Comment by pbuttigieg** [comment]
Note that DwC re-uses the Dublin Core [`license`](http://purl.org/dc/terms/license) field, with a useful link to [`license document`](http://purl.org/dc/terms/LicenseDocument). 

MIxS should likely do the same in place of or in addition to the terms requested above.

**Comment by pbuttigieg** [comment]
>The GSC board discussed this issue this week, decided not to add a new term on use/reuse restrictions at this time.


@lschriml Let's be clear - the board conflated this issue with 

@only1chunts
> i'm closing this issue now as we dont need to carry out any action for v6 release. if we need to revisit in the future we can either re-open or start a fresh issue.

This is an odd way to handle issues, and an easy way to obscure them - I would use a label to indicate this is not for the v6 release, but not close it.
