### ISSUE TITLE
Update term request: MIxS core depth

### ISSUE THREAD

**Issue by raissameyer** [GenomicsStandardsConsortium/mixs#112]
**Current term details**
```
Term name - geographic location (depth)
Term ID - MIXS:0000018
Structured comment name - depth
Definition - Please refer to the definitions of depth in the environmental packages
Expected value - -
Value syntax - -
Example -
Preferred unit - 
Package(s) - MIxS core
```

**Suggested update(s)**
based on the definition and additional information given for `depth` in the environmental packages
```
Definition - Depth is defined as the vertical distance below local surface, e.g. For sediment or soil samples depth is measured from sediment or soil surface, respectively. Depth can be reported as an interval for subsurface samples
Expected value - measurement value
Value syntax - {float} {unit}
Example - 10 meter
Preferred unit - meter
```

**Additional context**

The present definition is semantic nonsense, and as all definitions of depth in the environmental packages are currently identical I don’t see any reason not to add this information to MIxS core depth as well (as you have done for e.g. altitude and elevation). This is especially important as the current definition impedes an appropriate mapping between DwC and MIxS (see [here](https://github.com/tdwg/gbwg/issues/13#issuecomment-777237294)). 

I acknowledge that you’ve already mentioned the need to update this in the [editors version of V6](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=567040283&range=F8), but for completeness I’m adding it to the tracker as well. 

Thank you!

**Comment by only1chunts** [comment]
thanks @raissameyer it is in fact already in the issue tracker under #63 
The plan is that Depth will be a core term instead of listed in each individual package.
