### ISSUE TITLE
[MIXS:0000094] alt: Typo in definition?

### ISSUE THREAD

**Issue by 79-6d** [GenomicsStandardsConsortium/mixs#114]
**Current term details**
Please supply the current details of the term that you would like to update:
```
Term name - alt
Term ID - MIXS:0000094
Structured comment name - altitude
Definition - Altitude is a term used to identify heights of objects such as airplanes, space shuttles, rockets, atmospheric balloons and heights of places such as atmospheric layers and clouds. It is used to measure the height of an object which is above the earth‚Äôs surface. In this context, the altitude measurement is the vertical distance between the earth's surface above sea level and the sampled position in the air
Expected value - measurement value
Value syntax - {float} {unit}
Example - 100 meter
Preferred unit - meter
Package(s) - air
```

**Suggested update(s)**

I am not sure what `Äôs` means, perhaps `sea`?

**Comment by only1chunts** [comment]
looks like a formatting issue, I think it's meant to be an apostrophe e.g. "earth's" surface. I'm no expert on English so I don't even know if that's meant to have an apostrophe there or not?! but the strange encoding is something to do with cutting and pasting between mac and microsoft, so yes we should correct that.

**Comment by lschriml** [comment]
It should be earth's. 
fixed
