### ISSUE TITLE
Recommend wikidata instead of GAZ in MIxS6

### ISSUE THREAD

**Issue by cmungall** [GenomicsStandardsConsortium/mixs#116]
GAZ is no longer supported. New entries can be added to Wikidata by anyone.

See
https://github.com/EnvironmentOntology/gaz/issues/35

I think that starting mixs6 we should recommend wikidata

Note that I started on the task of mapping GAZ to Wikidata with a view to merging in info from GAZ, but have no resources to complete:

https://github.com/cmungall/environments2wikidata

however, I don't think GSX should wait on this

**Comment by lschriml** [comment]
We have included the INDSC country list. 
I am in the process of creating a country only gaz.
Keeping the gas in MIxS 6.
