### ISSUE TITLE
Expand the range of env_medium

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#117]
The current definition of `env_medium` specifies the range to be a term from EnvO's `environmental hierarchy`:
```
In this field, report which environmental material or materials (pipe separated) immediately surrounded your sample or specimen prior to sampling, using one or more subclasses of ENVO’s environmental material class: http://purl.obolibrary.org/obo/ENVO_00010483. Format (one term): termLabel [termID]; Format (multiple terms): termLabel [termID]|termLabel [termID]|termLabel [termID]. Example: Annotating a fish swimming in the upper 100 m of the Atlantic Ocean, consider: ocean water [ENVO:00002151]. Example: Annotating a duck on a pond consider: pond water [ENVO:00002228]|air ENVO_00002005. If needed, request new terms on the ENVO tracker, identified here: http://www.obofoundry.org/ontology/envo.html
```
However, GOLD needs a number of terms that are not in the hierarchy. See this ticket:

https://github.com/EnvironmentOntology/envo/issues/1067

We could import the terms into EnvO, but this bloats the ontology and is counter to the philosophy of the OBO Foundry. I suggest we modify the definition of `env_medium` to allow for other ontology terms (e.g., from another OBO `material entity` hierarchy).

I realize that the `Expected value` field (for `env_medium`) is less restrictive:
```
Add terms that identify the material displaced by the entity at time of sampling. Recommend subclasses of environmental material [ENVO:00010483]. Multiple terms can be separated by pipes e.g.: estuarine water [ENVO:01000301]|estuarine mud [ENVO:00002160]
```
But this creates confusion as to what the proper range is.

**Comment by only1chunts** [comment]
**Current term details**
```
Term name - environmental medium
Term ID - MIXS:0000014
Structured comment name - env_medium 
Definition - In this field, report which environmental material or materials (pipe separated) immediately surrounded your sample or specimen prior to sampling, using one or more subclasses of ENVO’s environmental material class: http://purl.obolibrary.org/obo/ENVO_00010483. Format (one term): termLabel [termID]; Format (multiple terms): termLabel [termID]\|termLabel [termID]\|termLabel [termID]. Example: Annotating a fish swimming in the upper 100 m of the Atlantic Ocean, consider: ocean water [ENVO:00002151]. Example: Annotating a duck on a pond consider: pond water [ENVO:00002228]\|air ENVO_00002005. If needed, request new terms on the ENVO tracker, identified here: http://www.obofoundry.org/ontology/envo.html 
Expected value - Add terms that identify the material displaced by the entity at time of sampling. Recommend subclasses of environmental material [ENVO:00010483]. Multiple terms can be separated by pipes e.g.: estuarine water [ENVO:01000301]\|estuarine mud [ENVO:00002160] 
Value syntax - {termLabel} {[termID]}
Example - soil [ENVO:00001998] 
Package(s) - CORE
```

**Suggested update(s)**
```
Definition - Add terms that identify the material displaced by the entity at time of sampling. Recommend subclasses of environmental material [ENVO:00010483], or . Multiple terms can be separated by pipes e.g.: estuarine water [ENVO:01000301]|estuarine mud [ENVO:00002160]. Note this term was previously named "material".
Expected value - One or more ontology terms describing the material displaced by sample. 
Value syntax - {termLabel} {[termID]}
Example - estuarine water [ENVO:01000301]|estuarine mud [ENVO:00002160]
Package(s) - CORE
```

**Additional context**
This new definition takes into account Bills concerns above AND the requirement added by @lschriml to MIxS v6 to edit spreadsheet of "add synonym to end of definition".

**Comment by pbuttigieg** [comment]
@only1chunts @wdduncan 

This can be expanded, but the suggestions in the ENVO tracker are not all valid, as they include things that are not materials or media.

Further, a sentence in the update is not complete and giving CURIE IDs isn't helpful - the user needs to get to the hierarhies and most won't know how. 

>Add terms that identify the material displaced by the entity at time of sampling. Recommend subclasses of environmental material [ENVO:00010483], or . Multiple terms can be separated by pipes e.g.: estuarine water [ENVO:01000301]|estuarine mud [ENVO:00002160]. Note this term was previously named "material".

If you want to keep the text, it should read:

```
Add ontology terms that identify the material displaced by the entity at time of sampling. We recommend subclasses of environmental material (http://purl.obolibrary.org/obo/ENVO_00010483), but terms from other OBO ontologies are permissible as long as they reference mass/volume nouns (e.g. air, water, blood) and not discrete, countable entities (e.g. a tree, a leaf, a table top). Multiple terms can be separated by pipes e.g.: estuarine water [ENVO:01000301]|estuarine mud [ENVO:00002160]. Note this term was previously named "material".
```

It would be best to link to this page instead: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS

We're working on getting an IRI for that page, so that it's more stable, but this should be around until MIxS v7.

**Comment by lschriml** [comment]
Updated to include the above discussion. 

definition for environmental medium: 
Report the environmental material(s) immediately surrounding the sample or specimen at the time of sampling. We recommend using subclasses of 'environmental material' (http://purl.obolibrary.org/obo/ENVO_00010483). EnvO documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS . Terms from other OBO ontologies are permissible as long as they reference mass/volume nouns (e.g. air, water, blood) and not discrete, countable entities (e.g. a tree, a leaf, a table top).
