### ISSUE TITLE
update term name for MIXS:0000029 to host scientific name

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#131]
**Current term details**
```
Term name - specific host
Term ID - MIXS:0000029
Structured comment name - specific_host
Definition - If there is a host involved, please provide its taxid (or environmental if not actually isolated from the dead or alive host - i.e. a pathogen could be isolated from a swipe of a bench etc) and report whether it is a laboratory or natural host) | host taxid, unknown, environmental
Expected value - 
Value syntax - {NCBI taxid}\|{text}
Example - Homo sapiens or 9606
```

**Suggested update(s)**
```
* Term name - host scientific name
Term ID - MIXS:0000029
* Structured comment name - specific_host
Definition - If there is a host involved, please provide its taxid (or environmental if not actually isolated from the dead or alive host - i.e. a pathogen could be isolated from a swipe of a bench etc) and report whether it is a laboratory or natural host) | host taxid, unknown, environmental
Expected value - 
Value syntax - {NCBI taxid}\|{text}
Example - Homo sapiens or 9606
```

**Additional context**
The SARS COV2 package being used at EBI renamed this, it seems to be more easily understood and therefore easier to get people to use it so we should update the MIXS:0000029 name

Q - Do we update the structured comment name as well as the  Term name?

**Comment by lschriml** [comment]
Revised the definition. 

* Term name - host scientific name
Term ID - MIXS:0000029
* Structured comment name - specific_host
Definition - Report the host's taxonomic name and/or NCBI taxonomy ID.
Expected value - host scientific name, taxonomy ID
Value syntax -{text}|{NCBI taxid}
Example - Homo sapiens and/or 9606

**Comment by only1chunts** [comment]
agreed, moved to InProgress

**Comment by lschriml** [comment]
Looking at MIXS 6 core (to edit) - this has already been updated 

checked Checklists (MIMAG, MISAG, MIUVIG)
new package: MIxS-Food
MIxS 6 packages - to edit

In progress checklist: 
    MIxS - SARS-CoV-2 - OK
    
In progress packages: 
   MIxS-SA  (Symbiont)
   MIxS-Ag     - OK
   MIxS - Positive and Negative Controls

This ticket is complete.
