### ISSUE TITLE
Identifiers.org Resolution Service

### ISSUE THREAD

**Issue by jjkoehorst** [GenomicsStandardsConsortium/mixs#138]
To discuss if we want to register the MIxS url space with identifiers.org. This is mostly used when identifiers are used in multiple resources with different uri's as a resolution service.

**Comment by wdduncan** [comment]
Is this related to https://github.com/GenomicsStandardsConsortium/mixs-rdf/issues/2?

cc @ramonawalls

**Comment by ramonawalls** [comment]
@wdduncan You will see several issues that look familiar, since I transferred them here form MIxS as RDF.

**Comment by turbomam** [comment]
MIxS terms are resolvable via w3id.org now in this style: http://w3id.org/mixs/0000002
