### ISSUE TITLE
Remove implicit taxonomic scope from votu_class_appr, votu_seq_comp_appr, votu_db

### ISSUE THREAD

**Issue by thomasstjerne** [GenomicsStandardsConsortium/mixs#140]
**Current term details**
Please supply the current details of the term that you would like to update:
```
Term name - vOTU database
Term ID - MIXS:0000087
Structured comment name - votu_db
Definition - Reference database (i.e. sequences not generated as part of the current study) used to cluster new genomes in "species-level" vOTUs, if any
Expected value - database and version
Value syntax - {database};{version}
Example - NCBI Viral RefSeq;83
Preferred unit - 
Package(s) - 
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):
```
Term name - OTU database
Term ID - MIXS:0000087
Structured comment name - otu_db
Definition - Reference database (i.e. sequences not generated as part of the current study) used to cluster new genomes in "species-level" OTUs, if any
Expected value - database and version
Value syntax - {database};{version}
Example - NCBI Viral RefSeq;83, UNITE;8.3
Preferred unit - 
Package(s) -  
```

**Additional context**
We have been working with different communities to draft a guide on [how to publish DNA-derived data](https://doi.org/10.35035/doc-vf1a-nr22) to ALA, GBIF, OBIS and similar systems. During this work it was pointed out that the terms UViGs and vOTU in field names votu_class_appr, votu_seq_comp_appr, votu_db refer to Uncultivated Virus Genome (MIUViG) and virus Operational Taxonomic Units.

Is there a reason that these terms are taxonomically scoped? If not, we suggest to remove the implicit taxonomic scope and make them relevant for a broader spectrum of DNA derived data (Fungi, Prokaryotes, Animals etc.).
See also https://github.com/gbif/doc-publishing-dna-derived-data/issues/133

**Comment by only1chunts** [comment]
Thanks for bringing this up, personally I agree with your suggestion. I will add it to the agenda for the next working group call (24th May) for wider discussion. Notes will be added here after the call.

**Comment by lschriml** [comment]
I think this suggestion is a good idea.
Lynn

**Comment by lschriml** [comment]
Agreement on this update on the CIG call.
Will update in the spreadsheet.

**Comment by thomasstjerne** [comment]
Thanks for addressing this so fast!
Will this then apply to MIxS v6 already?
i.e.:
Structured comment name | MIxS ID
------------ | -------------
otu_class_appr | MIXS:0000085
otu_seq_comp_appr | MIXS:0000086 
otu_db | MIXS:0000087

**Comment by only1chunts** [comment]
Yes all 3 MIXS ID (term names, structured comment names, and definitions) will be updated in the v6 update coming soon. Thanks.

**Comment by lschriml** [comment]
Yes

**Comment by only1chunts** [comment]
The following updates have been made in the MIxS6 spreadsheet "MIUVIG_Checklist_v6" tab:
**MIXS:0000085**
```
Term name - OTU classification approach
Structured comment name -  otu_class_appr 
Definition - Cutoffs and approach used when clustering “species-level” OTUs. Note that results from standard 95% ANI / 85% AF clustering should be provided alongside OTUS defined from another set of thresholds, even if the latter are the ones primarily used during the analysis
```
**MIXS:0000086**
```
Term name -  OTU sequence comparison approach
Structured comment name - otu_seq_comp_appr 
Definition - Tool and thresholds used to compare sequences when computing "species-level" OTUs
```

**MIXS:0000087**
```
Term name -  OTU database
Structured comment name - otu_db
Definition - Reference database (i.e. sequences not generated as part of the current study) used to cluster new genomes in "species-level" OTUs, if any
```
