### ISSUE TITLE
Update definition of sample material processing [MIXS:0000016]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#146]
**Current term details**
```
Term name - sample material processing
Term ID - MIXS:0000016
Structured comment name - samp_mat_process
Definition - Any processing applied to the sample during or after retrieving the sample from environment. This field accepts OBI, for a browser of OBI (v 2018-02-12) terms please see http://purl.bioontology.org/ontology/OBI
Expected value - text or OBI
Value syntax - {text}\|{termLabel} {[termID]}
Example - filtering of seawater, storing samples in ethanol
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):

```
** Definition - A brief description of any processing applied to the sample during or after retrieving the sample from environment, or a link to the relevant protocol(s) performed. 
** Expected value - text
** Value syntax - {text}
```

**Additional context**
This change has been made directly in the v6 Cor to Edit sheet, but no evidence of discussion anywhere in GitHub or note. 

@lschriml & @ramonawalls , Are we OK with the suggested update to definition, expected value and syntax?

**Comment by lschriml** [comment]
Hello @only1chunts - in general we have been moving to have the definitions, etc., to be more linked to ontologies. 

I prefer the 'Current term details' above.
What do you think ?

Cheers,
Lynn

**Comment by pbuttigieg** [comment]
Suggested qualifications: 

>** Definition - A brief description of any processing applied to the sample during or after retrieving the sample from the environment, or (preferred) a persistent link (e.g. a DOI) to the relevant protocol(s) performed.

**Comment by lschriml** [comment]
Update in the spreadsheet. 
Value syntax - {text} or {URI} or {termLabel} {[termID]}

**Comment by only1chunts** [comment]
@thomasstjerne suggested we update the structured comment name also:
`Structured comment name - samp_mat_process`
to 
`Structured comment name - sample_mat_process`

Any objections?

**Comment by only1chunts** [comment]
MIXS:0000111 (samp_vol_we_dna_ext) will not be possible to use sample_vol_we_dna_ext as that exceeds 20char. so to be consisent we may need to use samp_ for all. which will mean a change to  MIXS:0000002 (sample_collec_device) and MIXS:0001225 (sample_collec_method)

**Comment by only1chunts** [comment]
Unless anyone has any objection I am going to change the term structured comment names to use "samp_" instead of "sample_". As seen from the list below there are only 4 terms that use sample_ compared to many many terms that use samp_

From core:
**sample_name** [MIXS:0001107]
**sample_collec_device** [MIXS:0000002]
**sample_collec_method** [MIXS:0001225]
samp_mat_process
samp_size
samp_vol_we_dna_ext
samp_stor_temp
samp_stor_dur
samp_stor_loc

from packages:
occup_density_samp
occup_samp
oxy_stat_samp
rel_samp_loc
room_samp_pos
samp_capt_status
samp_collect_point
samp_dis_stage
samp_floor
samp_loc_corr-rate
samp_md
samp_preserv
samp_room_id
samp_salinity
samp_sort_meth
samp_subtype
samp_time_out
samp_transport_cond
samp_tvdss
samp_weather
samp_well_name


From proposed FOOD package(s):
samp_pooling
samp_rep_biol
samp_rep_tech
samp_source_mat_cat
samp_stor_device
samp_stor_media
samp_transport_cont
samp_transport_dur
samp_transport_temp
**sample_purpose** [MIXS:0001151]
samp_room_id
samp_floor
samp_type
num_samp_collect
area_samp_size
samp_loc_condition
samp_surf_moisture

**Comment by only1chunts** [comment]
the change to the definition as per the original thread in this ticket has been completed in all relevant MIxSv6 sheets
