### ISSUE TITLE
Voucher

### ISSUE THREAD

**Issue by ndheilly** [GenomicsStandardsConsortium/mixs#157]
The new term below is proposed by Adam Schneider, collaborator on the symbiont-associated package:

Here is the associated email message: "The only thing you may want to consider, for zoologists or botanists, is where the best place to include a voucher number. Usually these are in the form of a collection acronym, e.g. US for the Smithsonian, and an accession number. Here's an example from GenBank, where the data is structured in the specimen-voucher:
https://mcz.harvard.edu/files/mcz/files/guidelines_for_submitting_to_genbank.pdf "

In response to his email, I proposed to add the following term. 

Term name - Specimen-Voucher  
Structured comment name - Voucher
Definition - primary identifier of the physical specimen from which the sequence was obtained, and is intended for use in cases where the voucher/sample is still available (e.g., museums, herbaria, frozen tissue collections)
Expected value - [text]
Value syntax - [institution_code:collection_code:specimen_id]
Example - [MCZ:Mamm:12345]
Preferred unit - [if appropriate]
Package(s) - [host-associated, symbiont-associated, etc.]

```

**Additional context**
Add any other context about the new term here.

**Comment by only1chunts** [comment]
Hi, 
We've used the term :
MIXS:0000026
Term name - source material identifiers
Structured comment name -  source_mat_id 
Definition - A unique identifier assigned to a material sample (as defined by http://rs.tdwg.org/dwc/terms/materialSampleID, and as opposed to a particular digital record of a material sample) used for extracting nucleic acids, and subsequent sequencing. The identifier can refer either to the original material collected or to any derived sub-samples. The INSDC qualifiers /specimen_voucher, /bio_material, or /culture_collection may or may not share the same value as the source_mat_id field. For instance, the /specimen_voucher qualifier and source_mat_id may both contain 'UAM:Herps:14' , referring to both the specimen voucher and sampled tissue with the same identifier. However, the /culture_collection qualifier may refer to a value from an initial culture (e.g. ATCC:11775) while source_mat_id would refer to an identifier from some derived culture from which the nucleic acids were extracted (e.g. xatc123 or ark:/2154/R2). 


The definition has already been flagged for discussion before v7 #149 so if there are changes you think would help please feel free to add comments to that thread. I'll close this one now.
Thanks.
