### ISSUE TITLE
symbiotic relationship for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#169]
**New term details**
```
Term name - symbiotic relationship
Structured comment name - symbiotic_rel
Definition - Type of host dependence for the symbiotic organism.
Expected value - enumeration 
Value syntax - [facultative\|obligate]
Example - obligate 
Package(s) - symbiont-associated 
Already assigned MIXS ID : MIXS:0001315
```

**Additional context**
This is a term requested as part of the Symbiont package

**Comment by only1chunts** [comment]
How does this term differ from observed biotic relationship #168 ?
@ndheilly, Could the observed biotic relationship be expanded to include this use case?

**Comment by ndheilly** [comment]
The two terms "observed biotic relationship" #168, are "symbiotic relationship" #169 and must remain so for several reasons:
- symbiotic relationship is mandatory: it determines whether the association with the host is facultative or obligate.
- observed biotic relationship is conditional because it is often unknown, and because the relationship can vary between species, strains of host and parasite, and changes over time

**Comment by ramonawalls** [comment]
We agreed to change the name of this term to “host dependence” so it will be more distinct from “observed biotic relationship” (#168 ) and “type of symbiosis” (#170 ).

Updated spreadsheet.

**Comment by only1chunts** [comment]
Just for clarity:
**New term details**
```
MIXS ID : MIXS:0001315
Term name - host dependence
Structured comment name - host_dependence	
Definition - Type of host dependence for the symbiotic host organism to its host.
Expected value - enumeration 
Value syntax - [facultative\|obligate]
Example - obligate 
Package(s) - symbiont-associated 
```

in[MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)

**Comment by ndheilly** [comment]
Can the term (#169) name be changed to type_dependence given that it already assumes that the organism is dependent to a host? 
The term  Update MIXS:0000028 - observed biotic relationship (#168) could be named host_dependence to question whether the organism is dependent to a host or not.

MIXS ID : MIXS:0001315
Term name - type of host dependence
Structured comment name - type_dependence	
Definition - Type of host dependence for the symbiotic host organism to its host.
Expected value - enumeration 
Value syntax - [facultative\|obligate]
Example - obligate 
Package(s) - symbiont-associated 

Term name - dependence to a host
Term ID - MIXS:0000028
Structured comment name - host_dependence
**Definition - Please indicate if the sampled organism was free-living or in a symbiotic relationship at the time of sampling. For symbiotic organisms you may wish to consider using the symbiont-associated package that includes terms for type_of_symbiosis [MIXS:0001307] and host_of_host term details.
Expected value - enumeration
** Value syntax - [free living|symbiotic]
Example - free living
Preferred unit -
Package(s) - MIxS core
