### ISSUE TITLE
type of symbiosis - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#170]
**New term details**
```
Term name - type of symbiosis
Structured comment name - type_of_symbiosis
Definition - Type of biological interaction established between the symbiotic organism and its respective host. 
Expected value - enumeration
Value syntax - [commensalistic\|mutualistic\|parasitic]
Example - parasitic
Package(s) - symbiont-associated
Already assigned MIXS ID : MIXS:0001307
```

**Additional context**
Term created as part of Symbiont associated package.

**Comment by only1chunts** [comment]
This is another sort of "observed biotic relationship" #168, along with "symbiotic relationship" #169
Is splitting out all the different sorts of relationships into separate fields wise? what is the rational for doing so? is there a better way to handle this?
@ndheilly, please comment.

**Comment by ndheilly** [comment]
The "observed biotic relationship" did not exist when we created this package and was added later on. Yes these terms appear to be one and the same. I am happy that this term was added to the core package and we should amend the manuscript accordingly.

**Comment by ramonawalls** [comment]
This term is fine as is. It is the observed biotic relationship that needs to change. See #168

**Comment by only1chunts** [comment]
confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)

**Comment by ndheilly** [comment]
In most definitions of the SA package, the host of the sample is now called: the symbiotic host organism.
For consistency with other terms in the SA package, the definition now needs to be modified to:

Term name - type of symbiosis
Structured comment name - type_of_symbiosis
Definition - Type of biological interaction established between the symbiotic host organism being sampled and its respective host. 
Expected value - enumeration
Value syntax - [commensalistic\|mutualistic\|parasitic]
Example - parasitic
Package(s) - symbiont-associated
Already assigned MIXS ID : MIXS:0001307

**Comment by only1chunts** [comment]
thanks for spotting this. I have updated the Mixs v6 sheet with your suggested definition. 
NB - if you add comments to a closed ticket please reopen it or tag me or something to make sure it doesn't get missed, thanks.
