### ISSUE TITLE
life cycle type - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#171]
**New term details**
For us to assess a new term request we require the following details:
```
Term name - life cycle type
Structured comment name - life_cycle_type
Definition - Type of life cycle, level of complexity of the symbiotic organism life cycle.
Expected value - type of life cycle of the symbiotic organism (host of the samples)
Value syntax - [complex life cycle:#hosts|simple life cycle]
Example - complex life cycle: 3 hosts
Package(s) - Symbiont-associated 
Already assigned MIXSID : MIXS:0001300
```

**Additional context**
This is a term requested as part of the Symbiont package

**Comment by only1chunts** [comment]
looks fine to me

**Comment by pbuttigieg** [comment]
Discussed in today's CIG call:
* Scoping a little unclear, this could be more generic if it's not bound to the definition and we go by the label
* Options: 
  * relabel to symbiont_lifecycle_type or similar, as this is using terminology specific to this field
  * make more generic by modifying definition (remove symbiosis) 

In the symbiosis field, this means - according to our symbiont-associated team - the number of hosts a symbiont goes through during its lifecycle. 

Concerns: 
* Moving away from describing the sample, this is species information 
  * A long standing issue with MIxS - where do we draw the line in natural history?   
* The original definition is circular
* The value field is bespoke and complex. Defer to later generic cleanup in MIxS.

Given that this is the only package requesting this, we would rescope to:

```
Term name - symbiotic life cycle type
Structured comment name - sym_life_cycle_type
Definition - The type of the symbiotic organism's life cycle, expressed in the number of hosts the organism occupies. Simple life cycles occur within one host, complex ones in many.
Expected value - type of life cycle of the symbiotic organism (host of the samples)
Value syntax - [complex life cycle: [number of hosts]|simple life cycle]
Example - complex life cycle: 3
Package(s) - Symbiont-associated 
Already assigned MIXSID : MIXS:0001300
```

**Comment by ramonawalls** [comment]
Updated the definition and labels as described above and according to the agreed upon naming pattern (symbiotic host organism).

**Comment by only1chunts** [comment]
Sorry to reopen this one, but I think the definition still needs a little more detail to be clear that its asking for prior knowledge of the species being sampled. My suggestion below:

```
Term ID - MIXS:0001300
Structured comment name - sym_life_cycle_type
Term name - symbiotic host organism life cycle type
** Definition - Type of life cycle of the symbiotic host species (the thing being sampled), expressed as the number of hosts it occupies in its normal life cycle. Simple life cycles occur within a single host, complex ones within multiple hosts.
Expected value - type of life cycle of the symbiotic organism (host of the samples)
Value syntax - [complex life cycle:#hosts|simple life cycle]
Example - complex life cycle: 3 hosts
package - Symbiont associated

```

**Comment by ramonawalls** [comment]
This is better, Chris.

**Comment by only1chunts** [comment]
Now updated in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)

**Comment by ndheilly** [comment]
Upon careful revision, we propose to simplify this term usage to indicate only whether the life cycle is simple or complex
for consistency with other defintions of the host being sampled in other terms, we need to change reference to the host being sampled to "symbiotic host organism".
We propose the following revision:

Term ID - MIXS:0001300
Structured comment name - sym_life_cycle_type
Term name - symbiotic host organism life cycle type
** Definition - Type of life cycle of the symbiotic host organism. Organism with complex life cycles use different hosts over the course of their life cycle.
Expected value - type of life cycle of the symbiotic host organism 
Value syntax - [complex life cycle|simple life cycle]
Example - complex life cycle
package - Symbiont associated

**Comment by only1chunts** [comment]
I have updated the definition to:

> Type of life cycle of the symbiotic host species (the thing being sampled). Simple life cycles occur within a single host, complex ones within multiple different hosts over the course of their normal life cycle.

and updated the value syntax and example as suggested above by @ndheilly

**Comment by ndheilly** [comment]
Ok
