### ISSUE TITLE
mode of transmission - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#172]
**New term details**
```
Term name - mode of transmission
Structured comment name - mode_transmission
Definition - Symbiont transmission mode to host from which it was sampled.
Expected value - enumeration
Value syntax - [horizontal:castrator\|horizontal:directly transmitted\|horizontal:micropredator\|horizontal:parasitoid\|horizontal:trophically   transmitted\|horizontal:vector transmitted\|vertical]
Example - horizontal:castrator
Packages(s) -   symbiont-assiociated
Already assigned MIXS ID - MIXS:0001312
```

**Additional context**
Term created as part of Symbiont associated package.

**Comment by only1chunts** [comment]
I have no idea if this is relevant to the specific sample, how does one know how a specific specimen got the symbiont? or is this a generic field for inclusion of external knowledge about how the symbiont is usually transmitted?
Is there any scope here to potentially include transmission of viruses? i.e. make the term more generic to be used in multiple packages?

**Comment by ndheilly** [comment]
Yes, it is a field for inclusion of general knowledge about how the symbiont is transmitted. the terms used have broade scope and are the same for macro-organisms, bacteria and viruses. Multiple terms can apply for some symbionts (mixte transmission includes horizontal transmission and vertical transmission, some viruses use vectors, but can also be horizontally transmitted)

**Comment by pbuttigieg** [comment]
In the CIG call today:

The generic issue of where MIxS stops in terms of its metadata scope is at play above. This needs a separate conversation in the CIG and is deferred here. 

Removing circularity in the definition....

```
Term name - mode of transmission
Structured comment name - mode_transmission
Definition - The process through which a symbiont entered the host from which it was sampled.
Expected value - enumeration
Value syntax - [horizontal:castrator\|horizontal:directly transmitted\|horizontal:micropredator\|horizontal:parasitoid\|horizontal:trophically   transmitted\|horizontal:vector transmitted\|vertical]
Example - horizontal:castrator
Packages(s) -   symbiont-assiociated
Already assigned MIXS ID - MIXS:0001312
```

**Comment by ramonawalls** [comment]
Updated the definition in the sheet.

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)

**Comment by ndheilly** [comment]
The way the host being sampled is referenced to in definitions Kereps changing. 
For consistency, the definition needs to be modofied as follow:

Term name - mode of transmission
Structured comment name - mode_transmission
Definition - The process through which the symbiotic host organism entered the host from which it was sampled.
Expected value - enumeration
Value syntax - [horizontal:castrator\|horizontal:directly transmitted\|horizontal:micropredator\|horizontal:parasitoid\|horizontal:trophically   transmitted\|horizontal:vector transmitted\|vertical]
Example - horizontal:castrator
Packages(s) -   symbiont-assiociated
Already assigned MIXS ID - MIXS:0001312

**Comment by only1chunts** [comment]
updated the definition in mixs v6 sheet as provided above by @ndheilly
