### ISSUE TITLE
observed host symbionts - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#175]
**New term details**
```
Term name - observed host symbionts
Structured comment name -host_symbiont
Definition - The taxonomic name of the organism(s) found living in mutualistic, commensalistic, or parasitic symbiosis with the specific host. For cases when the specific host of the sample is a symbiont this field should refer to other organisms it is associated with. E.g.: hyperparasite species X (parasite of the parasite)
Expected value - symbionts of the symbiotic organism (host of the samples). e.g.: annotating a sample collected from a trematode with a nematomorpha cyst consider: species name of the nematomorph; {species name} or {common name}
Value syntax - {text}
Example - Paragordius varius
Packages(s) - symbiont-assiociated
```

**Additional context**
Term created as part of Symbiont associated package.

**Comment by ndheilly** [comment]
the term is already present in other packages

**Comment by ramonawalls** [comment]
I think this one is fine.

**Comment by only1chunts** [comment]
it seems we also discussed this term back in Feb too and had a ticket #110 for it! No worried its now confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
