### ISSUE TITLE
host specificity type - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#176]
**New term details**
```
Term name - host specificity type
Structured comment name -specificity_type
Definition - Level of specificity of symbiont-host interaction: e.g. generalist (symbiont able to establish associations with distantly related hosts) or species-specific.
Expected value - enumeration
Value syntax - [family-specific|generalist|genus-specific|species-specific]
Example - species-specific
Packages(s) - symbiont-assiociated
Already assigned MIXS ID - MIXS:0001308
```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by only1chunts** [comment]
this sounds more like general information about the species rather than sample-specific details. Is it relevant to the checklist of sample information?

**Comment by ndheilly** [comment]
Coupled with the term host_of_the_symbiont_role, it provides important information on the symbiont-host relationship that we would like to be able to use for meta-analyses down the line.

**Comment by ramonawalls** [comment]
To be consistent with other terms in the package, I changed the structured comment name to host_specificity.  “Type” adds no information and doesn’t fit in 20 characters.

Definition is good as is.

**Comment by only1chunts** [comment]
For clarity the term details are:
```
Term name - host specificity
Term ID - MIXS:0001308
Structured comment name - host_specificity
Definition - Level of specificity of symbiont-host interaction: e.g. generalist (symbiont able to establish associations with distantly related hosts) or species-specific.
Expected value - enumeration
Value syntax - [family-specific|generalist|genus-specific|species-specific]
Example - species-specific
Packages(s) - symbiont-assiociated
```
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)

**Comment by ndheilly** [comment]
ok
