### ISSUE TITLE
host of the symbiont role - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#177]
**New term details**
```
Term name - host of the symbiont role
Structured comment name -symbiont_host_role
Definition - Role of the host in the life cycle of the symbiotic organism.
Expected value - enumeration
Value syntax - [accidental|dead-end|definitive|intermediate|paratenic|reservoir|single host]
Example - intermediate
Packages(s) - symbiont-assiociated
Already assigned MIXS ID - MIXS:0001303
```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by ramonawalls** [comment]
I think this one is clear as is.

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
