### ISSUE TITLE
host cellular location [MIXS:0001313] - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#179]
**New term details**
```
Term name - host location
Structured comment name -host_location
Definition - Location of the symbiotic organism within its host: e.g. intracellular if present within host cells or extracellular if present outside of host cells.
Expected value - enumeration
Value syntax - [intracellular|extracellular|not determined]
Example - extracellular
Packages(s) - symbiont-assiociated
Term ID - MIXS:0001313
```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by only1chunts** [comment]
The name and definition are incongruent, I.e. the required value is not the location of the host, but the location within the host. 
I suggest the name is changed to “location within host” (loc_in_host). 
```
Term name = location within host
Structured comment name = loc_in_host
```
Additionally, do we need a second term (#178) for "host tissue location" when this term could easily cover both aspects?

**Comment by ndheilly** [comment]
We must keep a separate term for host-tissue-location. This one will be commonly used regardless of the type of symbiont.

I do not think that location_within_host would be a good name for the item aimaing at determining whether the organism is intracellular or extracellular... Yes, I guess we could be combine "host location" and "intracellular location" if you want to reduce the number of lines. Is this what you mean?

Term name - host location
Structured comment name -host_location
Definition - Location of the symbiotic organism within its host: e.g. intracellular if present within host cells or extracellular if present outside of host cells.
Expected value - enumeration
Value syntax - [extracellular|intracellular|intracellular_nucleus|intracellular_cytoplasm|intracellular_organella|not determined]
Example - extracellular
Packages(s) - symbiont-assiociated

**Comment by only1chunts** [comment]
I'm just thinking we dont want to proliferate very similar terms when we dont need to, so if location within host can be used for both tissue and intra/extracellular then we should.
With regards to the name "host location" to most people is going to mean physical location of the host, which I don't think is what is intended here(is it?), so the name probably needs to change. Is location the correct word? would site be better?

**Comment by ndheilly** [comment]
No I do not think they can be combined. This is one of the main point of need for this package!
What we really need is to identify the host species, tissue , cell type and then for intracellular organisms only, the cell compartment…
For both intracellular and extracellular organisms we need to indicate separately whether the organism is collected from the heart, gut or the liver etc.. similar symbiont can be collected from different tissues… they will likely differ because they live in different environments.
But whether the symbiont is intracellular or extracellular is not likely to change from one sample to another. 

To give you some perspective, what you are proposing is the same as saying that we can say that an organism was collected from water, and host, or soil, in the same term as indicating that it is collected in a mountain, desert or from a deep sea hydrothermal vent! 

I agree that location is not perfect. We started with tissue but it caused some issues for those working on organisms that infect the blood. If we consider a blood a tissue, we can change to tissue_site instead of location. What do you reckon?

**Comment by only1chunts** [comment]
These are sounding very similar to the triple-level environment terms we collect already as part of the core:
broad-scale environmental context
local environmental context
environmental medium

**Comment by ramonawalls** [comment]
@ndheilly I agree with your need for this term as well as the tissue term.  How do you feel about “host cellular location” as a more specific label?

**Comment by ndheilly** [comment]
Host cellular location sounds good to me. agreed.

**Comment by only1chunts** [comment]
Did this term get subsumed into the newly suggested term "host of the symbiotic host environemental medium" [MIXS:0001326] #198 ?

**Comment by lschriml** [comment]
symbiotic host cellular location
          the cellular location of the symbiotic host in the host of the symbiotic host

**Comment by pbuttigieg** [comment]
```
Term name - location of the smaller symbiont in the larger symbiont
Structured comment name - symbiont_loc
Definition - Given a symbiotic relationship between a smaller and larger organism, this field captures the location of the smaller symbiont within the larger one: e.g. intracellular if present within larger symbiont's cells or extracellular if present outside of larger symbiont's cells.
Expected value - enumeration
Value syntax - [extracellular|intracellular|intracellular_nucleus|intracellular_cytoplasm|intracellular_organella|not determined]
Example - extracellular
Packages(s) - symbiont-assiociated
```

I don't, however, actually think this is needed. As @only1chunts suggested, this can be covered in the symbiont-specifice env_local

**Comment by ndheilly** [comment]
Again, to ensure that the host of the sampled is referenced to using exactly the same vocabulary throughout the package, the definition needs to be changed to:

Term name - cellular location
Structured comment name - symbiont_loc
Definition - This field captures the location of the symbiotic host organism within the host from which it was sampled: e.g. intracellular if the symbiotic host organism is localized within the cells or extracellular if the symbiotic host organism is localized outside of cells.
Expected value - enumeration
Value syntax - [extracellular|intracellular|intracellular_nucleus|intracellular_cytoplasm|intracellular_organella|not determined]
Example - extracellular
Packages(s) - symbiont-assiociated

**Comment by ramonawalls** [comment]
Minor changes to the term name, structured comment name and definition.

Term name - symbiont cellular location
Structured comment name - symb_cell_loc
Definition - The location of the symbiotic host organism within the host from which it was sampled: e.g. intracellular if the symbiotic host organism is localized within the cells or extracellular if the symbiotic host organism is localized outside of cells.
Expected value - enumeration
Value syntax - [extracellular|intracellular|intracellular_nucleus|intracellular_cytoplasm|intracellular_organelle|not determined]
Example - extracellular
Packages(s) - symbiont-assiociated


TODO: Update spreadsheet

**Comment by only1chunts** [comment]
for consistency with the other terms we need to use the word host instead of symbiont in the name:
```
term name - host cellular location
structured comment name - host_cellular_loc
```

**Comment by only1chunts** [comment]
updated in  [v6 spreadsheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055), and added to [log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
