### ISSUE TITLE
No ENVO ID requested in spreadsheets 

### ISSUE THREAD

**Issue by pbuttigieg** [GenomicsStandardsConsortium/mixs#18]
Currently, the spreadsheets that are downloadable from the gensc.org website *do not* clearly instruct users to supply the ID (in CURIE format), just the term label.

This is very risky as only the ID is authoritative. Can this be updated right away? 

Users are submitting poor annotations right now.

A valid example would be
"air [ENVO:00002005]"

**Comment by lschriml** [comment]
Hello Pier,
   Thank you for pointing this out.

Pelin, can you look into this ? 
I think it makes sense to add the ID. 

What do you think ?

Cheers,
Lynn

**Comment by pyilmaz** [comment]
MIxS v5 should fix this issue

**Comment by ramonawalls** [comment]
This is fixed in MIxS 5. See https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/review/mixs_v5_review.xlsx.

**Comment by ramonawalls** [comment]
@folker Can you please make me a contributor to this repo, so I can close issues?

**Comment by only1chunts** [comment]
related discussion for MIxS v6 #106

**Comment by ramonawalls** [comment]
This issue was fixed but never closed. Closing now.
