### ISSUE TITLE
intracelullar location - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#180]
**New term details**
```
Term name - intracelullar location
Structured comment name -intracelullar_loc
Definition - For intracellular symbionts, location of the symbiotic organism within its host cell.
Expected value - enumeration or text
Value syntax - [organella|nucleus] or {text}
Example - 
Packages(s) - symbiont-assiociated
Already assigned MIXS ID - MIXS:0001314
```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by only1chunts** [comment]
I think maybe could be merged into "location within host" #179

**Comment by ndheilly** [comment]
Ok to discuss this

**Comment by ramonawalls** [comment]
I agree that this term could be merged with “host location” by adding nucleus, organelle, and {text} to the other vocabulary.

**Comment by ndheilly** [comment]
If that works for you. ok with me.

**Comment by only1chunts** [comment]
I believe we do not require this term anymore, so can it be deleted it from the "Newpackage-SA" sheet in the v6 Spreadsheet? I have put a strike through on it for now until someone confirms we can delete it.

**Comment by ndheilly** [comment]
Ok. we reviewed #179 and agree with removing #180

**Comment by ramonawalls** [comment]
TODO: Update spreadsheet (remove term) and change log.

**Comment by only1chunts** [comment]
removed from [v6 spreadsheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055), nothing to add to change log as the term was a new term that we are no longer adding.
