### ISSUE TITLE
duration of association with the host - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#181]
**New term details**
```
Term name - duration of association with the host
Structured comment name -association_duration
Definition - Time spent in host of the symbiotic organism at the time of sampling; relevant scale depends on symbiotic organism and study.
Expected value - value
Value syntax - {float} {unit}
Example - 
Packages(s) - symbiont-assiociated
Already assigned MIXS ID - MIXS:0001299
```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by ramonawalls** [comment]
I think this term is fine as is.

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
