### ISSUE TITLE
host of the symbiont common name - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#183]
**New term details**
```
Term name - host of the symbiont common name
Structured comment name -symb_host_name
Definition - Common name of the host of the symbiotic organism under study.
Expected value - unique identifier
Value syntax - {text}
Example - snail
Packages(s) - symbiont-assiociated

```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by ramonawalls** [comment]
Update as per agreed-upon pattern.

```
Term name - host of the symbiotic host common name
Structured comment name -host_of_host_name
Definition - Common name of the host of the symbiotic host organism.
Expected value - common name
Value syntax - {text}
Example - snail
Packages(s) - symbiont-assiociated

```

The expected value was 'unique identifer', but that did not match the definition, syntax, or example, so I changed it to "common name".

spreadsheet updated

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
