### ISSUE TITLE
host of the symbiont subject id - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#185]
**New term details**
```
Term name - host of the symbiont subject id
Structured comment name -symb_host_id
Definition - A unique identifier by which each host of the symbiotic organism subject can be referred to, de-identified, e.g. #H14.
Expected value - unique identifier
Value syntax - {text}
Example - H3
Packages(s) - symbiont-assiociated

```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by ramonawalls** [comment]
Update as per agree-upon pattern.

```
Term name - host of the symbiotic host subject id
Structured comment name -host_of_host_sub_id
Definition - A unique identifier by which each host of the symbiotic host organism subject can be referred to, de-identified, e.g. #H14.
Expected value - unique identifier
Value syntax - {text}
Example - H3
Packages(s) - symbiont-assiociated

```

spreadsheet updated

I'm closing this, but the examples aren't actually very good, since they are supposed to be unique IDs.

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
