### ISSUE TITLE
host of the symbiont family relationship - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#187]
**New term details**
```
Term name - host of the symbiont family relationship
Structured comment name -symb_host_family_rel
Definition - Relationships to other hosts of symbiotic organism in the same study; can include multiple relationships.
Expected value - relationship type;arbitrary identifier
Value syntax - {text};{text}
Example - 
Packages(s) - symbiont-assiociated

```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by only1chunts** [comment]
may need to be part of the discussion on sample relationships for v7! #109

**Comment by ramonawalls** [comment]
Updating per agreed-upon pattern.

```
Term name - host of the symbiotic host family relationship
Structured comment name -host_of_host_fam_rel
Definition - Familial relationship of the host of the symbiotic host organisms to other hosts of symbiotic host organism in the same study; can include multiple relationships.
Expected value - relationship type;arbitrary identifier
Value syntax - {text};{text}
Example - 
Packages(s) - symbiont-assiociated

```

Leaving this issue for @only1chunts 's comment about relationships, but it is okay for MIxS 6.

Spreadsheet updated.

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
