### ISSUE TITLE
host of the symbiont genotype - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#190]
**New term details**
```
Term name - host of the symbiont genotype
Structured comment name -symb_host_genotype
Definition - Observed genotype of the host of the symbiotic organism.
Expected value - genotype
Value syntax - {text}
Example - 
Packages(s) - symbiont-assiociated

```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by ramonawalls** [comment]
Update labels and definition per agreed upon pattern.

```
Term name - host of the symbiotic host genotype
Structured comment name - host_of_host_geno
Definition - Observed genotype of the host of the symbiotic host organism.
Expected value - genotype
Value syntax - {text}
Example - 
Packages(s) - symbiont-assiociated

```

spreadsheet updated

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
