### ISSUE TITLE
host of the symbiont total mass - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#193]
**New term details**
```
Term name - host of the symbiont total mass
Structured comment name -symb_host_tot_mass
Definition - Total mass of the host of the symbiotic organism at collection, the unit depends on the host.
Expected value - measurement value
Value syntax - {float} {unit}
Example - 
Packages(s) - symbiont-assiociated

```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by ramonawalls** [comment]
At the CIG discussion on 7/2, we agreed to rename symbiont terms as "host of host".

```
Term name - host of the symbiotic host total mass
Structured comment name -host_of_host_tot_mass
Definition - Total mass of the host of the symbiotic host organism at collection, the unit depends on the host.
Expected value - measurement value
Value syntax - {float} {unit}
Example - 
Packages(s) - symbiont-assiociated

```

Spreadsheet has been updated.

**Comment by ramonawalls** [comment]
Remove an underscore so short name is only 20 characters.

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
