### ISSUE TITLE
sample storage solution - for Symbiont-associated (SA) package

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#194]
**New term details**
```
Term name - sample storage solution
Structured comment name -samp_store_sol
Definition - Solution within which sample was stored, if any.
Expected value - solution name
Value syntax - {text}
Example - 
Packages(s) - symbiont-assiociated
Already assigned MIXS ID - MIXS:0001317
```
**Additional context**
Term created as part of Symbiont associated package.

**Comment by only1chunts** [comment]
could this just be a part of the "sample material processing" MIXS:0000016 ?

**Comment by ndheilly** [comment]
Most general sample processing information were copied from other packages and are indeed not novel.

**Comment by pyilmaz** [comment]
Sample material processing is really broad, and if it relevant for symbiont studies, we should capture the storage solution. I feel an example would be useful, i.e 5% ethanol, formeldehyde (if that is what is meant)

**Comment by ramonawalls** [comment]
We can add an example for a future release, but for now there are no serious problems with this term, and I approve it, with the addition of an example as Pelin suggested.

**Comment by ramonawalls** [comment]
SA spreadsheet updated with example.

**Comment by only1chunts** [comment]
in[ MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
