### ISSUE TITLE
new terms for  environmental local context to symbiotic host organisms’s host

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#197]
**New term details**
For us to assess a new term request we require the following details:
```
Term name - host of the symbiotic host local environmental context
Structured comment name - host_of_host_env_loc
Definition - In this field, report the entity or entities which are in the local vicinity of the symbiotic host organism and which you believe have significant causal influences on your sample or specimen. Because the host of host is associated with another organism, these terms usually will be a body part of the host. For example, if the symbiotic host organism is an intestinal worm, its local environmental context will be the term for intestine from UBERON. Format (one term): termLabel [termID]; Format (multiple terms): termLabel [termID]|termLabel [termID]|termLabel [termID].
Expected value - Add term(s) that identify environmental entities having causal influences upon the entity at time of sampling, multiple terms can be separated by pipes.
Value syntax - {termLabel} {[termID]}
Example - small intestine[uberon:0002108]
Preferred unit - 
Package(s) - SA
MIxS ID - mixs:0001325
```

**Additional context**
Add any other context about the new term here.

This term was added to the SA sheet in the MIxS6 document. 

@ndheilly and @only1chunts please check and close ticket.

**Comment by ndheilly** [comment]
This term needed a small modification for clarity. i think there was a mistake in referencing the symbiotic host organism and the host of host from which it was sampled.

Term name - host of the symbiotic host local environmental context
Structured comment name - host_of_host_env_loc
Definition - In this field, report the entity or entities which are in the direct environment of the symbiotic host organism and which you believe have significant causal influences on your sample or specimen. For symbiotic host organism it will often refer to a body part of the host of host. For example, if the symbiotic host organism is an intestinal worm, its local environmental context will be the term for intestine from UBERON. Format (one term): termLabel [termID]; Format (multiple terms): termLabel [termID]|termLabel [termID]|termLabel [termID].
Expected value - Add term(s) that identify environmental entities having causal influences upon the entity at time of sampling, multiple terms can be separated by pipes.
Value syntax - {termLabel} {[termID]}
Example - small intestine[uberon:0002108]
Preferred unit - 
Package(s) - SA
MIxS ID - mixs:0001325

**Comment by only1chunts** [comment]
I have some more tweaks to the definition and expected value:

Definition - For a symbiotic host organism the local anatomical environment within its host may have causal influences. Report the anatomical entity(s) which are in the direct environment of the symbiotic host organism being sampled and which you believe have significant causal influences on your sample or specimen.  For example, if the symbiotic host organism being sampled is an intestinal worm, its local environmental context will be the term for intestine from UBERON (http://uberon.github.io/). 

Expected value - UBERON term(s), multiple values can be separated by pipes.

@ndheilly please confirm these are OK?

**Comment by ndheilly** [comment]
Ok

**Comment by only1chunts** [comment]
Confirmed in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
