### ISSUE TITLE
New term for environmental medium specific to symbiotic host organism

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#198]
**New term details**
For us to assess a new term request we require the following details:
```
Term name - host of the symbiotic host environemental medium
Structured comment name - host_of_host_env_med
Definition - Report the environmental material(s) immediately surrounding the sybiotic host organism at the time of sampling. This usually will be a tissue or substance type from the host, but may be another material if the symbiont is external to the host. We recommend using classes from the UBERON ontology, but subclasses of 'environmental material' (http://purl.obolibrary.org/obo/ENVO_00010483) may also be used. EnvO documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS . Terms from other OBO ontologies are permissible as long as they reference mass/volume nouns (e.g. air, water, blood) and not discrete, countable entities (e.g. intestines, heart).
Expected value - An ontology term for a material such as a tissue type or excreted substance.
Value syntax - {termLabel} {[termID]}
Example - feces[uberon:0001988]
Preferred unit - 
Package(s) - SA
MIxS ID: mixs:0001326
```

**Additional context**
Add any other context about the new term here.

I have filled in the MIxS6 SA spreadsheet.

@ndheilly and @only1chunts, please check what I have written before closing.

**Comment by ndheilly** [comment]
There are a couple of typos that needed to be fixed.

Term name - host of the symbiotic host environmental medium
Structured comment name - host_of_host_env_med
Definition - Report the environmental material(s) immediately surrounding the symbiotic host organism at the time of sampling. This usually will be a tissue or substance type from the host, but may be another material if the symbiont is external to the host. We recommend using classes from the UBERON ontology, but subclasses of 'environmental material' (http://purl.obolibrary.org/obo/ENVO_00010483) may also be used. EnvO documentation about how to use the field: https://github.com/EnvironmentOntology/envo/wiki/Using-ENVO-with-MIxS . Terms from other OBO ontologies are permissible as long as they reference mass/volume nouns (e.g. air, water, blood) and not discrete, countable entities (e.g. intestines, heart).
Expected value - An ontology term for a material such as a tissue type or excreted substance.
Value syntax - {termLabel} {[termID]}
Example - feces[uberon:0001988]
Preferred unit - 
Package(s) - SA
MIxS ID: mixs:0001326

**Comment by only1chunts** [comment]
Confirmed changes in [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) and included in [v6 update log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
