### ISSUE TITLE
negative control type [MIXS:0001321]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#199]
**New term details**
```
Term name - negative control type
Term ID - MIXS:0001321
Structured comment name - neg_cont_type
Definition - Type of negative control.
Expected value - enumeration or text
Value syntax - [collection device control|collection tube control|DNA extraction blank control|PCR amplification control|swab control|syringe control] or {text}
Example -
Package(s) - negative control
```

**Additional context**
Add any other context about the new term here.

**Comment by pbuttigieg** [comment]
Related to #200 too.

This field seems to focus on the stage of a workflow or a bit of apparatus, while the positive one [clarified in today's CIG call, the definition is not clear] is expecting the name of the positive control used (if from a company) or some sort of textual description. 

It would be wise to align the value types expected by these fields, and to clarify the definitions in both. Right now this risks some difficulties downstream. 

Enumeration here may not be the best way, as the values are unbounded. Like the positive control field, I'd simply have this as textual, but leave some examples as indicated. 

I'd go more for:

```
Term name - negative control type
Term ID - MIXS:0001321
Structured comment name - neg_cont_type
Definition - The substance or equipment used as a negative control in an investigation.
Expected value - text
Value syntax - {text}
Example - [distilled water|phosphate buffer|empty collection device|empty collection tube|DNA-free PCR mix|sterile swab |sterile syringe]
Package(s) - negative control
```

**Comment by ramonawalls** [comment]
I agree with @only1chunts proposal, but we need confirmation from @josieburgin.

**Comment by only1chunts** [comment]
I have added the term with details below to the v6 CORE and set to "C" conditional mandatory for all checklists, with an occurence of "1".
```
Structured comment name - neg_cont_type	
Term name - negative control type
Definition - Type of negative control
Expected value - enumeration or text	
Value syntax - [collection device control|collection tube control|DNA extraction blank control|PCR amplification control|swab control|syringe control] or {text}
Term ID - MIXS:0001321
```

IF there are any changes requried to the above details please REOPEN this ticket (and tag me).

Term added to [v6 spreadsheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=567040283) and added to the [change log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
