### ISSUE TITLE
NTR: access and benefit sharing permit

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#20]
**Label:** access benefit sharing permit

**Short name  (ID):** abs_certificate (or abs_cert)

**Definition:** Identifier that points to the signed Access and Benefit Sharing (ABS) agreement for a particular (set of) sample(s), for compliance with the Ngoya Protocol requirements. Recommended to use the ABS Clearing House unique identifier registered at https://absch.cbd.int/search/nationalRecords?schema=absPermit. For more information about ABS, see https://absch.cbd.int/help/about. 

**Background:**
All samples collected after Oct 2014 in Nagoya signatory countries should have a signed access and benefit sharing (ABS) permit stating that they were collected in compliance with ABS agreements. The ABS clearing house (ABSCH) issues permanent identifiers, which can be searched by country or by reference at
https://absch.cbd.int/search/nationalRecords?schema=absPermit. 

Adding this new term was discussed and agreed upon at the Compliance and Interoperability Group meetings. The term cannot be required, because not all countries have signed the treaty. As a non-signatory country, NCBI could not enforce it or validate it, but they could store it. Groups like GGBN could make their own checklists that do include ABSCH IDs.

**Comment by ramonawalls** [comment]
@pbuttigieg this may be of interest to you. If you know of others outside the GSC list who are interested, please notify them as well.

**Comment by pbuttigieg** [comment]
Thanks! We could add this to SDGIO and link to the UN document ontology.

**Comment by ramonawalls** [comment]
This term was approved at the CIG calls. It will not be a required MIxS term, but once a new release is prepared, it will become part of the MIxS vocabulary.
