### ISSUE TITLE
positive control type [MIXS:0001322]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#200]
**New term details**
```
Term name - positive control type	
Term ID - MIXS:0001322
Structured comment name - pos_cont_type
Definition - Type of positive control.
Expected value - 
Value syntax - {term} or {text}
Example - 
Package(s) - +ve control
```

**Additional context**
Add any other context about the new term here.

**Comment by pbuttigieg** [comment]
Similar concerns as stated in #199 
Once again the definitions is circular.


```
Term name - 	positive control type	
Term ID - MIXS:0001322
Structured comment name - pos_cont_type
Definition - The substance, mixture, product, or apparatus used to verify that a process which is part of an investigation delivers a true positive.
Expected value - 
Value syntax - {term} or {text}
Example - 
Package(s) - +ve control
```


The examples should list both descriptions of "home made" positive controls as well as products from companies or standards agencies.

**Comment by ramonawalls** [comment]
Also agree with @pbuttigieg 's suggestion. Please respond @josieburgin

**Comment by only1chunts** [comment]
I have added the term with details below to the v6 CORE and set to "C" conditional mandatory for all checklists, with an occurence of "1".
```
Term name - positive control type	
Term ID - MIXS:0001322
Structured comment name - pos_cont_type
Definition - The substance, mixture, product, or apparatus used to verify that a process which is part of an investigation delivers a true positive.
Expected value - 
Value syntax - {term} or {text}
Example - 
Package(s) - Core
```

IF there are any changes requried to the above details please REOPEN this ticket (and tag me).


Term added to [v6 spreadsheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=567040283) and added to the [change log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
