### ISSUE TITLE
host variety or cultivar proposed MIXS:0001143

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#202]
Part of the 147 new terms for the Food packages #201 

**Current term details**
```
Term name - host variety or cultivar
Structured comment name - host_variety
Definition - The variety or cultivar of the host organism; the name given to a particular variety of organism to distinguish it from otherwise similar organisms of the same species.
Expected value - text
Value syntax - {text}
Example - romaine lettuce; Athena melons; Patio Snacker cucumbers
Term ID - MIXS:0001143
Package(s) - Food
```

**Suggested update(s)**
This term has been proposed in the new Food packages, but I think it is an exact duplicate of another new term MIXS:0001318 proposed during the tidy up of existing terms:
```
Term name - host subspecific genetic lineage
Term ID - MIXS:0001318
Structured comment name - host_subspecf_genlin 
Definition - Information about the genetic distinctness of the host organism below the subspecies level, e.g., serovar, serotype, biotype, ecotype, or any relevant genetic typing schemes like Group I plasmid. Subspecies should not be recorded in this term, but in the NCBI taxonomy. Supply both the lineage name and the lineage rank separated by a colon, e.g., biovar:abc123
Expected value - Genetic lineage below lowest rank of NCBI taxonomy, which is subspecies, e.g. serovar, biotype, ecotype, plus genetic lineage name.
Value syntax - {rank name}:{text}
Example - subvariety:glabrum
Preferred unit - 
Package(s) - host-associated AND plant-associated
```

**Additional context**
See ticket #73 for previous discussion around this topic

**Comment by lschriml** [comment]
I think these are distinct.

**Comment by ramonawalls** [comment]
Varieties and cultivars are essentially sub-species (but less formal), so the original definition is more accurate. I think this might already be in the plant specimen context. I will look it up. Otherwise, original definition is okay.

**Comment by ramonawalls** [comment]
This is not the same as the one in the plant specimen context, but would rather be the one in the plant- associated package. Ramona still needs to check.

**Comment by ramonawalls** [comment]
I learned something important (to me) today: variety is actually a taxonomic rank below subspecies, whereas cultivar is not a rank, but follows species. Even though cultivar is roughly equivalent to the taxonomic level of sub-species, varieties are not listed in NCBI taxonomy. Therefore, I think it is appropriate to include them within the definition of subspecific genetic lineage (MIXS:0000020). 

Actions: 
1) update definition of subspecific genetic lineage (I'll make a new ticket for this)
2) Replace MIXS:0001143 with MIXS:0000020 

@only1chunts I will take you in the new issue so you can update the spreadsheet and change log.

**Comment by ramonawalls** [comment]
Note that in the Plant Specimen Contextual Consensus (https://gensc.org/the-plant-specimen-contextual-data-consensus/, which will be turned into a checklist with MIxS 7), cultivar is indeed included under subspecific genetic lineage.
