### ISSUE TITLE
investigation_type multivalued? and possibility of additional legal values ?

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#203]
**Current term details**

NMDC is reevaluating its use of the [`investigation_type`](https://microbiomedata.github.io/nmdc-schema/investigation_type.html) slot. 

A colleague has suggested that this slot should [1) take multiple values and that 2) the range should be expanded.](https://docs.google.com/spreadsheets/d/1GZayIFIrY2jdoxRIpk9KDTBLiE71VVtb7YAd5ZSYGR0/edit#gid=860381937)

1) I have been looking at the specification in row 3 of [mixs_v5.xlsx](https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx?raw=true). It's not clear to me whether this is intended to be a multi-valued slot. For `env_broad_scale`, it **is** specified

> Format (multiple terms): termLabel [termID]|termLabel [termID]|termLabel [termID].

2) I don't have an exhaustive list of the allowed values we'd like to add, but I did want to raise this possibility. Do any MIxS stakeholders want to chime on on this?

**Comment by only1chunts** [comment]
hi,
"investigation_type" is one of the terms we are removing from the MIXS specifications as its entirely implicit in the checklist chosen. see #60

**Comment by lschriml** [comment]
if NMDC wants to utilized this type of information, and it differs from how investigation_type was used in the past, I would suggest creating a new term.

**Comment by pyilmaz** [comment]
The investigation type should not take multiple values, as each investigation type is a mixs checklist, with different requirements, so if you have a multi-investigation study, you should use the corresponding checklists

**Comment by turbomam** [comment]
NMDC is using an `investigation_type` slot that we define locally, so as to meet the needs listed above.

I like it when we can find overlapping solutions, but I will close this and leave it to @mslarae13 to reopen it or create a new issue if necessary.
