### ISSUE TITLE
add column to indicate if a term can have multiple values

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#204]
In order to make the MIXS 6 spreadsheet more easily convertible to LinkML, it would be useful to have a column to indicate if a term can have multiple values. Right now, the multi-values information seems to be in the description of the term.

see also https://github.com/GenomicsStandardsConsortium/mixs/issues/203

cc @cmungall @turbomam

**Comment by only1chunts** [comment]
Hi @wdduncan, the "occurrence" column in the spreadsheet is meant to show that. Its either "1" or "m" to indicate if the term can have 1 or multiple values. I'm not 100% sure its fully verified as correct, but it is where the information should be.

**Comment by wdduncan** [comment]
Thanks @only1chunts

**Comment by pyilmaz** [comment]
Hi @only1chunts! The occurrence column is indeed the one. The 0 value is legacy from when we moved depth and elevation to environmental packages; ie just indicates that they are not part of the main requirements, but may be mandatory in certain packages (soil, air, water...)

**Comment by only1chunts** [comment]
as this has now been answered I'm closing this ticket. Bill, if anything is unclear feel free to re-open it.

**Comment by turbomam** [comment]
I'm also interested in this issue. Thanks for the response @pyilmaz.

Are they legacy 0s and blanks going to be left as is? Is the meaning of those values (an the 1s and ms) reflected in the spreadsheet?

**Comment by turbomam** [comment]
This is mostly irrelevant now that the LinkML representation allows a term/slot to assert `multivalued: true`

The multi-valued implementation is straightforward in YAML and JSON representations of data. In TSV, cells with legal multiple values must be follow this pattern (even if the description say "multiple values can be separated with ';' or 'semicolon'):

`[red|blue|green]`

So we need more documentation and examples for that.

**Comment by ramonawalls** [comment]
This issue has been fixed with release 6.2
