### ISSUE TITLE
samp_taxon_id

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#205]
**New term details**
```
Term name - Taxonomy ID of DNA sample
Term ID - MIXS:0001320
Structured comment name - samp_taxon_id
Definition - NCBI taxon id of the sample.  Maybe be a single taxon or mixed taxa sample
Expected value - Taxonomy ID (organismal taxon or ‘synthetic metagenome’ of mock community)
Value syntax - {text} [NCBI:txid]
Example - Gut Metagenome [NCBI:txid749906]
Package(s) - required for +ve and -ive control packages, but should be included in all checklists
```

**Additional context**
Included in +/- control packages #25 , but as all data submitted to INSDC also must include a taxonomy ID I believe this could be a term included in core for all checklists.
The examples field could be used to specify the use of NCBI:txid2582415 for "blank sample" in the negative control package.

Note - the definition is specific to NCBI taxonomy, do we want to loosen that to allow usage of other taxonomies (see #128 )?

**Comment by ramonawalls** [comment]
Decision: add to core, stick with NCBITaxon ID. Good to. Update spreadsheet.

**Comment by only1chunts** [comment]
I've added it to the core as agreed. However, are we adding this as MANDATORY to all checklists, which will effectively make it the replacement of the "submitted to INSDC" term that we agreed to deprecate.

Also, @anjijohnston  for occurence is it 1 or M ? i.e. could we expect multiple NCBI taxon ID's per sample? I think its 1, but I just wanted to check.

**Comment by only1chunts** [comment]
I've gone with mandatory for all checklists, and set it to occurence =1. If there are any further changes to be made please reopen this ticket and add a comment about what needs updating.
new term added to [change log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823) and closed ticket.
