### ISSUE TITLE
update definition- freq_clean [MIXS:0000226]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#206]
**Current term details**
```
Term name - frequency of cleaning
Term ID - MIXS:0000226
Structured comment name - freq_clean
Definition - The number of times the building is cleaned per week
Expected value - measurement value
Value syntax - {integer}
Example -
Preferred unit - 
Package(s) - built environment, food production facility
```

**Suggested update(s)**
```
Term name - frequency of cleaning
Term ID - MIXS:0000226
Structured comment name - freq_clean
** Definition - The number of times the sample location is cleaned. Frequency of cleaning might be on a Daily basis, Weekly, Monthly, Quarterly or Annually.
** Expected value - enumeration or {text} 
** Value syntax - [ Daily\| Weekly\| Monthly\| Quarterly \| Annually\| other]
Example -
Preferred unit - 
Package(s) - built environment, food production facility
```

**Additional context**
Definition update suggested during the review of the Food packages. The newly suggested definition makes a fundamental change to the value expected here, i.e. the original definition is number per week, the new definition is fixing the number at 1 but asking for the time frame weekly, monthly etc.

**Comment by lschriml** [comment]
Agreed, this is more flexible.
However, the field field was defined per week, as that is how this data is usually collected in built environment studies.

**Comment by ramonawalls** [comment]
Will cause problems with backwards compatibility, but we agreed to make the change.

**Comment by only1chunts** [comment]
updated in [v6 spreadsheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=345753674) and added to [change log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823)
