### ISSUE TITLE
update definition - avg_occup [MIXS:0000775]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#207]
**Current term details**
```
Term name - average daily occupancy
Term ID - MIXS:0000775
Structured comment name - avg_occup		
Definition - Daily average occupancy of room
Expected value - value
Value syntax - {float}
Example - 2
Preferred unit - 
Package(s) - built environment, food production facility 
```

**Suggested update(s)**

Definition - Daily average occupancy of room. Indicate the number of person(s) daily occupying the sampling room.

**Additional context**
The new definition was suggested during the review of the food packages.

**Comment by lschriml** [comment]
Agreed, update.

**Comment by only1chunts** [comment]
done- updated in MIxS6 packages to edit, and added to change log
