### ISSUE TITLE
update - samp_type [MIXS:0000998]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#208]
**Current term details**
```
Term name - sample type
Term ID - MIXS:0000998
Structured comment name - samp_type
Definition - Type of material (i.e. sample) collected. Includes types like core, rock trimmings, drill cuttings, piping section, coupon, pigging debris, solid deposit, produced fluid, produced water, injected water, swabs, etc. If "other" is specified, please propose entry in "additional info" field
Expected value - enumeration
Value syntax - [core|rock trimmings|drill cuttings|piping section|coupon|pigging debris|solid deposit|produced fluid|produced water|injected water|water from treatment plant|fresh water|sea water|drilling fluid|procedural blank|positive control|negative control|other]
Example - solid deposit
Preferred unit - 
Package(s) - hydrocarbon resources-cores, hydrocarbon resources-fluids/swabs, food-food production facility, food-farm environment
```

**Suggested update(s)**

```
Definition - The type of material from which the sample was obtained. Samples are usually categorized as food, body products or tissues, or environmental material. This field accepts terms listed under environmental specimen (http://purl.obolibrary.org/obo/GENEPIO_0001246).
Expected value - GENEPIO:0001246
Value syntax - {termLabel} {[termID]}
Example - built environment sample [GENEPIO:0001248]
```

**Additional context**
Updates suggested during review of Food packages.
I'm not convinced that the changes suggested would work for all use cases, as the suggested "environmental specimen" ontology only contains a small number of terms and appears to overlap with the ENVO terms collected elsewhere.

**Comment by lschriml** [comment]
Agreed, these represent the same entity.

**Comment by only1chunts** [comment]
@lschriml , the question here is; is the new suggested definition of samp_type better or worse than the current definition? i.e. do we update samp_type definition or not.

**Comment by ramonawalls** [comment]
Leave value syntax as is. Change the example. Change definition to make it less specific.

`The type of material from which the sample was obtained. For the Hydrocarbon package, samples include types like core, rock trimmings, drill cuttings, piping section, coupon, pigging debris, solid deposit, produced fluid, produced water, injected water, swabs, etc. For the Food Package, samples are usually categorized as food, body products or tissues, or environmental material. This field accepts terms listed under environmental specimen (http://purl.obolibrary.org/obo/GENEPIO_0001246).`

Note that TDWG has a task group to define minimum metadata for a material. We should coordinate with them.

In NCBI, sample_type is defined as e.g. cell culture, tissue culture,...  Value from this term can be derived directly from BioProject. We need to figure out where this is coming from for sure.

TODO: Update this per above for MIxS 6, but open a new ticket to resolve general issues around this term for MIxS 7.

**Comment by ramonawalls** [comment]
This change was approved by Chris from the food package.

**Comment by only1chunts** [comment]
all instances in v6 spreadsheet updated to suggestions at the start of this ticket, and added to the[ change log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823).
