### ISSUE TITLE
update definition - solar_irradiance [MIXS:0000112]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#209]
**Current term details**
```
Term name - solar_irradiance	solar irradiance
Term ID - MIXS:0000112
Structured comment name - solar_irradiance
Definition - The amount of solar energy that arrives at a specific area of a surface during a specific time interval
Expected value - measurement value
Value syntax - {float} {unit}
Example - 1.36 kilowatts per square meter per day
Preferred unit - kilowatts per square meter per day, ergs per square centimeter per second
Package(s) - 
```

**Suggested update(s)**

Definition - The mean amount of solar energy that arrives at a specific area of a surface during the season.

**Additional context**
Update to definition suggested during the review  of Food packages.

**Comment by lschriml** [comment]
If we change the definition, I think it would change the intended usage of this term. My leaving the time interval with options, better serves the use case. 
If we used 'season' we may then need to create a term for each type of time interval.

**Comment by only1chunts** [comment]
agreed, no update required. 
I have updated the Food package tab in the [MIxS v6 Term Updates sheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) to use the same definition as the already existing term.
