### ISSUE TITLE
definition update : sample material processing 

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#21]
Hi,
Currently the definition for the attribute "sample material processing" is

> Any processing applied to the sample during or after retrieving the sample from   environment. This field accepts OBI, for a browser of OBI (v 2013-10-25)   terms please see http://purl.bioontology.org/ontology/OBI

Having just been looking through the OBI terms it seems like the ONLY appropriate term in OBI for this field would be [lavage](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0600044) ! Perhaps the definition of the term can be changed to:

> A brief description of any processing applied to the sample during or after retrieving the sample from   environment, or a link to the relevant protocol(s) performed.

**Comment by 79-6d** [comment]
Unfortunately I am not familiar with the OBI terms. I thought there are many relevant vocabularies that can be used for this term under [material processing](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000094&viewMode=All&siblings=false#). 

I am wondering if it is possible for samples to undergo multiple processes? Should we define how those records should be documented in this field? 

@lschriml @ramonawalls do you mind to please lend me a hand here? thank you so much!

**Comment by lschriml** [comment]
Looking at BioSample, how this term (sample material processing) has been used: 

        Stools Processing Device (bioMerieux) in combination with ZymoBIOMICS DNA Mini kit 
          (ZymoResearch)

         Fecal samples less than 6 hr old were collected from individual mice and stored at -80C 
             (doi:10.1186/s12866-018-1359-5). 

         flash frozen using LN2 and stored at -20C until processing.

--> this term is being populated with textual descriptions. 
Agree: remove the OBI reference.

Updated in MIxS 6 core and in each of the checklist

Cheers,
Lynn
