### ISSUE TITLE
mixs6 spreadsheet has a definition field inserted into mixs ID column

### ISSUE THREAD

**Issue by cmungall** [GenomicsStandardsConsortium/mixs#216]
See row 470:

<google-sheets-html-origin><style type="text/css"></style>

hydrocarbon resources-cores |   |   |   | permeability | permeability | Measure of the ability of a hydrocarbon resource to allow fluids to pass through it. (Additional information: https://en.wikipedia.org/wiki/Permeability_(earth_sciences)) | measurement value range | {integer} - {integer} {unit} |   |   | X | mD | 1 | 10 | Measure of the ability of a material (such as a hydrocarbon resource or a membrane) to allow fluids to pass through it. Additional information: https://en.wikipedia.org/wiki/Permeability_(earth_sciences) |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/50745/127060451-8a8060d5-35ce-4b40-b278-c22ce220f705.png)

@wdduncan and I noticed this when trying to build linkml yaml from the latest spreadsheet

**Comment by only1chunts** [comment]
looks like a copy/paste mistake by someone (probably me as I've been doing lots on those sheets! sorry)
I've fixed it now, the actual value should be MIXS:0000404
Thanks for pointing it out.
