### ISSUE TITLE
Ag package term suggestion insect_collect_prot MIXS:0001292

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#219]
**New term details**
```
Term name - insect sample collection protocol
Term ID - MIXS:0001292
Structured comment name - insect_collect_prot
Definition - Describes the procedure whereby insect samples for an experiment are sourced.
Expected value - free text
Value syntax - {text}
Example - traps, sweep nets, manual
Package(s) - Agriculture
```

**Additional context**
Term suggested as part of Ag package

## Points for discussion
how is this different to sample collection method?

**Comment by ramonawalls** [comment]
Suggest that they reuse existing terms for sample collection method (MIXS:0001225) and sample collection device (MIXS:0000002).

Will know that the sample is insect based on the sample type description. Provide package-specific guidance for their community.

**Comment by only1chunts** [comment]
Agreed there is no need for new term MIXS:0001292.
I have removed this term from the  [MIxS v6 Term Updates](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) NewAg sheet.
