### ISSUE TITLE
Ag package term suggestion insect_sample MIXS:0001293

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#220]
**New term details**
```
Term name - type of pests, vectors or pollinator collected
Term ID - MIXS:0001293
Structured comment name - insect_sample
Definition - Sample description (genus, species, biotype)
Expected value - free text
Value syntax - {text}
Example - Myzus persicae
Package(s) - Agriculture
```

**Additional context**
Term suggested as part of Ag package

## Points for discussion
Currently this definition seems to be the same as that of species_name of the sample OR host_species, so either we dont need this term or the definition needs to be explicit as to what it is actually asking for.
Could this be covered by one of the terms created for the Symbionts package?

**Comment by ramonawalls** [comment]
We (on the call) agree with @only1chunts that existing terms should be reused. Need to provide guidance to ag group on how to use them.

**Comment by only1chunts** [comment]
Term not added as all details can already be captured in MIXS:0001309 and other terms in the symbiont associated package
I have removed this term from the  [MIxS v6 Term Updates](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) NewAg sheet.
