### ISSUE TITLE
Ag package term suggestion env_ag_biome

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#221]
**New term details**
```
Term name - environment agricultural (biome)
Term ID - MIXS:0001294
Structured comment name - env_ag_biome
Definition - Biomes are defined based on factors such as plant structures, leaf types, plant spacing, and other factors like climate. Biome should be treated as the descriptor of the broad ecological context of a sample. Examples include: agricultural fields, urban, natural, control environments (laboratory or greenhouses), postharvest, other
Expected value - free text
Value syntax - {text}
Example - Desert
Package(s) - Agriculture
```

**Additional context**
Term suggested as part of the Ag package

## Points for discussion
How does this fit in with our ENVO triple terms for environment?

**Comment by ramonawalls** [comment]
This does not need to be a special term for biomes. If they have a very specific biome classification, should request in ENVO. 

Just use the normal environmental triplet description.

Keep notes on usage in their documentation.

**Comment by only1chunts** [comment]
Term not added as all details can already be captured in the 3 ENVO fields; MIXS:0000012, MIXS:0000013, MIXS:0000014
I have removed this term from the  [MIxS v6 Term Updates](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=2063807055) NewAg sheet.
