### ISSUE TITLE
Ag package term suggestion ag_sample_type MIXS:0001295

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#222]
**New term details**
```
Term name - agricultural sample type collected
Term ID - MIXS:0001295
Structured comment name - ag_sample_type
Definition - Sample was collected from aboveground plant parts, soil or root-associated
Expected value - free text
Value syntax - {text}
Example - Leaf
Package(s) - Agriculture
```

**Additional context**
Suggested as part of the Ag package

## Points to discuss
isn't this already covered by the env terms?

**Comment by pyilmaz** [comment]
I'd say three terms would cover this field, depending on the sample collected:
Plant-associated package > plant product:Substance produced by the plant, where the sample was obtained from
Plant-associated package > plant structure:  Name of plant structure the sample was obtained from; for Plant Ontology (PO) (v releases/2017-12-14) terms, see http://purl.bioontology.org/ontology/PO, e.g. petiole epidermis (PO_0000051). If an individual flower is sampled, the sex of it can be recorded here.
MIxS-core > environmental medium (if soil, mud etc...)

**Comment by only1chunts** [comment]
CIG discussion - agree that this term is not required as its covered by the use of the three environmental terms in the core.

**Comment by ramonawalls** [comment]
In addition to the core environment terms, there are also terms in the Plant Package (not plant associated) that can be used to describe the sample itself.

**Comment by only1chunts** [comment]
I have removed the suggested term "ag_sample_type" from the Ag package, no need for any mention in the changes log as its a new term that has not been created.
