### ISSUE TITLE
Ag package term suggestion strain NEW

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#227]
**New term details**
```
Term name - organism strain
Term ID - 
Structured comment name - strain
Definition - A strain is a genetic variant or kind of microorganism
Expected value - microbial or eukaryotic strain name
Value syntax - 
Example - 
Package(s) - Agriculture
```

**Additional context**
Suggested as part of the Ag package

## Points for discussion
why not use the existing term "host_subspecf_genlin" MIXS:0001318

**Comment by pyilmaz** [comment]
Does this term refer to the organism being sequenced? Also suggest change expected value to bacteria, archaea or eukaryotic strain name, since eukaryotic microorganisms is also a thing

**Comment by ramonawalls** [comment]
1. Subspecific genetic lineage is for any lineage that is below what is listed in NCBI taxonomy (i.e. below subspecies). Is "strain" referring to something equivalent to a subspecies or is it referring to sub-subspecies? Either way, the package should reuse one of the existing terms.

2. Is this specific to the organism being sequenced, or could it refer to a microorganism whose microbiome is being sequenced?

**Comment by ramonawalls** [comment]
On call we agreed that the ag package should reuse subspecific genetic lineage for times when the "strain" is below subspecies. If it is at the subspecies level, then NCBI taxon ID should be used.

**Comment by only1chunts** [comment]
The Ag package already includes the term "host_subspecf_genlin" MIXS:0001318 (row 97).
I have deleted the row for "strain" from the Ag package.
