### ISSUE TITLE
Ag package term suggestion spiked_strains NEW

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#228]
**New term details**
```
Term name - spiked strains
Term ID - 
Structured comment name - spiked_strains
Definition - organism name, NCBI accessions, CFUs/gram
Expected value - 
Value syntax - 
Example - 
Package(s) - Agriculture
```

**Additional context**
Suggested as part of the Ag package

## Points for discussion
various "spikein" terms already defined in food package, need to select an appropriate one for use here

**Comment by only1chunts** [comment]
Spikein_strain = MIXS:0001170
definition = Taxonomic information about the spike-in organism(s) at the strain level. This field accepts terms under organism (http://purl.obolibrary.org/obo/NCIT_C14250). This field also accepts identification numbers from NCBI under https://www.ncbi.nlm.nih.gov/taxonomy. Multiple terms can be separated by pipes.

**Comment by ramonawalls** [comment]
Are they asking for the amount of spiking as well (CFUs per gram)?

**Comment by ramonawalls** [comment]
There are a lot of spikes in the food package. Maybe we should move to a general term for spiking (substance, amount, unit), but that is a bigger question.

**Comment by only1chunts** [comment]
use MIXS:0001170

**Comment by only1chunts** [comment]
I have copied over the "spikein_strain" MIXS:0001170 details from the Food package to the Ag package to over-write the "spiked_strains" row in Ag package.
