### ISSUE TITLE
Ag package term suggestion transportation NEW

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#229]
**New term details**
```
Term name - transportation
Term ID -  
Structured comment name - transportation
Definition - A planned process that is the movement of people, animals and goods from one location to another (duration and conditions).
Expected value - 
Value syntax - 
Example - 
Package(s) - Agriculture
```

**Additional context**
Suggested as part of the Ag package

## Points to discuss
Better definition required, rather to vague, what exactly is expected here in relation to the sampling event?

**Comment by ramonawalls** [comment]
We need clarification from the Ag group about what they are trying to capture here. Currently, it is too vague.

**Comment by ymgan** [comment]
Not sure if it is relevant, came across this term in Darwin Core today so I just gonna put it here:


Term: **pathway**

field | property
--|--
Identifier | http://rs.tdwg.org/dwc/terms/pathway
Definition | The process by which an Organism came to be in a given place at a given time.
Comments | Recommended best  practice is to use controlled value strings from the controlled  vocabulary designated for use with this term, listed at http://rs.tdwg.org/dwc/doc/pw/. For details, refer to https://doi.org/10.3897/biss.3.38084
Examples | releasedForUse, otherEscape, transportContaminant, transportStowaway, corridor, unaided

**Comment by only1chunts** [comment]
use MIXS:0001137 and MIXS:0001138

**Comment by only1chunts** [comment]
Incorporated the two Food package terms  MIXS:0001137 and MIXS:0001138 in the Ag package, and removed the row for "transportation".
