### ISSUE TITLE
Ag package term suggestion lib_const_meth NEW

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#231]
**New term details**
```
Term name - library construction method
Term ID - 
Structured comment name - lib_const_meth
Definition - Library construction method used for clone libraries
Expected value - library construction method
Value syntax - {text}
Example - paired-end,single,vector
Package(s) - Agriculture
```

**Additional context**
Suggested as part of the Ag package

## Points to discuss
Is this already covered by lib_layout and/or lib_vector terms in core?

**Comment by pyilmaz** [comment]
IMO it is covered by library_layout

**Comment by only1chunts** [comment]
OK.

**Comment by only1chunts** [comment]
I have removed the "lib_const_meth" term from the Ag package. All "lib" terms are within the core and listed as either mandatory or conditional mandatory depending on the checklist used.
