### ISSUE TITLE
Provide standardize way to map MIxS columns to ontology descriptors

### ISSUE THREAD

**Issue by cmungall** [GenomicsStandardsConsortium/mixs#235]
E.g. tot_org_carb in the soil package should be mapped to http://purl.obolibrary.org/obo/ENVO_09000008

Should this be specified outside, e.g. in SSSOM format, as separate mapping files?

**Comment by ramonawalls** [comment]
All mixs entities (terms, checklists, extensions, combinations) now have unique IRIs. Also, even though the information is not in place yet, LinkML provides a standard way to map MIxS columns (aka terms aka slots) to ontology terms, so this issue is fixed.
