### ISSUE TITLE
Evaluate CEDAR template datamodel for representing MIxS templates

### ISSUE THREAD

**Issue by cmungall** [GenomicsStandardsConsortium/mixs#236]
Note this ticket is not about evaluating CEDAR tooling, but rather the abstract data model and associated JSON-LD / RDF / JSON Schema representation.

High level description here:

https://github.com/metadatacenter/cedar-docs/wiki/CEDAR-Template,-Element,-and-Field-Instances

e.g JSON-LD/RDF for a template with two fields here:

```
{
  "studyID": { "@value": "SDY2"  },
  "pi": { 
    "fullName": { "@value": "Dr. P.I." }, 
    "homePage": { "@id": "https://www.stanford.edu/people/DrPI.html" }, 
    "address": { "@value": "Stanford, CA 94305, USA" },
    "dob": { "@value": "1999-01-01" } 
  }
}
```

Note that fields can be constrained to be value sets from ontologies:

The paper is here:  https://more.metadatacenter.org/sites/default/files/An%20Open%20Repository%20Model%20for%20Acquiring%20Knowledge%20about%20Scientific%20Experiments.pdf

The abstract data model is in fig 1:

![image](https://user-images.githubusercontent.com/50745/81482452-fdd29580-91eb-11ea-8f7b-57b76c29e697.png)

More docs and guides here:

https://github.com/metadatacenter/cedar-docs/wiki/CEDAR-technical-documentation

**Comment by cmungall** [comment]
I vote for closing this - it would be easy to add something generic at the LinkML level

**Comment by ramonawalls** [comment]
We are using LinkML, so closing.
