### ISSUE TITLE
Guidelines for minting new IRIs for terms

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#238]
We need to determine what conditions necessitate creating a new IRI for a mixs term.
This is seen if you at differences between look at the difference between the "value syntax" column for the mixs term "depth".  

In version 4, the value syntax for depth is: {float}   m (I assume this means the unit is meters)
But in version 5, value syntax for depth is:  {float}   {unit}

Does this mean a new IRI should be minted for depth in version 5?

cc @cmungall @ramonawalls @jdeck88 @folker @renzok

**Comment by ramonawalls** [comment]
This issue will only become important when we transition from MIxS6 (first version with IRIs) to MIxS 6.1 or 7.

**Comment by ramonawalls** [comment]
We now have unique IDs for all MIxS terms in place and at least some policies around creating and updating terms. Closing this issue.
