### ISSUE TITLE
Use skos:inScheme

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#239]
use skos:inScheme to say which part of the template it is (environment, sequencing, study, ...)

see: 
- https://www.w3.org/TR/skos-reference/#schemes
- https://www.w3.org/2012/09/odrl/semantic/draft/doco/skos_inScheme.html

definition: Relates a resource (for example a concept) to a concept scheme in which it is included.

cd @cmungall  @ramonawalls

**Comment by ramonawalls** [comment]
This issue has been resolved by the use of LinkML.
