### ISSUE TITLE
IRIs (and URLs) for MIxS terms

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#24]
Older MIxS terms have URLs provided by TDWG, such as https://terms.tdwg.org/wiki/mixs:alt_elev . These pages have links to GSC pages (e.g.,  http://gensc.org/ns/mixs/alt_elev) that don't currently resolve.

We need a more stable and maintainable solution to identifiers for MIxS terms.

One suggestion was to request PURLs via the OBO Foundry. This has a lot of benefits, but there were some concerns because MIxS is not an ontology. See the discussion at OBOFoundry/OBOFoundry.github.io#822.

Another suggestion is that we could host the URLs ourselves, of the form http://gensc.org/ns/mixs/alt_elev.

We can use this space to discuss.

**Comment by folker** [comment]
I think the restructuring of the gsc web site has a bearing on this too. We could choose to maintain the “documents” as JSON and use sphinx to generate a stable web site to point to for stuff like "https://terms.tdwg.org/wiki/mixs:alt_ele"

I personally would prefer this. it bypasses the need for hosting our DB etc.

**Comment by cmungall** [comment]
@folker - I don't know much about the existing gsc website but I embrace the use of modern practices such as keeping metadata in structured form in github (e.g. json-ld or yaml) and deriving a lightweight website using technology like jekyll/mkdocs.

You may also be interested in the w3id.org system which makes it easy to register a URI space.

We are using this in this project: https://biolink.github.io/biolink-model/

Each class in the schema has a w3id.org URI:

https://w3id.org/biolink/vocab/Gene

This redirects to a page that is markdown generated from the schema. We don't run any servers here, everything already hosted.

We also have a paper coming out on the purl.obolibrary.org system https://github.com/OBOFoundry/purl.obolibrary.org

This runs off a tiny amazon instance. Even if you didn't use the obolibrary purls themselves (there was some resistance on the linked ticket), the system itself is generic and anyone can set up.

**Comment by ramonawalls** [comment]
This issue is replaced by GenomicsStandardsConsortium/mixs-rdf#2 and GenomicsStandardsConsortium/mixs-rdf#5
