### ISSUE TITLE
How to represent packages

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#244]
Environmental paramaters are groups under environmental packages (e.g., plant, soil, skin).

NMDC is representing checklists as classes in linkml, not sure how they are storing packages. We need to discuss this more, both how to represent them in linkml and how to interpret them in RDF and OWL.

**Comment by cmungall** [comment]
I propose classes, for packages, checklists, and combos: it's easiest to define overrides on requirements

See https://cmungall.github.io/mixs-source/

(note: we would have a more custom md for mixs)
