### ISSUE TITLE
Keep mappings to GOLD IDs?

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#249]
Older MIxS terms have mappings to GOLD IDs, as seen in https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=567040283 (column AD). We removed these from MIxS 6. Does anyone think they need to be maintained?

@cmungall @lschriml @only1chunts

**Comment by lschriml** [comment]
Let’s check with JGI, if GOLD is still using them, then yes

**Comment by ramonawalls** [comment]
I had an email exchange with Reddy from GOLD, and it is okay to get rid of these mappings.

"Unless this is aimed at helping specific users, I think you can skip this mapping to MIGS ids. Our goal is to have these replaced by corresponding MIXS ids in GOLD. We already have MIXS ids listed for some fields like ENVO triads etc. So I think the MIGS mapping may not be needed anymore. "
