### ISSUE TITLE
New checklists for positive and negative controls

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#25]
Background:
Experimental controls have become very important in microbiome studies (metagenomics, 16S rRNA gene profiling), and in fact each study should include controls (at the minimum one to several DNA extraction controls).
There have been several cases in the microbiome field where researchers report the finding of certain organisms in certain scenarios that eventually turned out to originate from kit reagents/contamination in the lab.
Some journals indicate now specifically in the author guidelines, that the data for DNA extraction controls (and other experimental controls) need to be provided.
See e.g. https://microbiomejournal.biomedcentral.com/submission-guidelines/preparing-your-manuscript/research-article
The above journal specifies “These controls should be sequenced, and the sequence data reported in the paper and made available along with the sample sequence data in a public repository.”

An initial call was held on June 12, 2019 with members of the CIG, including representatives from NCBI and ENA. Three options were discussed:
1. Add terms for controls to all existing checklists
2. Create two new checklists/packages for positive and negative control types
3. Add an attribute for positive control to existing checklists and have a separate checklist for negative controls

ENA prefers option 2. NCBI will need to discuss implementations internally before expressing a preference.

Regardless of which implementation is adopted, new terms will be needed. An initial list was drafted at the call and will be shared as a spreadsheet where people can make suggestions and comments.

**Comment by ramonawalls** [comment]
A draft of the lists is available at https://docs.google.com/spreadsheets/d/1miWEW8fxvTOpFDuq1nV0NkBLgB35Q7nkt4JsHxlEHqw/edit#gid=0. I included some of the key terms from MIxS that seemed relevant.

**Comment by only1chunts** [comment]
May I ask why we need a separate geographic location attribute for control samples? "cont_geo_loc_name" surely the normal "geo_loc_name" is sufficient?

**Comment by ramonawalls** [comment]
@only1chunts I think the reasoning for separate fields was that their may be separate locations for where the negative control is collected and where it is processed. Perhaps @lschriml can say more about this, as I think she works with negative controls.

**Comment by ramonawalls** [comment]
Suggestions from CIG call on 6/24: 

Make technical replicate a separate boolean field

Make a more general label for biological replicate to capture any sort of biological set of interest. Then there may also need to be a set type field and set ID field.

**Comment by lschriml** [comment]
Update terms and add MIXS IDs.

**Comment by lschriml** [comment]
@josieburgin @anjijohnston 
- the positive and negative control checklists are updated, columns aligned, MIxS IDs added.

- Could there be just one checklist, as the only different is the type of control ? 

Cheers,
Lynn

**Comment by josieburgin** [comment]
Hi @lschriml, when implemented in ENA, if it is added as one single checklist we would need to make both the 'positive control type' and 'negative control type' fields as optional which means they would not necessarily be used at all. So for us, it would be preferable to have 2 checklists to ensure users use the correct control type field.

**Comment by lschriml** [comment]
Sounds good.
Have you decided on a name for the checklists ?

**Comment by josieburgin** [comment]
Hi @lschriml we don't have a particular preference over the checklist names. Something like MIxS Positive Control and MIxS Negative Control should work fine.

**Comment by lschriml** [comment]
Sounds good.
Do you anticipate additional changes/edits ?

When the last edits are complete, I will assign MIxS IDs.

Cheers,
Lynn

**Comment by josieburgin** [comment]
Hi @lschriml, I have no further comments.

**Comment by only1chunts** [comment]
sorry for taking so long to get around to looking at this. For the positive control it seems logical to include the taxon ID as there is going to be some sort of DNA included, but for the negative controls there is a good chance there will be no DNA included and therefore no taxon ID.
If the recommendation is to use the NCBI:txid2582415 for "blank sample" then we should include that in the definition?

If we are going to add the term "taxid" for these checklists, it should also be added to the core and recommended for all checklists, but that brings us into this directly related discussion in ticket #128  i.e. are we limiting the ID to NCBI taxonomy only?

**Comment by josieburgin** [comment]
Hi @only1chunts, this may have been added as INSDC need the tax ID. In which case the INSDC guidelines would be 'blank sample' for the negative controls.

Regarding how GSC wants to handle taxonomy - if tax ID is not normally included in the GSC checklists I don't know if it needs to be included here? If you decide it should be included - I agree having details on the appropriate taxon to use in the definition would be good.

**Comment by ramonawalls** [comment]
TODO: Move into final MIxS spreadsheet with a few small changes. Needed changes are in GH issues.

**Comment by only1chunts** [comment]
I just started moving this to v6 spreadsheet and realised that these are not actually "environmental packages", and they dont actually include all the mandatory terms of the MIxS checklists (i.e. there are no ENVO fields) so how are we classing these? Checklists or packages? if packages, how do reconcile the fact they remove some of mandatory fields in whichever checklist they are appended to?

**Comment by only1chunts** [comment]
Infact looking at it, there is actually only ONE term that makes up each of these "packages" the rest of the listed terms are actually Core items. 
Obviously EBI/NCBI can create their own submission packages for these, but I'm wondering if we actually need to define these as packages, instead just add the two new terms "pos_cont_type" and "neg_cont_type" to the core and specify them as conditional mandatory for all checklists?

**Comment by ramonawalls** [comment]
@only1chunts I agree about just adding the new terms and not creating new checklist or packages. HOWEVER, once MIxS as RDF is up an running, it will be easy to create new checklist/packages/profiles, so we can reopen this issue then.

**Comment by only1chunts** [comment]
I have added the two terms (pos_cont_type and neg_cont_type) to the core as conditional mandatory for all checklists.
closing this ticket now. If anyway has any objections or updates please reopen this ticket.
