### ISSUE TITLE
Keep links to issues for terms?

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#250]
In the clean version of MIxS 6, the links to Github issues were removed. Should we add those back in? They seem useful?

@only1chunts @lschriml

**Comment by only1chunts** [comment]
Given the errors Jasper has flagged in the "clean" google sheets version (merged cells) introduced by copy paste, and the fact that we dont actually need a google sheets version as the scripts take TSV format, I think I will delete the clean version google sheet, and upload two TSV files instead.
According to the file https://github.com/GenomicsStandardsConsortium/mixs-source/blob/main/gsctools/mixs_converter.py
on line 470 & 471 
```
    cv.core_filename = f'downloads/mixs6_core.tsv'
    cv.packages_filename = f'downloads/mixs6.tsv'
```
The relevant TSV files are pulled from the "downloads" directory. So I will save a copy of the TSV file there (with a name that includes the date and my initials so there is no confusion over which one I have uploaded.
As for the GitHub tickets with the rows, I think the [changes log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823) is sufficient, as that includes not only the updates but also the deprecated terms that are not present in the clean version.

**Comment by ramonawalls** [comment]
Add those links would require manual curation, which is error prone and hard to keep up to date. I vote for not including them.

**Comment by only1chunts** [comment]
I'm happy to not include them as long as we have some method to be able to trace back how, when and why things get changed (something better than we have had upto this point! i.e. individuals memories)

**Comment by ramonawalls** [comment]
For me, it would be easier to search github issues for the term label or ID. We just need to diligent about recording changes in git issues, which we are definitely getting better at.

**Comment by only1chunts** [comment]
Great that this has been decided, has it been included in the GitHub documentation so that we can reference it when someone forgets (probably me! :-D)  Thanks.

**Comment by ramonawalls** [comment]
How do we know if the term is included in a github issue? 

Expectation: User goes to github issue tracker and types in term and finds relevant issues.

However, terms can be referred to as the short name, long name, or identifier (plus other random words).

We can add to the contributor documentation that you should fill out the issue template, which includes the short name, long name, and identifier. Action item for RLW to add this to the github documentation file for contributors.
