### ISSUE TITLE
Change definition of MIXS:0001139 (food source

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#252]
**Current term details**
Please supply the current details of the term that you would like to update:
```
Term name - food source
Term ID - MIXS:0001139
Structured comment name - food_source
Definition - Individual plant or animal from which the food product or its major ingredient is derived; also a chemical food source [FDA CFSAN 1995].
Expected value - FOODON
Value syntax - {termLabel} {[termID]}
Example - giant tiger prawn [FOODON:03412612]
Preferred unit - 
Package(s) - Food
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):
```
Term name - food source
Term ID - MIXS:0001139
Structured comment name - food_source
Definition - Type of plant or animal from which the food product or its major ingredient is derived or a chemical food source [FDA CFSAN 1995].
Expected value - FOODON term
Value syntax - {termLabel} {[termID]}
Example - giant tiger prawn [FOODON:03412612]
Preferred unit - 
Package(s) - Food
```

**Additional context**
The change here is to change the definition text. Currently it asks for an individual plant or animal, but I think the intention is for the type of plant or animal or chemical.

**Comment by only1chunts** [comment]
this term has only been introduced in v6 (see #201) and the change was agreed in the CIG call 27Sept.
I have made the change directly to the definition in the Food packages as proposed here. No need to log in the change log.
