### ISSUE TITLE
Urobiome package term suggestion race

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#263]
**New term details**
```
Term name - race
Structured comment name - race
Definition - Race of the host. e.g. Alaska Native, American Indian, Asian, Black or African American, Native Hawaiian or Other Pacific Islander, White, See https://www.census.gov/topics/population/race/about.html
Expected value -  free text
Value syntax - {text}
Example - caucasian
Preferred unit - 
Package - Urobiome
```

**Additional context**
Suggested as part of the Urobiome package.

see also previous discussions on ethnicity & race #59

**Comment by lakarstens** [comment]
We would like to retract race as a suggested term, we included it only because it was in a prior version of mixs

**Comment by ramonawalls** [comment]
mixs:895 is the current term for ethnicity, which works for the urbiome package. For further discussion see issue #59. The definitions should be improved, and it should refer to an ontology for values.
