### ISSUE TITLE
MIxS 5 ETA?

### ISSUE THREAD

**Issue by pbuttigieg** [GenomicsStandardsConsortium/mixs#27]
Cross-link to #18 and https://github.com/EnvironmentOntology/envo/issues/805 https://github.com/EnvironmentOntology/envo/issues/804 https://github.com/EnvironmentOntology/envo/issues/803 https://github.com/EnvironmentOntology/envo/issues/802 https://github.com/EnvironmentOntology/envo/issues/807

Over at ENVO, we are getting more requests on how to annotate in a MIxS compliant way. As MIxS 5 will change things quite a bit, we'd like to know when to expect its release so we can inform our users.

Do we have a planned release date for MIxS 5?

**Comment by ramonawalls** [comment]
I hope we will finalize it on the next CIG call, on June 24. I'll post results here.

**Comment by only1chunts** [comment]
Please can you send the final version around the mailing list so that we can have a final check.

**Comment by pbuttigieg** [comment]
Or put it in a pre-release directory in this repo?

**Comment by pbuttigieg** [comment]
HI all, we're going to start releasing new ENVO guidance, we can't wait any longer as other microbiome initiatives need it. 

Please can we have **at least** the pre-release version exposed? 

I strongly recommend open and transparent development in a pre-release directory in future.
