### ISSUE TITLE
Food package update to term env_samp_device

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#294]
**Additional context**
FDA and OHE alignment work suggested "env_samp_device" be changed to "sampling_device"

**Comment by only1chunts** [comment]
"env_samp_device" is not a term we included in the final version, and I cant seem to find the relevant MIXS ID that it refers to, so I'm not sure this term is even meant to be included. We probably discussed it and suggested the general term "samp_collec_device" MIXS:0000002 from the core was to be used instead. In which case its a no, we cannot change the name.

**Comment by lschriml** [comment]
'environmental sampling device' -- to deal with swabs 
   -- check food pack for this term. 
 --- 'sampling device'  --> needed for food facility
         -- as a foodon term

--> followup with Chris Grim.

**Comment by ramonawalls** [comment]
samp_collect_device (MIXS:0000002) is already included in the food-farm environment and food-human food packages.

It is in food-farm twice -- need to remove one row.

**Comment by only1chunts** [comment]
removed duplicate row from [v6 spreadsheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809) - "MIXS6 packages Final_clean"
