### ISSUE TITLE
Food package update term "animal_am" MIXS:0001243

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#295]
**Current term details**
```
Term name - food animal antimicrobial
Term ID - MIXS:0001243
Structured comment name - animal_am
Definition - The drug class(es) or name(s) (generic or brand) of the antimicrobial(s) given to the food animal within the last 30 days.
Expected value - text
Value syntax - {text}
Example - tetracycline
Preferred unit - 
Package(s) - food-animal and animal feed, 
```

**Suggested update(s)**
```
Term name - host antimicrobial name
Term ID - MIXS:0001243
Structured comment name - host_am
Definition - The drug class(es) or name(s) (generic or brand) of the antimicrobial(s) given to the food animal within the last 30 days.
Expected value - Controlled Vocabulary
Value syntax - 
Example - tetracycline
Preferred unit - 
Package(s) - food-animal and animal feed, 
```

**Additional context**
FDA and OHE alignment work suggested this change.

**Comment by only1chunts** [comment]
"animal_am" MIXS:0001243 - changing this to host_am makes sense to me, but it does raise other questions - like what do we do with the other related terms:
"animal_am_dur" food animal antimicrobial duration MIXS:0001244
"animal_am_freq" food animal antimicrobial frequency MIXS:0001245
"animal_am_route" food animal antimicrobial route of administration MIXS:0001246
"animal_am_use" food animal antimicrobial intended use MIXS:0001247

another issue is **Expected Value = Controlled Vocabulary**. We need the CV terms to be included.

NB- for future discussion, we should look at the overlap of the above terms with the already existing "antibiotic regimen" MIXS:0000553

**Comment by lschriml** [comment]
Keep as is.

**Comment by lschriml** [comment]
term name: food animal antimicrobial
definition: remove 'drug'
update to:
The name(s) (generic or brand) of the antimicrobial(s) given to the food animal within the last 30 days.

**Comment by lschriml** [comment]
- check other packages for any overlap for 'antimicrobial'

**Comment by ramonawalls** [comment]
Remove word drug from definition. Keep name as food animal.

**Comment by only1chunts** [comment]
Updated definition within the [v6 spreadsheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809) "MIxS6 packages- Final_clean" tab.
Nothing added to change log as the term is new anyway and covered by ticket #201
