### ISSUE TITLE
Food package update to term food_prod_char MIXS:0001136

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#298]
**Current term details**
```
Term name - food production characteristics
Term ID - MIXS:0001136
Structured comment name - food_prod_char
Definition - Descriptors of the food production system such as wild caught, free-range, organic, free-range, industrial, dairy, beef.
Expected value - text
Value syntax - {text}
Example - wild caught
Preferred unit - 
Package(s) - food-food production facility ; food-farm environment
```

**Suggested update(s)**
```
** Term name - labeling claims
Term ID - MIXS:0001136
** Structured comment name - label_claims 
** Definition - Labeling claims containing descriptors such as wild caught, free-range, organic, free-range, industrial, hormone-free, antibiotic free, cage free. Can include more than one term, separated by ";"
Expected value - text
Value syntax - {text}
Example - wild caught
Preferred unit - 
Package(s) - food-food production facility ; food-farm environment
```

**Additional context**
FDA and OHE alignment work suggested this change.

**Comment by only1chunts** [comment]
The new suggestion of "labeling claims" doesn't seem to fit with the expected values? it is ambiguous and overlaps with the terms: 
"dietary claim or use" MIXS:0001199 
and 
"food allergen labeling" MIXS:0001201
both of which also include labeling claims. 
**I suggest we do not update the term food_prod_char.**

**Comment by lschriml** [comment]
Want to keep both terms. 
label on the product
other:
production environment.


term name update to: product labeling claims

Approved by group.

**Comment by lschriml** [comment]
keep:
Term name - food production characteristics
Term ID - MIXS:0001136

update: 
** Term name - labeling claims
Term ID - MIXS:0001136

to:
term name update to: product labeling claims

**Comment by ramonawalls** [comment]
It seems like there will be three terms to describe the same thing. We can add this, but we may want to merge them in a future version of mixs.

**Comment by ramonawalls** [comment]
** Term name - production labeling claims
Term ID - MIXS:0001136
** Structured comment name - prod_label_claims 
** Definition - Labeling claims containing descriptors such as wild caught, free-range, organic, free-range, industrial, hormone-free, antibiotic free, cage free. Can include more than one term, separated by ";"
Expected value - text
Value syntax - {text}
Example - wild caught
Preferred unit - 
Package(s) - food-food production facility ; food-farm environment

**Comment by only1chunts** [comment]
"prod_label_claims" given mixs ID-  MIXS:0001337
Added to 2 food packages in [v6 spreadsheet](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809) and included in the [Change Log](https://docs.google.com/spreadsheets/d/1G5ri-vUERgy3zfzj_MQsZEff0K8mT1LT/edit#gid=1075103823).
