### ISSUE TITLE
Food package update to term soil_rel_location MIXS:0001161

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#299]
**Current term details**
```
Term name - soil relative location
Term ID - MIXS:0001161
Structured comment name - soil_rel_location
Definition - Location of sampled soil to other parts of the farm e.g. under crop plant, near irrigation ditch, from the dirt road
Expected value - text
Value syntax -
Example -
Preferred unit - 
Package(s) - food-farm environment ; agriculture
```

**Suggested update(s)**
```
** Term name - relative location of sample
Term ID - MIXS:0001161
** Structured comment name - rel_location
Definition - Location of sampled soil to other parts of the farm e.g. under crop plant, near irrigation ditch, from the dirt road
Expected value - text
Value syntax -
** Example - furrow
Preferred unit - 
Package(s) - food-farm environment ; agriculture
```

**Additional context**
FDA and OHE alignment work suggested this change.

**Comment by only1chunts** [comment]
I'm not sure about this one, firstly how is this term different from "adjacent_environment" MIXS:0001121, defined as "Description of the environmental system or features that are adjacent to the sampling site. This field accepts terms under ecosystem (http://purl.obolibrary.org/obo/ENVO_01001110) and human construction (http://purl.obolibrary.org/obo/ENVO_00000070). Multiple terms can be separated by pipes."

**Comment by lschriml** [comment]
Discussed, term will be used for multiple sampling systems, hydroponic, soil, etc. 
Term has been broadened from soil. 
Approved.

**Comment by lschriml** [comment]
use:
** Term name - relative location of sample
Term ID - MIXS:0001161
** Structured comment name - rel_location
Definition - Location of sampled soil to other parts of the farm e.g. under crop plant, near irrigation ditch, from the dirt road
Expected value - text
Value syntax -
** Example - furrow
Preferred unit - 
Package(s) - food-farm environment ; agriculture

**Comment by ramonawalls** [comment]
IMO, this term is redundant with Environmental Feature, and it supplies free text rather than an ontology term, so it is less valuable, but we can keep it for now. We may want to revisit this in the future.

Use Chris's suggested update.

**Comment by only1chunts** [comment]
Included in V6 spreadsheet as suggested above, but I agree with Ramona that we should revisit this in future with a view to merging it into env_feature and/or adjacent_environment.
