### ISSUE TITLE
air package alt_elev vs alt

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#302]
**Describe the bug**
Not sure this really qualifies as a bug. But, looking at the "air" template, but altitude and elevation are requested in 2 spots... alt, elev, and alt_elev. Unclear where this information should actually go

**Comment by turbomam** [comment]
Discussing now! What file or sheet did you see these in?

**Comment by only1chunts** [comment]
Thank you @mslarae13 for contacting us, this is the correct forum for such questions.
From your description we're not quite sure exactly where you have seen the "alt_elev" field as that has not been a part of the v5 standard, and it will not be in v6 to be released soon. My guess would be that its a legacy term from an older version of MIxS.
For now you can see the current (v5) and the soon to be released (v6) checklists and packages here:
https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=276512563

You may already be aware, but just in case not, we are moving towards a LinkML system for MIxS in the future, which we hope will make it easier for people to maintain standards with the current version as well as make it easier to search and find details of individual terms! Fingers crossed that happens soon and makes everyone's life that little bit easier.

I will close this ticket now, but if you have any further questions about the alt_elev term please feel free to re-open it.
Thanks.

**Comment by mslarae13** [comment]
@only1chunts 

I just noticed the same thing for depth in the soil package. Also downloaded from the mixs5 master.

it's listed as depth, geographic location (depth) and depth, depth (structure comment name, item)

**Comment by only1chunts** [comment]
I think we already identified and dealt with the Depth issue, please take a look at #63 to check its the same thing as you're seeing now?

The alt_evel issues appears to be a problem with the individual package spreadsheet for air* (I've not checked the other individual packages yet), as the [mixs_v5.xlsx](https://github.com/GenomicsStandardsConsortium/mixs-legacy/blob/master/mixs5/mixs_v5.xlsx) spreadsheet is correct. i.e. altitude and elevation are two separate terms.
The individual package spreadsheet are supposed to be created from the 1 master, but it looks like a mistake was made here, sorry about that! 
Moving forward the source of trust will be a single LinkML file which will be used to auto-generate all individual package spreadsheets, so this sort of mistake should not happen in the future.
Thank you for bringing these things to our attention.
