### ISSUE TITLE
organic matter

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#313]
**Current term details**
Please supply the current details of the term that you would like to update:
```
Term name - organic matter
Term ID -  org_matter
Structured comment name - 
Definition - 
Expected value - 
Value syntax -
Example -
Preferred unit - 
Package(s) - sediment
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):
```
Term name - 
Structured comment name - 
Definition - 
Expected value - 
Value syntax -
Example -
Preferred unit - 
Package(s) - soil
```

**Additional context**
organic matter  is relevant for the soil package

**Comment by ramonawalls** [comment]
Todo: add to soil package then close this issue.

**Comment by ramonawalls** [comment]
done
