### ISSUE TITLE
Add temperature of sample to soil package

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#322]
**Current term details**
Please supply the current details of the term that you would like to update:
```
Term name - temperature
Term ID - temp
Structured comment name - 
Definition - Temperature of the sample at the time of sampling
Expected value - 
Value syntax -
Example -
Preferred unit - 
Package(s) - sediment
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):
```
Term name - 
Structured comment name - 
Definition - 
Expected value - 
Value syntax -
Example -
Preferred unit - 
Package(s) - soil
```

**Additional context**
Add any other context about the update request here, e.g. why you think this needs to be updated.

Some experiments will measure the temperature of the soil at the time of sampling. I think the term in the sediment package fits this need.

**Comment by ramonawalls** [comment]
Todo: add to soil package then close this issue.

**Comment by ramonawalls** [comment]
Done.

**Comment by turbomam** [comment]
Does this mean that there's new content in the Google Sheets, which should be run through the LinkML converter again? (Not that there's anything wrong with that)

**Comment by ramonawalls** [comment]
> Does this mean that there's new content in the Google Sheets, which should be run through the LinkML converter again? (Not that there's anything wrong with that)

Yes, but wait! I have a few more changes to make yet. I want to try to run the converter myself, but it might be challenging due to issue #345
