### ISSUE TITLE
horizon method to "soil horizon method"

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#326]
**Current term details**
Please supply the current details of the term that you would like to update:
```
Term name - horizon method
Definition - Reference or method used in determining the horizon
Package(s) - soil
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):
```
Term name - "soil horizon method"
```

**Additional context**
Add any other context about the update request here, e.g. why you think this needs to be updated.

I think the terms are both fine. Just suggest updating the "method" term to match

https://github.com/GenomicsStandardsConsortium/mixs/issues/232
Relates to ^

**Comment by ramonawalls** [comment]
Agree, and this is an easy fix.

**Comment by ramonawalls** [comment]
Todo: Change label and close this issue.

**Comment by ramonawalls** [comment]
I changed the label but left the structured comment name as is.

**Comment by ramonawalls** [comment]
@only1chunts, did you add it to your doc, or to the changelog on Github?

**Comment by only1chunts** [comment]
On the Google spreadsheet doc.
