### ISSUE TITLE
Clarify sections in core

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#327]
There is confusion about what belongs in the nucleic acid section of core. We should check all the sections and make sure they are clear.

See also #307 #308 #312

**Comment by ramonawalls** [comment]
Sections and Core are now gone

**Comment by only1chunts** [comment]
I think the sections should remain and be used more robustly, but there are other tickets that advocate the cleanup of sections (e.g. #139) so its fine to close this ticket.
