### ISSUE TITLE
Broken link for MIGS/MIMS at https://gensc.org/mixs/

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#331]
The link http://wiki.gensc.org/index.php?title=MIGS/MIMS

from 
> The entire checklist for all sequence types can be downloaded above, but please note that if you only need the spreadsheet for a survey of marker genes, or for a metagenome sequence, reduced spreadsheets are available via relevant project pages of [MIGS/MIMS](http://wiki.gensc.org/index.php?title=MIGS/MIMS) and [MIMARKS](http://wiki.gensc.org/index.php?title=MIMARKS).

on https://gensc.org/mixs/

is broken

**Comment by ramonawalls** [comment]
@only1chunts Can you see if this has been fixed, and if so, close this issue?

**Comment by only1chunts** [comment]
Yes the current website no longer points to any of the old wiki.gensc pages which dont work. (there are other broken links I need to find and fix, but not these ones!)
Closing issue.
