### ISSUE TITLE
legacy publishing expectations

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#335]
In what ways can we use tags to organize old versions?

what do established users expect?

legacy versions as folders in main branch of current repo?

**Comment by ramonawalls** [comment]
Per our discussion on 2/14, we will move any version before MIxS 6 to the mixs_legacy repo (so move 4 and 5). 

Todo:
 - [ ] move files to legacy repo
 - [ ] update links on website
 - [ ] announce change in release email and release notes

**Comment by ramonawalls** [comment]
done
