### ISSUE TITLE
OWL generation urlencode https://w3id.org/mixs/vocab/AddRecovMethodEnum#other;{timestamp}

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#345]
Exception: "https://w3id.org/mixs/vocab/AddRecovMethodEnum#other;{timestamp}" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?

**Comment by ramonawalls** [comment]
@turbomam Do you think it would work if I separated that column into two values, so that it would read something like:

permissible values: {red};{blue};{green} 
permissible values: {timestamp}

So basically, permissible values would have a cardinality of 2 (one enum list and one other).

Is that allowed in linkml?

**Comment by cmungall** [comment]
For context, is this the row?

<google-sheets-html-origin><style type="text/css"></style>

hydrocarbon resources-fluids/swabs | add_recov_method | secondary and tertiary recovery methods and start date | Additional (i.e. Secondary, tertiary, etc.) recovery methods deployed for increase of hydrocarbon recovery from resource and start date for each one of them. If "other" is specified, please propose entry in "additional info" field | enumeration;timestamp | [Water Injection\|Dump Flood\|Gas Injection\|Wag Immiscible Injection\|Polymer Addition\|Surfactant Addition\|Not Applicable\|other];{timestamp} | Polymer Addition;2018-06-21T14:30Z |   | M |   | 1 | MIXS:0001009 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




@turbomam - if we get strange errors in the generation then let's make a linkml issue for it, we want to give informative errors, even if ultimately there is something that needs fixed downstream in the schema

@ramonawalls - I think the cleanest solutions are:

1. split into two slots/terms
2. model as a single-valued string with some custom syntax/regex

I'm guessing 1 may have to wait for future versions if mixs 6 is fixed

2 is pretty much what is implicit right now. It's maybe a little unsatisfactory as it's not as transparently an enum, but the solution basically works.

how I might model this in the future: make class that represents the complex object (here a tuple). This is similar to how we model things like lat-long and measurements and ranges in NMDC. This would require working out a few things - would the jsonschema require a nested object here or would we allow either a string or an object. I would keep it simple for this release - make sense?

**Comment by ramonawalls** [comment]
I also prefer to split this in to two terms, but I wonder if we should use solution 2 for the short term. Would we be able to customize our instance of linkml in the next day or two for solution 2?

**Comment by ramonawalls** [comment]
- {termLabel} {[termID]};{timestamp} is the value syntax for one term 
- {termLabel} {[termID]}; {timestamp} is the value syntax for 14 terms
- {termLabel}; {timestamp} is the value syntax for one term

I changed all of the above to `{termLabel} {[termID]};{timestamp}` so there are now 16 terms with that format. They are all uses of chemical administration (MIXS:0000751).

- {text};{timestamp}: 3 terms, all uses of land use name;date (MIXS:0000315)
- {text};{text};{timestamp}: 2 terms - chemical treatment and biocide
- {boolean};{timestamp}: 3 terms, 2 uses of gravidity (MIXS:0000875) and one of host of the symbiotic host gravidity (MIXS:0001333)
- {text};{float} {unit};{timestamp} 1 term for agrochem_addition (MIXS:0000639)

That leaves add_recov_method (MIXS:0001009) with a custom enum list in the value syntax.

So... it seems like add_recov_methods is the only term with the blocking error (the rest are not enums).

**Comment by ramonawalls** [comment]
I think the easiest thing is for me to edit the YAML file manually to fix this, since I need to get the release out before my presentation on Thursday/ A hard deadline. Going forward, I agree with @cmungall that we should have complex fields in MIxS. That would allow us to know which timestamp when with which value, and similar cases.

**Comment by turbomam** [comment]
> I changed all of the above to `{termLabel} {[termID]};{timestamp}` so there are now 16 terms with that format. They are all uses of chemical administration (MIXS:0000751).

> That leaves add_recov_method (MIXS:0001009) with a custom enum list in the value syntax.

> So... it seems like add_recov_methods is the only term with the blocking error (the rest are not enums).

That's great. Do you want to chat at any point today?

It sounds like you some changes to the Google Sheet and are planning on making some to the LinkML file. If you tell me which you want to consider authoritative, I can make sure the two are n sync with one another.

**Comment by turbomam** [comment]
There are still several LinkML permissible values containing a semicolon, indicative of a MIxS expected value in the pattern `[a|b|c];something else`


```python
from linkml_runtime.utils.schemaview import SchemaView
mixs_file = "model/schema/mixs.yaml"
mixs_view = SchemaView(mixs_file)
mixs_enums = mixs_view.all_enums()

for ek, ev in mixs_enums.items():
    pvs = ev.permissible_values
    for pvk, pvv in pvs.items():
        if ';' in pvk:
            print(f"{ek}\t{pvk}")
```

> compl_score_enum    low;{percentage}
contam_screen_param_enum    combination;{text
floor_finish_mat_enum    none;specify unfinished
pres_animal_insect_enum    other;{integer}
add_recov_method_enum    other;{timestamp}
food_quality_date_enum    use by; date

**Comment by turbomam** [comment]
## Proposed solution for  `add_recov_method_enum`

_Is there some way to convert between the cases used by the different kinds of artifacts? Like `AddRecovMethodEnum` in OWL and `add_recov_method_enum` in YAML?_

- Eliminate or clean up the enum
- set the slot's range to `string`
- set the pattern as below

`^(Water Injection|Dump Flood|Gas Injection|Wag Immiscible Injection|Polymer Addition|Surfactant Addition|Not Applicable|other)$`

**plus** a "timestamp"

https://stackoverflow.com/a/14322189

`^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$`

**therefore**

`^(Water Injection|Dump Flood|Gas Injection|Wag Immiscible Injection|Polymer Addition|Surfactant Addition|Not Applicable|other);([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$`

**Comment by turbomam** [comment]
## More OWL serialization failure patterns

> Exception: "https://w3id.org/mixs/vocab/CurLandUseEnum#rainforest+(evergreen+forest+receiving+>406+cm+annual+rainfall)" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?

_Some might argue that these parenthetical portions should be separated from the permissible value names_

**Comment by turbomam** [comment]
Exception: "https://w3id.org/mixs/vocab/SampPurposeEnum#research+and+development+or+{text}" does not look like a valid URI, I cannot serialize this as N3/Turtle. Perhaps you wanted to urlencode it?

**Comment by turbomam** [comment]
## compl_score_enum

compl_score | completeness score | Completeness score is typically based on either the fraction of markers found as compared to a database or the percent of a genome found as compared to a closely related reference genome. High Quality Draft: >90%, Medium Quality Draft: >50%, and Low Quality Draft: < 50% should have the indicated completeness scores | quality;percent completeness | [high\|med\|low];{percentage} | med;60% ...

Which is this supposed to be ?
- ; (percentage is mandatory)
- | (percentage is an alternative to the enumerated values?)

**Comment by turbomam** [comment]
## floor_finish_mat

built environment | floor_finish_mat | floor finish material | The floor covering type; the finished surface that is walked on | enumeration | [tile\|wood strip or parquet\|carpet\|rug\|laminate wood\|lineoleum\|vinyl composition tile\|sheet vinyl\|stone\|bamboo\|cork\|terrazo\|concrete\|none;specify unfinished\|sealed\|clear finish\|paint]

**Comment by turbomam** [comment]
## pres_animal_insect

agriculture | pres_animal_insect | presence of pets, animals, or insects | The type and number of animals or insects present in the sampling space. | enumeration;count | [cat\|dog\|rodent\|snake\|other];{integer} ...

**Comment by turbomam** [comment]
## food_quality_date

field | value
-- | --
Environmental package | food-farm environment
Structured   comment name | food_quality_date
Package   item | food   quality date
Definition | The   date recommended for the use of the product while at peak quality, this date   is not a reflection of safety unless used on infant formula this date is not   a reflection of safety and is typically labeled on a food product as   "best if used by," best by," "use by," or   "freeze by."
Expected   value | enumeration,   date
Value   syntax | [best   by\|best if used by\|freeze by\|\|use by]; date
Example | best   by 2020-05-24
Section |  
Requirement | X
Preferred   unit |  
Occurrence | 1
MIXS   ID | MIXS:0001178
github   ticket |

**Comment by turbomam** [comment]
Thorough fix is done already!

**Comment by ramonawalls** [comment]
I created issue #379 to create complex objects, so I can close this issue.
