### ISSUE TITLE
Is there any documentation for the intended use of new directory "packages_work_dir"

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#348]

**Comment by ramonawalls** [comment]
@turbomam See my proposed solution on issue #332. With the new release, those files will be part of the official release, so we can update links on our website. Going forward, in progress files will be stored on a branch.

**Comment by ramonawalls** [comment]
Files were removed with commit [42347a4](https://github.com/GenomicsStandardsConsortium/mixs/commit/42347a4b6551266fcdf314727cda5380f3079afd)
