### ISSUE TITLE
Add empty logs folder to repo root

### ISSUE THREAD

**Issue by sujaypatil96** [GenomicsStandardsConsortium/mixs#351]
Running `make all` doesn't go through completely. The make process halts at this step:

```
model/schema/mixs.yaml: downloads/mixs6.tsv downloads/mixs6_core.tsv
	$(RUN) python -m gsctools.mixs_converter  2>&1 | tee -a logs/sheet2linkml.log
```

The reason for that is because is there's no pre created logs folder with a `.keep` or `placeholder` file in the repo root. The workaround is to create an empty logs folder on your local machine.

CC: @turbomam

**Comment by ramonawalls** [comment]
@sujaypatil96 Is this still relevant or can you close it?

**Comment by sujaypatil96** [comment]
This issue can be closed now that we have different targets/processes in place after the transition to mixs v6.2.
