### ISSUE TITLE
gen-excel not finishing in an hour

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#360]
I added a `gen-excel` step to the makefile, in order to work around a known bug in `gen-project`'s excel generation

However, `gen-excel` did not complete after an hour. 

Remember how many environment * checklist classes there are!

Also:
> UserWarning: Title is more than 31 characters. Some applications may not be able to read the file

see also #359

**Comment by ramonawalls** [comment]
Per issue #359 , we can leave excel out of this release.

**Comment by sujaypatil96** [comment]
Fixed by PR #733
