### ISSUE TITLE
"github ticket" column contains non-GH ticket notes

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#366]
[Link to column as a whole](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809&range=M:M)

[Link to one example](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809&range=M1613)

We should parse these and make them a list (Although aren't they being implemented as annotations? See alsos might be better.)

**Comment by ramonawalls** [comment]
See #250 . If we close that issue, we can close this one.

**Comment by ramonawalls** [comment]
The concern was that the github ticket column contained links to not github tickets. Now that we are no longer using that we no longer are going to include links to gh issues with each slot, this issue is obsolete.
