### ISSUE TITLE
Create policy and practices for deprecating terms

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#383]
This came up at the Board meeting. How will we handle retirement of existing terms. Probably similar to ontologies for obsolete terms. Need a way to redirect to replacement term. Sometimes replacement will come from outside GSC.

**Comment by mslarae13** [comment]
Duplicated by https://github.com/GenomicsStandardsConsortium/mixs/issues/804 

& I think resolved by https://github.com/GenomicsStandardsConsortium/mixs/pull/805

Can we close?
