### ISSUE TITLE
Lack of block style indicators in terms.yaml

### ISSUE THREAD

**Issue by raissameyer** [GenomicsStandardsConsortium/mixs#385]
During the GSC22 session on MIOP*, we're working on a [YAML file](https://github.com/pbuttigieg/miop/blob/main/model/schema/terms.yaml) for MIOP terms based on the MIxS v6 [terms.yaml](https://github.com/GenomicsStandardsConsortium/mixs/blob/main/model/schema/terms.yaml) file. 

We noticed that you have no block style indicators in your MIxS v6 YAML file. Could this be an issue?

*MIOP: Minimal Information about an Omic Protocol

**Comment by cmungall** [comment]
Hi @raissameyer thanks for the interest!

The structural content of the YAML of the same regardless of which block style indicator is used, it's a matter of human aesthetic preference

You can play with different styles here:

https://yaml-multiline.info/

If you prefer a particular style we can look at normalizing to that

Before you go much further, how familiar are you with the framework that is being used here (linkml)? What I would not advocate doing is some kind of copy and tweak - instead I would treat this the same way you are familiar with doing things in OWL, import and reuse.

**Comment by ramonawalls** [comment]
Sounds like it is okay to me.
