### ISSUE TITLE
I think we lost column position/rank

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#386]
Terms in Chris Mungall's  mixs_source repo had `Position` comments. I think that reflected the ordering in the MIxS 6 Google Sheet. I might have eliminated that in my transition from comments to annotations. Should we add it back in?

See https://cmungall.github.io/mixs-source/size_frac/

**Comment by turbomam** [comment]
Would probably be best to use the new `rank` alot.

**Comment by ramonawalls** [comment]
We have a new rank slot. It may need work, but we don't need to worry about losing the information from the google sheet.
