### ISSUE TITLE
Resolve duplicate terms in checklists

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#39]
Many of the mixs checklists contain the same term. Sometimes those terms mean the same thing in different checklists, sometimes they don't. @wdduncan has compiled a list of where terms are duplicated at https://github.com/GenomicsStandardsConsortium/mixs-rdf/blob/master/notebooks/output/multi-package-mixs-terms-only.xlsx. 

I am going to make a series of issues to discuss and resolve these duplications. Each issue will reference this one, so we can organize them.

**Comment by ramonawalls** [comment]
@jzrapp This issue will replace #34

**Comment by ramonawalls** [comment]
We are using [this spreadsheet](https://docs.google.com/spreadsheets/d/1nWuQnc8_wXapabgfSjQN42GggoanB3Ued36ZDKxqqoM/edit#gid=2137919201) to review terms. Please chip in and do a few terms if you have time.

**Comment by jzrapp** [comment]
Hi @ramonawalls,
I think the table is targeting a different issue from what we wanted to address with our original comment here. 
Some of the packages contain terms for which very specific definitions have been provided. However, the term itself may also be applicable to a different environment, but the specificity of the definition encourages duplication of terms, with slight modifications to the definition. A more coherent solution could be the establishment of overarching packages for e.g. physical characteristics of sample, or biological description of sample

Examples of such terms include:
"permeability" from hydrocarbon resources-cores package
"bacterial production" from water package
"bacterial respiration" from water package
"horizon" from soil package

**Comment by ramonawalls** [comment]
Ah! This is very helpful information, @jzrapp. I will reopen the other issue, and add a comment there to clarify how it differs from this one.

**Comment by ramonawalls** [comment]
This has been fixed in the latest spreadsheet.
