### ISSUE TITLE
Links to URIs for mixs v6.0.0 return 404 error

### ISSUE THREAD

**Issue by cpauvert** [GenomicsStandardsConsortium/mixs#390]
**Describe the bug**
Hi,
thanks for the update of the MIxS! I tried to access to terms through their URIs as specified on the website or in the SHACL file but the links are dead and produce only 404 errors.

**To Reproduce**
1. Go to https://w3id.org/mixs/terms/0000050 or https://w3id.org/mixs/vocab/sequencing_field
2. See 404 error

**Expected behavior**
The page for the term of the MIxS and its description.

Best regards,
Charlie

**Comment by turbomam** [comment]
Thanks @cpauvert 

We are working on this. I'm not sure what the most recent and relevant existing issue for this is, but we should definitely revisit #246

**Comment by ramonawalls** [comment]
I haven't pushed the latest links to w3id.org, so I don't expect them to work, but I hope we can fix it at the technical call tomorrow.

But first we need to resolve #391 about the page URLs.

**Comment by ramonawalls** [comment]
I did not read this carefully enough the first time. the URL should be .../mixs/... but .../gensc/...

Please see https://github.com/GenomicsStandardsConsortium/mixs/issues/233#issuecomment-657666511 for the correct format for URIs. I will send an announcement as soon as the redirect is working properly.

**Comment by cpauvert** [comment]
Hi,
I tried again with the updated format indicated in the [comment](https://github.com/GenomicsStandardsConsortium/mixs/issues/233#issuecomment-657666511) you suggested but instead of a 404 error, the page just does not load and throws a "This site can't be reached" page, and I'm redirected to gensc.org.

https://w3id.org/gensc/terms/MIXS_0000001
https://w3id.org/gensc/terms/MIXS_0000050

**Comment by cpauvert** [comment]
Hi @ramonawalls,
Was a decision made regarding a stable way to refer to the MiXS terms? 

I followed the link you sent but the suggested link raises 500 internal server error (ex: https://w3id.org/gensc/terms/MIXS_0000001). Previously mentioned format raises 404 error (ex:  https://w3id.org/mixs/terms/MIXS_0000001) and the documentation pages (for instance: https://genomicsstandardsconsortium.github.io/mixs/seq_meth) points to an URI that does not work as well (ex: https://w3id.org/mixs/terms/0000050).

I am sorry to nag you again, but I am using a research data management platform that needs persistent identifiers for the metadata.
Thanks in advance,
Charlie

**Comment by turbomam** [comment]
Sujay, is it fair to say that you are the best person to lock in generation of the numerical term IDs? I will help with the w3id resolution.

**Comment by cpauvert** [comment]
Fixed by @turbomam in #530 Thank you Mark!
