### ISSUE TITLE
Documentation pages should use MIxS IDs, not labels

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#391]
The URLs for the automatically generated documentation pages (at least the few I looked at) use the term label, but they should use the 7 digit numerical IDs, so that the w3id IDs will resolve properly. I think this is happening because the documentation pulls from the field for "name" which uses a string, not the ID. I think we need to change the YAML so the ID number is in the name field.

**Comment by turbomam** [comment]
The URLs for term pages are built form their numeric `id`s now. @sujaypatil96 and I are working on supporting the same style of MIxS class pages.
