### ISSUE TITLE
horizon AND soil_horizon ?

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#394]
- https://genomicsstandardsconsortium.github.io/mixs/soil_horizon/
- https://genomicsstandardsconsortium.github.io/mixs/horizon/

**Comment by only1chunts** [comment]
to me this looks like a simple change of name accidentally let through when the soil package was created, the "soil_horizon" term should be changed to just "horizon" as it is the same MIXS ID and definition already.
## Proposed action
Update soil package term name "soil_horizon" MIXSID:0001082 to "horizon" MIXSID:0001082

**Comment by mslarae13** [comment]
@only1chunts @ramonawalls @turbomam can we check in about this at the call in 04/16? And add it to the CIG agenda if needed?

**Comment by mslarae13** [comment]
We checked in about this on 04/16 (@only1chunts, @Woolly-at-EBI )

horizon and soil_horizon had the same ID. 

To do
- change description to "[soil horizon](https://www.ebi.ac.uk/ols4/ontologies/envo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FENVO_03600030)
ENVO:03600030  
http://purl.obolibrary.org/obo/ENVO_03600030
A soil layer which is parallel to the soil surface and which has roughly homogenous physical, chemical and biological properties relative to the soil layers above or beneath it."

**Comment by mslarae13** [comment]
NCBI showed
0 use of horizon
19k use of soil_horizon 
8k horizon_meth/method
0 soil horizon_meth

Resolved. horizon was removed. soil_horizon is available in soil & agriculture.

**Comment by turbomam** [comment]
Querying NMDC's Postgres version of NCBI Biosample, generated February 26 2024

_Jasper also have a JSON/MongoDB solution_

```SQL
select
	harmonized_name,
	count(1)
from
	ncbi_attributes_all_long naal
where
	harmonized_name = 'horizon'
	or harmonized_name = 'horizon_meth'
	or harmonized_name = 'horizon_method'
	or harmonized_name = 'soil_horizon_meth'
	or harmonized_name = 'soil_horizon'
	or harmonized_name = 'soil_horizon_meth'
	or harmonized_name = 'soil_horizon_method'
group by
	harmonized_name;
```

----

```
|harmonized_name|count |
|---------------|------|
|horizon_meth   |8,646 |
|soil_horizon   |18,799|
```
