### ISSUE TITLE
Updates to Google Sheet

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#410]
As reviewed in 05-July-2022 TWG call:

- removed `section` value of 'sequencing' from agriculture | lib_layout
- removed `section` column from packages sheet
- food-farm environment | prod_label_claims (and ???): removed blank cell that nudged MIxS  and GH issue off to right
- food-animal and animal feed|samp_transport_cont was erroneously ID'ed MIXS:0000755. Corrected to as MIXS:0001230-

**Comment by only1chunts** [comment]
@turbomam these all appear to be things that have been done already, please confirm that is the case, if so we can close this ticket.
