### ISSUE TITLE
sheet diff vs NMDC

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#413]
[MIxS 6 term updates](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809) vs [NMDC copy of MIxS 6 term updates](https://docs.google.com/spreadsheets/d/1-ocpwjx6nkBod6aj4kcYeSB5NRlhXaYCcuk3ooX2OV4/edit#gid=750683809) report

**Comment by ramonawalls** [comment]
@turbomam Is this done? There is a merged tag.

**Comment by ramonawalls** [comment]
Can this issue be closed?

**Comment by turbomam** [comment]
NMDC will be responsible for doing our own diff against MIxS now. Thanks.
