### ISSUE TITLE
annotate cardinality, for better sheet/yaml round trip potential

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#415]
- E
- M
- C
- X
-  `-`

LinkML doesn't have a concept of conditional yet

**Comment by turbomam** [comment]
The same kind of thing needs to be applied to [Requirement](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809&range=H:H)

**Comment by only1chunts** [comment]
We have discussed this in various TWG and CIG calls over the last few months, the general conclusion has been that M (mandatory) is easy to model so should be done now. The others can be modelled, but require more work to define the requirements of each term in a Package dependant manner, e.g. conditional mandatory should be defined as mandatory in certain package/checklist combinations when the condition is that the sample if from a particular environment.

## Proposal
No changes until the review process has been streamlined and we are in a situation to make Checklist/Package specific determinations (both requirements and examples) see ticket #?

**Comment by turbomam** [comment]
The MIxS 6.2.0 LinkML model accounts for the fact that a slot can be forbidden, optional, `recommended` or `required` in a class like a `Checklist` or `Extension`.
