### ISSUE TITLE
hyphens appearing in dataclass names

### ISSUE THREAD

**Issue by sujaypatil96** [GenomicsStandardsConsortium/mixs#418]
As documented partly in PR #403, there are dataclasses that are created in `mixs/mixs.py` that have a hyphen in them, which is not valid syntax for dataclass names.

To reproduce the error, run the following commands:
```
poetry install  # install project
```

```
python
>> import mixs.mixs as mixs  # import dataclass as module
```

```
from mixs import Host-Associated  # errors out with ValueError
```

We need to do a preliminary analysis and check if the problem needs to be fixed on LinkML's end or the MIxS end.

**Comment by turbomam** [comment]
@sujaypatil96  please provide  a list of the offending dataclasses

**Comment by sujaypatil96** [comment]
This is no longer an issue starting with MIxS v6.2, so closing it.
