### ISSUE TITLE
altitude in mix_v5 doesn't  have MIXS ID

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#42]
The  altitude structured comment name (row 8 on the MIxS tab in mixs_v5.xlsx) doesn't have a MIXS ID assigned to it.

BTW who is managing IDs? Are they always unique? Do the IDs persist across MIxS versions?

**Comment by ramonawalls** [comment]
The IDs came from an old database that is no longer maintained. Chris is correct that for the latest version, terms were added, but no ID was created. We also have no way to track splits or merges in the old MIxS.  This could be assessed programmatically and manually, and some mappings made to older versions, once we finish moving to RDF.

**Comment by lschriml** [comment]
No action items for this ticket, at this time.
