### ISSUE TITLE
Differences between package specific spreadsheets and master spreadsheet for mixs_v5

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#43]
I've noticed that the master spreadsheet and the package specific spreadsheet are not always in sync. For example, if I open mixs_v5.xlsx and filter for the water and I open MIxSwater_20180621.xlsx, the MIxSwater_20180621.xlsx spreadsheet includes the lat_lon term, but the mixs_v5.xlsx spreadsheet does not. 

Is this by design? Or was there a problem merging the package specific spreadsheets?

**Comment by wdduncan** [comment]
@only1chunts Are you generating multiple spreadsheets for the release of MIxS 6? I didn't think you were, but I may be wrong.

**Comment by lschriml** [comment]
We are, yes

**Comment by only1chunts** [comment]
@lscriml, are we?
I'd assumed we would be creating a single spreadsheet with multiple tabs as
we have done in previous releases.

**Comment by wdduncan** [comment]
Ok. I'll have to check this once the separate spreadsheets are created.

**Comment by lschriml** [comment]
Yes, agreed. That is what I was thinking. The the checklists would each have a tab, a tab for MIxS 6 core and a tab for the environmental packages.
