### ISSUE TITLE
sorting of linkml document

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#437]
- Linkml can sort them alphabetically or by rank (which would be an annotation property that we aren’t using yet)
- We should request that alphabetical sorting list required fields first then others

cc @ramonawalls @turbomam @only1chunts @lschriml

**Comment by turbomam** [comment]
When we say "LinkML can sort them", are we saying that software could be written to write sort terms or slots in alphabetical or rank order? Like for ordering columns in a tabular output?

For the record, [DataHarmonizer](https://github.com/cidgoh/DataHarmonizer) already does arrange slots into groups, and sorts both the groups and the columns, according to `rank`

**Comment by turbomam** [comment]
See https://github.com/linkml/linkml/issues/885

**Comment by ramonawalls** [comment]
Sorting happens in the spreadsheet one might be working with for linkml (such as schemasheets). Not a MIxS issue, except around editing workflow.

We could add rank if we want.

**Comment by ramonawalls** [comment]
@wdduncan can this issue be closed or do you still have questions?

**Comment by wdduncan** [comment]
@ramonawalls This issue can be closed if you are satisfied. IIRC, I opened it during a call in regards to this question coming up by others.
