### ISSUE TITLE
two different definitions of 'host body product'

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#44]
In the host-associated package, the definition for 'host body product' is:

Substance   produced by the **body**, e.g. **Stool**, mucus, where the sample was obtained from.   For foundational model of anatomy ontology (fma) or Uber-anatomy ontology   (UBERON) terms, please see https://www.ebi.ac.uk/ols/ontologies/fma or   https://www.ebi.ac.uk/ols/ontologies/uberon

In the other host packages it is:

Substance   produced by the **host's body**, e.g. **stool**, mucus, where the sample was obtained   from. For foundational model of anatomy ontology (fma) **(v 4.11.0)** or   Uber-anatomy ontology (UBERON) (v releases/2014-06-15) terms, please see   http://purl.bioontology.org/ontology/FMA or   http://purl.bioontology.org/ontology/UBERON

The typographical differences make it difficult to compare programatically.

**Comment by lschriml** [comment]
Fixed.
