### ISSUE TITLE
New policy: MIxS source of truth = TSV schemasheets

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#447]
- not the old [MIxS 6 term updates](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809) style sheets
- not schemasheets that live in public Google Sheets 

The only way to share one's edits will be by making a new GH branch, making the edits to the TSV files, committing, and making a pull request, which will provide a clear difference report (as long as the sheets stay in the same sort order?) 

This will allow for asynchronous, auditable edits

**Comment by turbomam** [comment]
We will need GH actions that normalize the TSVs

- sort
- heck for all expected headers
- strange characters
- newline normalizastion

**Comment by ramonawalls** [comment]
At later TWG meetings, we decided that the yaml files would remain the source of truth, but that our "typical" workflow would support schemasheets.
