### ISSUE TITLE
sequencing machine type

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#45]
OBI has agreed to add terms for any sequencing machines we need. We should supply them with a list. 

Currently under MIxS seq method - Perhaps consider changing the term to “sequence machine type”? 
Can the same “method” be run on many types of machines manufactured by different companies, or is it 1 machine = 1 method?

Seems like an algorithm is being equated with a machine. There are a number of companies that produce DNA sequencers. Do you include model number etc? 

Also check SRA template

**Comment by only1chunts** [comment]
1 method = 1 machine (I dont know of a specific method that can be run on multiple instruments)
BUT 
1 machine = multiple methods (see for example MGIseq product page https://en.mgitech.cn/products/ for table of different methods that can be run on each machine)
NB- MGI-Seq is the re-branded BGI-Seq (which is based on the old Complete-Genomics technology). 
With that in mind, I think we require terms in MIxS for both "sequencing instrument" and "sequencing method"
Will OBI include all the alias's of instruments? (BGI/MGI have multiple names for things depending on where its being sold (China vs rest of world) and have legacy names that are sometime still used! its a mess).
How granular will the list be? i.e. various earlier Illumina instruments had extension packs / patches or versions if you like, but the machine was not renamed (I dont know if they still do that?) 
Oxford have new versions of the chemistry used, does that come under "methods" or "machine"?
Sorry its more questions than answers!

**Comment by josieburgin** [comment]
Hi @ramonawalls and @only1chunts, I agree that two terms makes sense here - this is similar to how INSDC do it with an 'instrument' and 'platform'. 

If it's useful to have the controlled vocab that ENA use - these are the permitted values for instrument and platform (I think this is the same INSDC-wide):
https://ena-docs.readthedocs.io/en/latest/submit/reads/webin-cli.html#metadata-validation
You can have a look and see if there is anything from this list you would want to OBI to add.

**Comment by ramonawalls** [comment]
This has been superseded by #96 .
