### ISSUE TITLE
Do we really need a salinity and a 'sample salinity' term

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#478]
I can see why hydrocarbon resources-cores and hcr_fw_salinity need a distinct 'hydrocarbon resources-fluids' term, but the two following terms seem practically identical to me.

Is it a matter of asserting different preferred units or examples? That can be done on a shared term in the packages sheet, and doesn't require to different terms.

Environmental package | Structured comment name | Package item | Definition | Expected value | Value syntax | Example | Requirement | Preferred unit | Occurrence | MIXS ID
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
human-vaginal | samp_salinity | sample salinity | Salinity is the total concentration of all dissolved salts in a liquid or solid (in the form of an extract obtained by centrifugation) sample. While salinity can be measured by a complete chemical analysis, this method is difficult and time consuming. More often, it is instead derived from the conductivity measurement. This is known as practical salinity. These derivations compare the specific conductance of the sample to a salinity standard such as seawater | measurement value | {float} {unit} | 1 milligram per liter | X | milligram per liter, practical salinity unit, percentage | 1 | MIXS:0000109
air | salinity | salinity | The total concentration of all dissolved salts in a liquid or solid sample. While salinity can be measured by a complete chemical analysis, this method is difficult and time consuming. More often, it is instead derived from the conductivity measurement. This is known as practical salinity. These derivations compare the specific conductance of the sample to a salinity standard such as seawater. | measurement value | {float} {unit} | 25 practical salinity unit | X | practical salinity unit, percentage | 1 | MIXS:0000183

**Comment by only1chunts** [comment]
related issues #119 & #317

**Comment by ramonawalls** [comment]
Duplicate issue. Closing.
