### ISSUE TITLE
Structured comment names too long

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#507]
Following the TWG call today I checked the schemasheets version of the MIXS terms/checklists (as provided [here](https://docs.google.com/spreadsheets/d/1zsxvjvifDcmkt72v9m1_VKa2m73_THDJapJYK6dqidw/edit#gid=1228184583)) and found 6 instances of structured comment names that are longer than the allowed 20char.
Looking back at previous tickets, we had fixed these before v6 release, see ticket #84, so I'm not sure how they have not actually been fixed? Maybe they were present in multiple packages and only some got changed? Anyway, here is what they should be corrected to in the LinkML version:

|ID | structured comment name | package in which the wrong name persists | should be corrected to |
|---|-------------------------------|--------------------------------------------|--|
|MIXS:0000253|host_infra_specific_name| (symbiont-associated)|host_infra_spec_name|
|MIXS:0000254|host_infra_specific_rank| (symbiont-associated)|host_infra_spec_rank|
|MIXS:0000316|previous_land_use_meth| (agriculture)|prev_land_use_meth|
|MIXS:0000339|microbial_biomass_meth| (agriculture)|micro_biomass_meth|
|MIXS:0000571|non_mineral_nutr_regm| (agriculture)|non_min_nutr_regm|
|MIXS:0000872|host_family_relationship| (symbiont-associated)|host_fam_rel|

------
There is one more in the air package, but that is a transposition of structured comment name and label:
Currently in Schemasheet version is looks like this:

```
Term name - air_PM_concen
Term ID - MIXS:0000108
Structured comment name - air particulate matter concentration
Package(s) - air
```
It should be:

```
Term name - air particulate matter concentration
Term ID - MIXS:0000108
Structured comment name - air_PM_concen
Package(s) - air

```

**Comment by only1chunts** [comment]
These two terms have been updated and committed in branch https://github.com/GenomicsStandardsConsortium/mixs/tree/issue-551-tested-schemasheets .

MIXS:0000253  host_infra_specific_name becomes host_infra_spec_name
MIXS:0000254  host_infra_specific_rank becomes host_infra_spec_rank

**Comment by ramonawalls** [comment]
All structure comment names have been shortened already.
