### ISSUE TITLE
MIXS:0000054 and MIXS:0000076 structured comment names are too long

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#508]
Two terms in the "core" for the MISAG and MUIVIG checklists have strucutred comment names that exceed the 20Char limit:

**Current term details**
```
Term name - single cell or viral particle lysis kit protocol
Term ID - MIXS:0000054
Structured comment name - single_cell_lysis_prot
Definition - Name of the kit or standard protocol used for cell(s) or particle(s) lysis
Package(s) - CORE


Term name - single cell or viral particle lysis approach
Term ID - MIXS:0000076
Structured comment name - single_cell_lysis_appr
Definition - Method used to free DNA from interior of the cell(s) or particle(s)
Package(s) - CORE
```

**Suggested update(s)**

MIXS ID| old short name | suggested new short name |
|---|--|--|
|MIXS:0000054 | single_cell_lysis_prot |  sc_lysis_method |
|MIXS:0000076 | single_cell_lysis_appr | sc_lysis_approach |

**Additional context**
We have other protocol-type terms which use the word method instead of protocol hence my suggestion to use the word method here, but I'm equally happy to leave that as protocol here if thats what the consensus is.

**Comment by turbomam** [comment]
Great, thanks. I haven't implemented that yet. We could follow this pattern in the slot definitions file

SAFE Structured   comment name | Package item | Structured comment name
-- | -- | --
`> slot` | title | annotations
`>` |   | inner_key: structured_comment_name
sc_lysis_method | single cell or viral particle lysis kit protocol | single_cell_lysis_prot
sc_lysis_approach | single cell or viral particle lysis approach | single_cell_lysis_appr

**Comment by turbomam** [comment]
I love issues that have proposed solutions like this one does!

By the way, I still see the [old values](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=0&range=A78) on the Google sheet. That's what I prefer. Are we all in agreement that changes like @only1chunts has proposed **won't** be retroactively applied to the google sheets?

**Comment by only1chunts** [comment]
This update has been made in branch https://github.com/GenomicsStandardsConsortium/mixs/tree/issue-551-tested-schemasheets

**Comment by only1chunts** [comment]
also updated in turboman/mixs-subset-examples-first branch in file Update mixs_combined_slotdefs.tsv

**Comment by ramonawalls** [comment]
These have been fixed per @only1chunts suggestions.

**Comment by turbomam** [comment]
I was trying to sort and filter the "MIxS Source Transformation and Cleanup" project board and may have accidentally changed the assignee in this issue
