### ISSUE TITLE
issue-447-repo-tsvs-sot branch unmanageable, starting new issue-511... branch

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#511]
Start a new, leaner branch with testing from the beginning

**Comment by turbomam** [comment]
https://github.com/GenomicsStandardsConsortium/mixs/tree/issue-551-tested-schemasheets

**Comment by turbomam** [comment]
See [this section of the Makefile](https://github.com/GenomicsStandardsConsortium/mixs/blob/6ff69c967332eb4a1ab37f35a67c59420cdfa732/Makefile#L82-L176)

Will add a status report (what's done vs incomplete)

todo
- legacy term, checklist and package names have been retained as annotations, but the LinkML elements have been given systematic names.
- combine the classdef, slot_assignment and slotdef TSVs derived from the core and packages
- parse enumerations and assign them as ranges for the corresponding slots
- re-enable checklist/package combination generation, including hybrid MIXS identifiers
- experiment with patterns
  - current '^[aeiou]+$' pattern on `samp_name` is intentionally failing at step XXX as an illustration
- get more positive (expected to pass) and negative (expected to fail) example files
- ensure that example data in the schema passes the corresponding validations
-

**Comment by ramonawalls** [comment]
Sorry to be picky, but I think this issue and the branch should be names issue-511, not issue-551, right? We are only up to issue 520. It only matters because it is a bit confusing, and lord knows the issues in the repo are confusing enough without odd names.

**Comment by turbomam** [comment]
Scheamsheets are off the table as the source of truth now.

We have discussed using schemasheets as a way for contributors to initially hand their work off to the TWG, but we haven't fleshed out the implementation or end-user documentation

Searching for "template" in the issues and PRs will show the old ways we told people to share their contributions

I have merged in a branch that generates a derived report-style schemsheet about classes and terms, but not enumerations, structured pattern settings, or a few other schema elements. 

see also 
- https://github.com/linkml/schemasheets/issues/113
