### ISSUE TITLE
Non-functional mixs urls

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs#518]
From @jkoehorst 

I am incorporating the MIXS URI’s into the ontologies but noticed that some URLS are still 404?  [MIXS:ChecklistClass](https://w3id.org/mixs/terms/ChecklistClass) > https://genomicsstandardsconsortium.github.io/mixs/terms/ChecklistClass

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ramonawalls** [comment]
Two issues: interlinks and case specific difference and w3id issue
- URIs are being generated automatically, but the w3id prefix is wrong
- To fix the Mac generated case specific issue, create documentation with github actions.The action is there, but gh actions won’t build it because the file is too large.

**Comment by turbomam** [comment]
@ramonawalls and @JKoehorst: I believe this is resolved. Could you please confirm?

**Comment by sujaypatil96** [comment]
All the CURIEs on MIxS term documentation pages: https://genomicsstandardsconsortium.github.io/mixs/term_list/ resolve successfully. 

I am closing this issue. Please feel free to reopen if you find that any documentation pages have broken/404 URLs.
