### ISSUE TITLE
rename ...551... branch -> ...511...

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#521]
@turbomam will create a new `issue-511-tested-schemasheets` branch off of this misnamed `issue-551-tested-schemasheets` branch. Then @ramonawalls can make a branch off of the new `issue-511-tested-schemasheets`

**Comment by turbomam** [comment]
@ramonawalls: I am closing this issue and related old PRs, You can make a branch off of `issue-511-tested-schemasheets` in order to convert `schemasheets/tsv_in/originals/MIxS_6_term_updates_MIxS6_packages-Final_clean.tsv` into single, global definitions in `schemasheets/tsv_in/MIxS_6_term_updates_global_partial_slotdefs.tsv`

**Comment by turbomam** [comment]
The 'partial' token in `schemasheets/tsv_in/MIxS_6_term_updates_global_partial_slotdefs.tsv`'s filename should be removed

**Comment by turbomam** [comment]
If the examples or requirement/cardinality for a term should be customized for any checklist or package class, that should go in `schemasheets/tsv_in/MIxS_6_term_updates_slot_assignments_and_usages.tsv`

**Comment by ramonawalls** [comment]
Thanks, @turbomam !
