### ISSUE TITLE
cultural_era

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#535]
**New term details**
This term is being requested as a required term in the Core set of terms for the new MINAS (ANcient Sequence) checklist. See [project page](https://github.com/orgs/GenomicsStandardsConsortium/projects/2)

```
Term name -** This is required **
Structured comment name - cultural_era
Definition - The   cultural era approximating the period in which the individual lived from   https://chronontology.dainst.org/ or PeriodO. Specify when no value for   'sample_age' is present, or additionally to it.
Expected value - Chronotology or PeriodO term; text
Value syntax - {termLabel} {[termID]}|{text}
Example - Copper Age [Chronotology: NW6hofAScJSE]
Preferred unit - 
Package(s) - NA
Section - Investigation
```
As this is a new checklist item we should assess whether it is suitable for use in any of the existing checklists:
| Checklist | -/C/E/M/X |
|---|---|
|minas| C |
|migs_eu|  |
|migs_ba|  |
|migs_pl|  |
|migs_vi|  |
|migs_org|  |
|mims|  |
|mimarks_s|  |
|mimarks_c|  |
|misag|  |
|mimag|  |
|miuvig|  |

**Additional context**

**Comment by jfy133** [comment]
@only1chunts (realised here might be easier rather email, so sorry for the repeat question)

Could this issue be updated to:

- remove the `minas` checklist from the table, 
- Update 'packages' in the code block to state `ancient` (this is the best word I can think for the package for now, and will work best with other packages, e.g. `ancient` + `host-associated` meaning ancient individual, for example.)

Would it be possible to create a `minas` label too? or woudl you rather all new terms just be added to the project board?

If it is possible to add a label, would I be able to get permissions to add labels to issues as we create tehm for teh `ancient` package (presumably meaning I would have to be added to the github repository as a collaborator (maybe with 'triage' role?))?  Fine if not though!

**Comment by lschriml** [comment]
@jfy133 I have added you with 'triage role' -- ready for adding new labels

**Comment by jfy133** [comment]
Thanks @lschriml ! I will try it out next week 👍

**Comment by jfy133** [comment]
@lschriml @only1chunts  I am able to assign labels but not create new ones, nor edit the opening post here. 

Could you make the label, and then I can close this issue and make a new one with the changes in the proposal?

**Comment by jfy133** [comment]
Closing in favour of https://github.com/GenomicsStandardsConsortium/mixs/issues/546, as this instead refers to the `ancient` extension rather than the original checklist idea.
