### ISSUE TITLE
Defining MIxS ID space for MIxS v.6

### ISSUE THREAD

**Issue by lschriml** [GenomicsStandardsConsortium/mixs#58]
As discussed during June CIG call (and previous calls):
  MIXS ID space: 
      - reusing IDS published in MIxS v5
      MIXS IDs are seven digits. current range : MIXS:0000001 to MIXS:0001106
      - with one ID for each unique term (e.g. depth in MIxS Core and in 
                 host-associated package - would have the same ID. 
      - Where there are no MIXS IDs currently, new IDS will be created
           - this step will begin with the MIxS Core and proceed through the packages, alphabetically.
     - New IDs for the packages will be created and recorded in: 
              MIxS Core >> environmental package field, e.g.
                       package                       MIXS ID
                         air                                   MIXS:0010000
                         built-environment         MIXS:0010001
                         host-associated            MIXS:0010002

    - We will add a column, to enable mappings, for 
         MIGS IDs  (utilized in GOLD database, SIGS, Environmental Microbiology journals)
         TDWG non-numerical ids, see:  https://terms.tdwg.org/wiki/Class:MIxS

AI for CIG (Chris Hunter or Lynn Schriml): register MIXS prefix with W3C

**Comment by lschriml** [comment]
@only1chunts 
Decentralized Identifiers (DIDs) v1.0.   - https://www.w3.org/TR/did-core/
     
     https://www.w3.org/2019/did-wg/WorkMode/getting-started
     https://www.w3.org/TR/did-spec-registries/#the-registration-process

**Comment by only1chunts** [comment]
thanks @lschriml , but it's still beyond my level of comprehension as to what we need to do!?

**Comment by lschriml** [comment]
No worries, I’ll look into it further next week when I’m back in the office.

Cheers,
Lyn

**Comment by ramonawalls** [comment]
I have looked up how to do it and set up a repo at https://github.com/GenomicsStandardsConsortium/w3id.org. Will go over it on Monday's mixs as rdf call, and maybe we can just do the pull request during the call.

**Comment by lschriml** [comment]
I have gone through MIXS core and packages, uniqued the IDS, and added them back to the v6.0 doc:
https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=567040283
-- added a new column in Core and Packages 

--> we have 601 unique terms

 MIXS IDS: https://docs.google.com/spreadsheets/d/1p5Ziciznkk9er99aPhc7ed8NDE0oUKw0rrBlEOYUtiA/edit#gid=0

Review items identified from this task: 
https://docs.google.com/spreadsheets/d/16qXxd-VtqK_6xVbnbCcwR5rztjYMBkAyv0NiRZWXe0c/edit#gid=0
-- linked to their Github ticket IDs

Cheers,
Lynn

**Comment by lschriml** [comment]
@ramonawalls @only1chunts: 

Following our MIXS RDF call today, 
(1)     New spreadsheets to separate MIxS from other checklists into their own tabs: 
        I added tabs in the [MIxS 6 term updates]          (https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=567040283)            (our working doc for MIxS v6) 
     - I added tabs for MIxS core only, MIMAG, MISAG, MIUVIG (while keeping original tabs (e.g. MIxS6 core - to edit)) 

(2) IDs for Checklists and Packages 
      In the [MIxS IDs google doc](https://docs.google.com/spreadsheets/d/1p5Ziciznkk9er99aPhc7ed8NDE0oUKw0rrBlEOYUtiA/edit#gid=786235511)
     --> ID range for MIXS terms are defined
            IDs for checklists
            IDS for environmental packages 

A couple of notes/questions: 
   -- in our main 'MIxS6 Core -- columns L to V specify the checklists
         [1] column N = migs_pl  --> We don't yet have MIGS Plants in INSDC --> I added it to the MIXS IDs (for checklists)
         [2] column P = migs_org  --> Question: We don't have this checklist in the current version, is it intended for animals ?? 
         [3] column Q: I think this is MIMS ??? 

      to clarify: column R, mimarks_s = MIMARKS Survey.    
                                                          BioSample:  from the environment, without culturing or identification of the organisms.
                       column S, mimarks_c - specimen       
                                                           BioSample: from cultured or voucher-identifiable specimens
          
**MISAG, MIMAG, MIUVIG in BioSample**
While comparing the published checklists, and what is presented in BioSample, I noted some differences. 
I checked, and our MIxS 5.0 aligns with the publications, 
however, the MISAG, MIMAG and MIUVIG in BioSample are not aligned with the publications or MIxS.

Cheers,
Lynn

**Comment by lschriml** [comment]
**DONE: adding MIxS IDs to MIxS Food.**
     New tab added to MixS 6.0 for new Food packages 
https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=814154599

**MIxS  IDs:**
https://docs.google.com/spreadsheets/d/1p5Ziciznkk9er99aPhc7ed8NDE0oUKw0rrBlEOYUtiA/edit#gid=1284299198
with tabs: 
  unique term ID list 
  MIxS6 new IDs

**Comment by lschriml** [comment]
To Do: 
Review packages, add IDs: 
     [MIxS-SARS-CoV-2 ](https://docs.google.com/spreadsheets/d/1ZV5PIu9RDNj7-NcHlLiLl-u1_V5gW_vfg-D9b83SqeY/edit#gid=0)
     [MIxS-SA ](https://docs.google.com/spreadsheets/d/1k_3lZ5zEF4SQBFe0eem_vpjt26mIdcKh2La2xCx3BJE/edit#gid=0)
     MIxS-Ag

**Comment by lschriml** [comment]
[SARS-CoV-2 MIxS package](https://docs.google.com/spreadsheets/d/1ZV5PIu9RDNj7-NcHlLiLl-u1_V5gW_vfg-D9b83SqeY/edit#gid=0) 
    -- terms aligned to MIxS terms, MIxS IDs added
   -- ready for review with NCBI and Will Hsiao's team

**Comment by lschriml** [comment]
Only outstanding tasks will be to add MIXS IDs to completed packages, 
once final revisions are complete. 
Lynn

**Comment by only1chunts** [comment]
Added to the v6 project "done" column so as its not missed in the changes document we generate

**Comment by turbomam** [comment]
@lschriml and friends: all MIxS slot (aka terms) and classes (eg `Checklists` and `Extensions`) have seven-digit `id`s now. Term `id`s resolve to our documentation pages when constructed like http://w3id.org/mixs/0000002, as promised by our schema's [prefix definition](https://github.com/GenomicsStandardsConsortium/mixs/blob/445efb5e0a86b074dbbc5a3cae8ee03c2df11ac7/src/mixs/schema/mixs.yaml#L18-L18C31) 

@sujaypatil96 and I will be [adding numerical `id` resolution for classes very soon](https://github.com/linkml/linkml/issues/1672). Feel free to up-vote that issue!

MIxS combination class `id`s are constructed from the `Checklist` and `Extension`s `id`s, like [MIXS:0010007_0016012 for `MimsSoil`](https://github.com/GenomicsStandardsConsortium/mixs/blob/445efb5e0a86b074dbbc5a3cae8ee03c2df11ac7/src/mixs/schema/mixs.yaml#L21806-L21814), as previously discussed.

Thanks for all of the great guidance. what are the criteria for closing this issue now.

**Comment by ramonawalls** [comment]
> Thanks for all of the great guidance. What are the criteria for closing this issue now?

@turbomam , as I understand it, this issue was to make sure that the MIxS ids of the form MIXS:xxxxxxx were in place, consistent, and unique for terms across all the old spreadsheets. It is now resolved.
