### ISSUE TITLE
misnomer in mixs documentation

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#599]
On this page : https://genomicsstandardsconsortium.github.io/mixs/
the names of the MIMARKS checklists is incorrect:

MIMARKSSpecimen | Minimal Information about a Marker Specimen: specimen

MIMARKSSurvey | Minimal Information about a Marker Specimen: survey

These should be:
MIMARKSSpecimen | Minimal Information about a Marker **Sequence**: specimen

MIMARKSSurvey | Minimal Information about a Marker **Sequence**: survey

See [original publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3367316/).

**Comment by turbomam** [comment]
Thanks. I'll review with @sujaypatil96 

The page you are referring to was generated from @cmungall's older LinkML transformation

I have a new transformation that will be ready for general review and feedback at Bangkok.

I guess we should still update what we have in front of the public now anyway.

**Comment by sujaypatil96** [comment]
Happy to make the necessary schema change to update the description for the [MimarksC](https://genomicsstandardsconsortium.github.io/mixs/0010009/) and [MimarksS](https://genomicsstandardsconsortium.github.io/mixs/0010008/) checklists. Will have a PR out for this soon.

**Comment by turbomam** [comment]
@sujaypatil96 I am solving this issue now

**Comment by turbomam** [comment]
Find  'Minimal Information about a Marker Specimen' in `src/mixs/schema/mixs.yaml` and replace with 'Minimal Information about a Marker Sequence'

**Comment by turbomam** [comment]
Two hits for the ...specimen and  ...survey variants

**Comment by turbomam** [comment]
```shell
git diff src/mixs/schema/mixs.yaml
```

> ```
> diff --git a/src/mixs/schema/mixs.yaml b/src/mixs/schema/mixs.yaml
> index 01fb71033..4ac3c6df0 100644
> --- a/src/mixs/schema/mixs.yaml
> +++ b/src/mixs/schema/mixs.yaml
> @@ -15283,7 +15283,7 @@ classes:
>          recommended: true
>      class_uri: MIXS:0010011
>    MimarksC:
> -    description: 'Minimal Information about a Marker Specimen: specimen'
> +    description: 'Minimal Information about a Marker Sequence: specimen'
>      title: MIMARKS specimen
>      comments:
>      - for marker gene sequences from cultured or voucher-identifiable specimens
> @@ -15384,7 +15384,7 @@ classes:
>          recommended: true
>      class_uri: MIXS:0010009
>    MimarksS:
> -    description: 'Minimal Information about a Marker Specimen: survey'
> +    description: 'Minimal Information about a Marker Sequence: survey'
>      title: MIMARKS survey
>      comments:
>      - for marker gene sequences obtained directly from the environment
> ```
>

**Comment by turbomam** [comment]
now running `date; make clean all test; date` locally, in addition to the GitHub action

**Comment by turbomam** [comment]
started at Tue Jul  9 10:58:03 AM EDT 2024
