### ISSUE TITLE
soil texture measure MIXS:0000335 

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#600]
We currently have 2 term names meaning the same thing with the same MIXS ID that needs to be fixed:

MIXS:0000335
SCN: soil_text_measure
Item name: soil texture measurement
Definition: The relative proportion of different grain sizes of mineral particles in a soil, as described using a standard system; express as % sand (50 um to 2 mm), silt (2 um to 50 um), and clay (<2 um) with textural name (e.g., silty clay loam) optional.
Expected value: measurement value
Value syntax: {float} {unit}
Extension: soil

MIXS:0000335
SCN: texture
Item name: texture
Definition: The relative proportion of different grain sizes of mineral particles in a soil, as described using a standard system; express as % sand (50 um to 2 mm), silt (2 um to 50 um), and clay (<2 um) with textural name (e.g., silty clay loam) optional.
Expected value: measurement value
Value syntax: {float} {unit}
Extension: agriculture

Of note, we also have soil_text_class which is very similar:

MIXS: 0001164
SCN: soil_texture_class
Item name: soil texture classification
Definition: One of the 12 soil texture classes use to describe soil texture based on the relative proportion of different grain sizes of mineral particles [sand (50 um to 2 mm), silt (2 um to 50 um), and clay (<2 um)] in a soil.
Expected value: enumeration
Value syntax: [clay|clay loam|loam|loamy sand|sand|sandy clay|sandy clay loam|sandy loam|silt|silty clay|silty clay loam|silt loam]
Extension: food-farm environment

**Propose to update Agriculture package with correction of term name to soil_texture**

**Comment by only1chunts** [comment]
closing ticket as change is being implemented in v6.2, see ticket #529

**Comment by lschriml** [comment]
Good idea Chris Sent from my iPhoneOn Jul 18, 2023, at 7:34 AM, Chris Hunter ***@***.***> wrote:﻿
We currently have 2 term names meaning the same thing with the same MIXS ID that needs to be fixed:
MIXS:0000335
SCN: soil_text_measure
Item name: soil texture measurement
Definition: The relative proportion of different grain sizes of mineral particles in a soil, as described using a standard system; express as % sand (50 um to 2 mm), silt (2 um to 50 um), and clay (<2 um) with textural name (e.g., silty clay loam) optional.
Expected value: measurement value
Value syntax: {float} {unit}
Extension: soil
MIXS:0000335
SCN: texture
Item name: texture
Definition: The relative proportion of different grain sizes of mineral particles in a soil, as described using a standard system; express as % sand (50 um to 2 mm), silt (2 um to 50 um), and clay (<2 um) with textural name (e.g., silty clay loam) optional.
Expected value: measurement value
Value syntax: {float} {unit}
Extension: agriculture
Of note, we also have soil_text_class which is very similar:
MIXS: 0001164
SCN: soil_texture_class
Item name: soil texture classification
Definition: One of the 12 soil texture classes use to describe soil texture based on the relative proportion of different grain sizes of mineral particles [sand (50 um to 2 mm), silt (2 um to 50 um), and clay (<2 um)] in a soil.
Expected value: enumeration
Value syntax: [clay|clay loam|loam|loamy sand|sand|sandy clay|sandy clay loam|sandy loam|silt|silty clay|silty clay loam|silt loam]
Extension: food-farm environment
Propose to update Agriculture package with correction of term name to soil_text_measure
