### ISSUE TITLE
restore @only1chunts's  mixs_v6.xlsx

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#610]
The released Excel version of MIxS 6.1 is https://github.com/GenomicsStandardsConsortium/mixs/blob/main/mixs/excel/mixs_v6.xlsx

@only1chunts made some fixes to that, based on issues in the repo, in https://github.com/only1chunts/mixs-cih-fork/raw/main/mixs/excel/mixs_v6.xlsx

I don't remember what all of the changes were, but he showed me a good audit trail. It was never merged into the main branch of this repo in anticipation of MIxS 6.2 RC, or something like it.

I was using https://github.com/only1chunts/mixs-cih-fork/raw/main/mixs/excel/mixs_v6.xlsx as input into the MIxS 6.2 RC build process because it was traceable back to this repo.

Unfortunately, it appears the the entire https://github.com/only1chunts/mixs-cih-fork has been deleted.

In order to keep working on MIxS 6.2 RC now, I am making a new branch based on this repo's main branch, but overwriting https://github.com/GenomicsStandardsConsortium/mixs/blob/main/mixs/excel/mixs_v6.xlsx with a cached copy of https://github.com/only1chunts/mixs-cih-fork/raw/main/mixs/excel/mixs_v6.xlsx that I found on one of my computer.

If we can either restore https://github.com/only1chunts/mixs-cih-fork or make MIxS 6.2 RC the  main branch of this repo, then it won't be necessary to merge the branch.

**Comment by turbomam** [comment]
see https://github.com/GenomicsStandardsConsortium/mixs/blob/issue-610-temp-mixs-xlsx-home/mixs/excel/mixs_v6.xlsx

**Comment by turbomam** [comment]
raw link: https://github.com/GenomicsStandardsConsortium/mixs/raw/issue-610-temp-mixs-xlsx-home/mixs/excel/mixs_v6.xlsx

**Comment by only1chunts** [comment]
ah, I destroyed that fork as I thought it had been copied over to your new fork already!  Sorry its gone, I do have a copy on my PC if there is stuff that we need to salvage from it?

**Comment by only1chunts** [comment]
OK, I can see above that you have recoved a copy of the excel file, thanks. That is the one I had made updates to, it exactly matches the one on my PC. Plus there is a change log file that I also had on my PC here:
[2023-May-31-change-log.txt](https://github.com/GenomicsStandardsConsortium/mixs/files/12796889/2023-May-31-change-log.txt)

**Comment by turbomam** [comment]
file added to new branch, not restored to original branch

closing
