### ISSUE TITLE
Change references to schema `id` and `from_schema` slot in YAML source

### ISSUE THREAD

**Issue by sujaypatil96** [GenomicsStandardsConsortium/mixs#616]
The main YAML source file (currently: https://github.com/GenomicsStandardsConsortium/mixs/blob/main/src/mixs_6_2_for_merge/schema/mixs_6_2_for_merge.yaml) has:

* id: https://w3id.org/mixs-6-2-rc
* from_schema: https://w3id.org/mixs-6-2-rc

This needs to be changed so we're using https://w3id.org/mixs

Note: This will further require modifications to the .htaccess file on w3id.org (https://github.com/perma-id/w3id.org/blob/master/mixs/.htaccess) so that the patterns know where to look for files/artifacts in the new directory structure.

**Comment by turbomam** [comment]
All appearances of the regular expression `mixs.6.2`, across the repo, have been replaced with plain `mixs`

**Comment by turbomam** [comment]
- https://w3id.org/mixs redirects to the documentation index page, https://genomicsstandardsconsortium.github.io/mixs/

**Comment by turbomam** [comment]
I recommend removing all references to the never-implemented "vocab endpoint"

**Comment by turbomam** [comment]
https://github.com/perma-id/w3id.org/pull/3650/files

**Comment by turbomam** [comment]
Because the [(expandable) schema source](https://linkml.io/linkml-model/latest/docs/from_schema/#linkml-source) for `from_schema` is says it is a read-only slot, I am removing all of those assertions.
