### ISSUE TITLE
Change enums names to PascalCase not SHOUTINGCASE

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#627]

**Comment by sujaypatil96** [comment]
I think this issue can be closed. A fix was made in the schema to change the casing of enum names, and the documentation reflects the same as well: https://genomicsstandardsconsortium.github.io/mixs/enumerations/

**Comment by mslarae13** [comment]
@turbomam to double check. Need to run linkML linter & get a report of all elements that don't stick to default rules.

**Comment by turbomam** [comment]
will run `linkml-lint`, possibly silencing some rules that we have chosen to ignore
