### ISSUE TITLE
gather user input on web documentation contents and style

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#635]
@sujaypatil96 @cmungall and I have worked very hard to 

1. give the MIxS documentation pages a MIxS favor (instead of using LInkML jargon) 
2. temporarily disable the slowest documentation features 

Each one of us has additional ideas about 1., and hope about re-enabling 2. Instead of debating amongst us LBL people, I would like to open this discussion to at least include the TWG, and preferably some outside, non-technical users

**Comment by sujaypatil96** [comment]
This is a fairly broad issue but I think a lot of concerns around jargon and build speed that were discussed at the time have been addressed. If there are any specific concerns we can make issues for it, but I think this issue can be closed.

Feel free to reopen if you disagree.
