### ISSUE TITLE
Misc. comments/feedback on documentation pages that need to be addressed

### ISSUE THREAD

**Issue by sujaypatil96** [GenomicsStandardsConsortium/mixs#636]
Some comments from a documentation review with @cmungall on 10/16:

- [x] Definitely show _titles_ of elements [imp]
- [ ] Remove _Subsets_ section from TOC on RHS of index/landing page
- [ ] Move _Enumerations_ to it's own page on LHS, similar to 'full term table' and 'combinations'
- [x] Remove _Inheritance_ section from class (Checklist/Extension/Combination) pages (justification: they're developer focussed and not useful for consumers of the standard)
    - [x] however, combo pages should state in simple terms what checklist and extensions they are composed from
- [ ] Use CamelCase for enums
- [x] Remake Terms table on _class_ documentation pages so that the Inheritance column isn't shown anymore. Instead have another column at the beginning of the terms table called 'MIXS ID'
- [x] Be consistent when showing cardinality on term pages, i.e., show it in the way that it appears in the terms table on class documentation pages
- [x] Drop annotations for which values don't exist
- [x] Remove _schema source_ section

CC: @turbomam

**Comment by turbomam** [comment]
I do not support removing subsets

**Comment by turbomam** [comment]
- https://github.com/GenomicsStandardsConsortium/mixs/issues/635
