### ISSUE TITLE
Terms to resolve based on ids

### ISSUE THREAD

**Issue by sujaypatil96** [GenomicsStandardsConsortium/mixs#637]
The current deployment of the documentation does not resolve terms based on ids like before. Restore that feature such that the terms resolve based on ids and not their names.

**Comment by turbomam** [comment]
This task is not complete if only terms resolve by numerical id. See PR notes and links.

**Comment by turbomam** [comment]
- https://github.com/GenomicsStandardsConsortium/mixs/issues/635

**Comment by turbomam** [comment]
I am not in favor of switching to ID based term resolution except in combination with class resolution by id.

Can you show some evidence that the ID resolution needs to be implemented before October 19th?

**Comment by sujaypatil96** [comment]
I dug up this issue: https://github.com/GenomicsStandardsConsortium/mixs/issues/391

It doesn't explicitly say that it needs to be done by 10/19, but it was an issue that @ramonawalls had brought up last year, and we had worked on to get a feature into docgen to support that.

**Comment by sujaypatil96** [comment]
I'm completely okay with whatever we decide, _id_ based resolution or _name_ based resolution.

**Comment by turbomam** [comment]
We agreed to stick with the precedent of id-based term lookup and are working on id-based class lookup too
