### ISSUE TITLE
update env_package ?

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#64]
Currently:
```
structured comment = env_package 
Item name = environmental package 
Definition = MIxS extension for reporting of measurements and observations obtained from one or more of the environments where the sample was obtained. All environmental packages listed here are further defined in separate subtables. By giving the name of the environmental package, a selection of fields can be made from the subtables and can be reported
```

Similar to the "Investigation Type" field, the values for this are only the option of the package chosen. Do we need to update the definition to better explain that this field just records the set of terms used if the user selects a defined package? i.e. it's not really a field the user can manually adjust, its implicit from the package they select and will be used by whatever tools we build for validation so that we know which checklist package to validate against.

**Comment by only1chunts** [comment]
to be removed

**Comment by lschriml** [comment]
this term has been removed from checklists and packages.
