### ISSUE TITLE
Add additional metadata for all checklists and extensions

### ISSUE THREAD

**Issue by cmungall** [GenomicsStandardsConsortium/mixs#653]
Each checklist and extension should have a text description. Checklists should have a publication link as `source`.

- http://www.gensc.org/pages/standards/checklists.html - descriptions and pub links can be mined from here
- http://www.gensc.org/pages/standards/extensions.html - no current descriptions?

Checklists may have a list of accepted abbreviations - we should normalize the names here

E.g for MIMAGS we use C vs S, but http://www.gensc.org/pages/standards/checklists.html has SU and SP. NCBI spells these out

**Comment by turbomam** [comment]
see 
- https://github.com/GenomicsStandardsConsortium/mixs/issues/646
