### ISSUE TITLE
host_spec_range

### ISSUE THREAD

**Issue by ndheilly** [GenomicsStandardsConsortium/mixs#66]
The definition needs to be updated to allow inclusion of many species for parasites with complex life cycle.
Some parasites have a very broad host range. Nobody will make the effort to list them all at the species level and the definition should clearly state that different taxonomic levels can be included.
Or did you mean the host from which the organism was collected?

**Comment by only1chunts** [comment]
**Current term details**
```
Term name - host specificity or range
Structured comment name - host_spec_range
Definition - The NCBI taxonomy identifier of the specific host if it is known
Expected value - NCBI taxid
Value syntax - {integer}
Example - 9606
```
I believe the definition should be reworded to indicate that this term should be used to describe the possible species/range that could play host to this particular parasite or sample. The similar term "specfic_host" should be used for the actual specific host of the sampled parasite/microbiome.

**Suggested update(s)**
```
Term name - host specificity or range
Structured comment name - host_spec_range
Definition - If the host species or range of species is known please provide details, for specific species please provide the NCBI taxonomic ID, otherwise a genus or textual descriptions of the host range.
Expected value - NCBI taxid or Free text
Value syntax - {integer}| {text}
Example - 9606 | most primates

**Comment by ndheilly** [comment]
it looks good to me. Thanks!

**Comment by only1chunts** [comment]
**Final decision**
Update definition, expected value, value syntax and example:
```
Definition - If the host species or range of species is known please provide details, for specific species please provide the NCBI taxonomic ID, otherwise a genus or textual descriptions of the host range.
Expected value - NCBI taxid or Free text
Value syntax - {integer}| {text}
Example - 9606 | most primates
```

**Comment by lschriml** [comment]
Looking at 'host_spec_range' in MIxS 6 core - to edit tab:
the definition is: 
The range and diversity of host species that an organism is capable of infecting, defined by NCBI taxonomy identifier.

--> should we add:  otherwise a genus or textual descriptions of the host  ??
