### ISSUE TITLE
should we spin off a technical issues only repo?

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#666]
like the NMDC issues repo, for those who are aware of it: https://github.com/microbiomedata/issues/issues

**Comment by cmungall** [comment]
I'm assuming that over time most new issues will be for content and many of the technical issues will stabilize, which would argue for keeping it simple and having one tracker for now. But I appreciate it's hard to find content issues. Some standard labels would help

**Comment by ramonawalls** [comment]
We have quite a lot of labels already -- perhaps too many to help improve sorting issues. I think a better solution than starting a new tracker is to clean up our labels and create documentation on how to use them consistenly.

**Comment by mslarae13** [comment]
I'm going to close this. Issues should always be technical. Non-technical or non-actionable items should be discussions.
