### ISSUE TITLE
update definition of relevant electronic resources

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#67]
Currently:
```
structured comment name = url
item name = relevant electronic resources 
definition = 
```
There is no definition included for this item.
my suggestion:
Any web address of an associated resource, e.g. a genome browser. The value should include the protocol (http, https or ftp).

**Comment by only1chunts** [comment]
discussed at zoom call Feb 8th:
"URL" is a reserved term so should not be used as the structured comment name.
Can we use a Darwin Core term here instead?
 DWC have: 
https://dwc.tdwg.org/terms/#dwc:associatedMedia
https://dwc.tdwg.org/terms/#dwc:associatedReferences
https://dwc.tdwg.org/terms/#dwc:associatedSequences
Can we change the structured comment name to "Associated_resource" which is an aggregate of those terms?

**Comment by pbuttigieg** [comment]
>Can we change the structured comment name to "Associated_resource" which is an aggregate of those terms?

That would be useful in the GBWG DwC MIxS mapping task team - the mixs:associated_resource would be the union of those DwC terms (unless MIxS wants to split them too)

**Comment by 79-6d** [comment]
Resource relationship can also be expressed in RDF - which is similar to resource relationship extension of Darwin Core:

https://dwc.tdwg.org/terms/#dwc:resourceID
https://dwc.tdwg.org/terms/#dwc:relationshipOfResource

See more: https://dwc.tdwg.org/terms/#resourcerelationship

**Comment by only1chunts** [comment]
The tdwg working group GBWG has started dwc-mixs mappings, and this is the [ticket ](https://github.com/tdwg/gbwg/issues/23 )referring to our URL term.
It suggests our URL maps to DWC's [references](http://purl.org/dc/terms/references)
The DWC details are:
```
URI - http://purl.org/dc/terms/references
Label - References
Definition - A related resource that is referenced, cited, or otherwise pointed to by the described resource.
Comment - This property is intended to be used with non-literal values. This property is an inverse property of Is Referenced By.
Type of Term - Property
Subproperty of - Relation (http://purl.org/dc/elements/1.1/relation), Relation (http://purl.org/dc/terms/relation)
```

Do we agree?
Should we rename our "URL" [MIXS:0000091] term to be "references"? 
Personally I think no, because the name "references" to me suggests that its like a reference list of a manuscript which is not the sort of thing we want in a MIxS checklist. I prefer the earlier suggested name of "Associated_resource"

**Comment by only1chunts** [comment]
**Current term details**
```
Term name - relevant electronic resources 
Term ID - MIXS:0000091
Structured comment name - url
Definition - 
Expected value - URL
Value syntax - {URL} 
Example - http://www.earthmicrobiome.org/
Preferred unit - 
Package(s) - CORE
```
**Suggested update(s)**
Update the structured comment name, definition, expected value and syntax:
```
Term name - relevant electronic resources 
Term ID - MIXS:0000091
** Structured comment name - associated_resource **
** Definition - A related resource that is referenced, cited, or otherwise associated to the sequence. **
** Expected value - reference to resource **
** Value syntax - {PMID} | {DOI} | {URL} **
Example - http://www.earthmicrobiome.org/
Preferred unit - 
Package(s) - CORE
```

**Comment by only1chunts** [comment]
@lschriml @ramonawalls are the suggested updates to Structured Comment, Definition, expected value and value syntax all OK to go ahead and make?
I think they are.

**Comment by lschriml** [comment]
@only1chunts 
    Looks good.
One thought for the structured comment name, what about 'web resource'  ?

**Comment by only1chunts** [comment]
I think the discussion above suggests that Associated Resources was chosen to align better with the DWC terminology

**Comment by only1chunts** [comment]
update made in spreadsheet, MIxS_only_v6, and MIxS6 Core to Edit, and MIMAGS, MISAG and MIUVIG checklist sheets.
