### ISSUE TITLE
GSC standards website pages, add back in the MIxS- labels

### ISSUE THREAD

**Issue by lschriml** [GenomicsStandardsConsortium/mixs#693]
Action Items: 
(1) add back the MIxS-extension acronyms that are currently missing on the website
(2) add back in extension specific papers.
          These could be added to the publication page: https://www.gensc.org/pages/about/publication-list.html
          and added as links to PubMed on the checklists and extensions pages. 
       They are available in the GSC pubmed collection: https://pubmed.ncbi.nlm.nih.gov/collections/45575934/?sort=pubdate
       I would like to have them present on the GSC web pages as well. 

[1] 
I recently noted that the published names of the extensions are no longer on the extensions page: 
https://www.gensc.org/pages/standards/extensions.html

This is important as this is part of our MIxS branding. 
And without these labels, we will loose the connection between the published names
of the checklists. 
For example: MIxS-Food, MIxS-symbiont

MIxS-HCR
https://pubmed.ncbi.nlm.nih.gov/27777648/

https://pubmed.ncbi.nlm.nih.gov/24152717/
MIxS-BE: a MIxS extension defining a minimum information standard for sequence data from the built environment

agricultural microbiome studies (MIxS-Ag)
https://apsjournals.apsnet.org/doi/10.1094/PBIOMES-09-19-0051-P

[2]  PubMed IDs: 
Checklists:
MIGS            PMID: 18464787 
MIMS           PMID: 18464787 
MIMARKS     PMID: 21552244
 
MISAG, MIMAG: PMID: 28787424 
 
[MIBiG]
             [Biosynthetic Gene cluster.](https://pubmed.ncbi.nlm.nih.gov/26284661/)
             https://pubmed.ncbi.nlm.nih.gov/30008988/  
    v 2.0(https://pubmed.ncbi.nlm.nih.gov/31612915/)
[(MIUViG).](https://pubmed.ncbi.nlm.nih.gov/30556814/) PMID: 30556814

Extensions: 
 
MIxS-HCR
https://pubmed.ncbi.nlm.nih.gov/27777648/

https://pubmed.ncbi.nlm.nih.gov/24152717/
MIxS-BE: a MIxS extension defining a minimum information standard for sequence data from the built environment

agricultural microbiome studies (MIxS-Ag)
https://apsjournals.apsnet.org/doi/10.1094/PBIOMES-09-19-0051-P

**Comment by only1chunts** [comment]
Hi Lynn,
This is gensc.org website related so the ticket needs to be moved to that repo instead of the mixs one, I'm not sure how to move tickets, so I'll just create a new one there instead to copy your concerns to, and close this ticket.
