### ISSUE TITLE
fao_class description has link to a dead site

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#696]
**Describe the bug**
the link provided to complete [fao_class](https://genomicsstandardsconsortium.github.io/mixs/0001083/) is broken (Soil classification from the FAO World Reference Database for Soil Resources. The list can be found at http://www.fao.org/nr/land/sols/soil/wrb-soil-maps/reference-groups) 

**Expected behavior**

The link should work, or we should provide a new link.

**Additional context**

Some things to consider... how often is this slot used? Does an updated link exist? Is this the same thing-> https://www.britannica.com/science/soil/FAO-soil-groups (i don't know what the previous site link looked like)

**Comment by mslarae13** [comment]
@turbomam  could you query NCBI and see how/ if this slot is filled out much?

**Comment by only1chunts** [comment]
looking at the FAO website and following links on there, it seems like they now use/recommend ISRIC world soil information list found here: https://www.isric.org/explore/world-soil-distribution 
I'm not sure if we should be using that list instead, or if we should be creating an enum ourselves (based on that list and linking to matching ontology terms - the few I checked are in ENVO already).

**Comment by turbomam** [comment]
```sql
select
	"value",
	count(1)
from
	all_attribs aa
where
	attribute_name = 'fao_class'
group by
	"value"
order by
	count(1) desc ;
```

There were only 6242 NCBI Biosamples with a `fao_class` annotation as of July.

value | count
-- | -:
Luvisols | 1046
not applicable | 452
not collected | 431
rendzina | 368
Typic Hapludalfs | 270
Oxisol | 253
Mollisol | 232
using EC meter (HORIBA) with a 2:5 soil/water suspension | 192
Endostagnic Luvisol from glacial till | 192
NA | 169
Hoytville silty clay loam | 133
Kokomo silty clay loam | 132
Phaeozem | 126
Fluvisol | 120
cambisol | 101
chernozem | 100
Greyzemic Phaeozem Albic | 97
"Fine-silty, mixed, thermic Oxyaquic Fragiudalfs" | 96
Chernozem | 90
"Fine, mixed, active, mesic Typic Paleudalfs" | 90
mesic Lamellic Hapludalfs | 90
Typic Argiudoll | 88
Cambisol | 83
loess | 80
using EC meter (LAQUAtwin EC-33B, HORIBA) with a 1:10 soil/water suspension (mS cm-1) | 78
Vitric eutric epiarenic | 72
missing | 67
Typic Argiudolls | 66
Podzol | 59
Andosol | 56
Luvic Phaeozem | 54
Luvisol | 51
Nitisol | 51
Arenosol | 48
"Fine-loamy, mixed, subactive, thermic typic Hapludults" | 47
Calcaric, Eutric Fluvisol | 36
Umbric Epistagnic Albeluvisol | 36
Gleysol | 34
Cryosol | 31
using EC meter (LAQUAtwin EC-33B, HORIBA) with a 1:5 soil/water suspension | 30
3a | 30
Histosol | 27
Haplic Phaeozem | 27
Pellic Vertisol | 27
arenosols | 24
Leptosol | 23
sod-podzolic | 22
Earth-cumuli-Orthic Anthrosols | 21
using EC meter (LAQUAtwin EC-33B, HORIBA) with a 2:5 soil/water suspension (mS cm-1) | 20
na | 19
Calcisols | 18
Ferralsol | 17
Mottled Fragic Pallic Soil (Ustochrept) | 16
Regosol | 12
Vertisol | 12
Oxisols | 12
Phaozem | 9
Planosol | 8
Haplic Luvisol | 6
Geric Ferralsol | 5
Stagnic Cambisol | 4
Lithosol | 3
Cambisol (almost Ferralsol) | 3
fluvisol | 3
histosol | 3
Kastanozem | 3
Umbrisol | 3
loamy-skeletal, mixed, active, mesic Lithic Dystrudept | 3
vertisol | 2
ferralsols | 2
phaeozem | 2
gypsisol | 2
xerosol | 1
krasnozem | 1
O-horizon | 1
fao_class | 1
Dark Chestnut soil | 1
A - Non-calcaric lithosol, B -D - Typical podzolic brown soil, E - Saline alluvial gley soil | 1
Alisol | 1

**Comment by mslarae13** [comment]
A good chunk of what is in NCBI currently is some variation of the FAO classification.. variations in plurality and capitalization, but it's one of the closer ones I've seen! 

That said, I agree with @only1chunts. We should create an FAO enumeration and require it be one of the provided list. Thanks for the link Chris, I wasn't able to find that site. 

I'll work on the enum and making the updates to the description now.

**Comment by mslarae13** [comment]
Updated, see https://github.com/GenomicsStandardsConsortium/mixs/pull/726

Note, the enum already existed so I just updated the available values
