### ISSUE TITLE
size_frac_low definition: size_frac_low and size_frac_up definitions are the wrong way round

### ISSUE THREAD

**Issue by Woolly-at-EBI** [GenomicsStandardsConsortium/mixs#698]
**Current term details**
Please supply the current details of the term that you would like to update:
```
Term name - size_frac_low
Term ID - MIXS:0000735
Structured comment name - 
Definition - Refers to the mesh/pore size used to pre-filter/pre-sort the sample. Materials larger than the size threshold are excluded from the sample
Expected value - 
Value syntax -
Example -
Preferred unit - 
Package(s) - 
Relationship to other MIXS terms [if applicable] -
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):
```
Term name - 
Structured comment name - 
Definition - Refers to the mesh/pore size used to retain the sample. Materials smaller than the size threshold are excluded from the sample
Expected value - 
Value syntax -
Example -
Preferred unit - 
Package(s) - 
Relationship to other MIXS terms [if applicable] -
```

**Additional context**
size_frac_low and size_frac_up definitions are the wrong way round

**Comment by mslarae13** [comment]
see 
https://github.com/GenomicsStandardsConsortium/mixs/issues/566
https://github.com/GenomicsStandardsConsortium/mixs/issues/699
https://github.com/GenomicsStandardsConsortium/mixs/issues/566

**Comment by mslarae13** [comment]
Corrected with PR https://github.com/GenomicsStandardsConsortium/mixs/pull/825
