### ISSUE TITLE
update gender of restroom values MIXS:0000808

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#70]
**Current term details**
```
Term name - gender of restroom 
Term ID - MIXS:0000808
Structured comment name - gender_restroom
Definition - The gender type of the restroom
Expected value - enumeration
**Value syntax -  [male\|female] **
Example - male
Package(s) - built environment
```
Should be more inclusive of other types

**Suggested update(s)**
```
Term name - gender of restroom 
Term ID - MIXS:0000808
Structured comment name - gender_restroom
Definition - The gender type of the restroom
Expected value - enumeration
**Value syntax -  [male\|female \ transgender \ unisex \ none \ other] **
Example - male
Package(s) - built environment
```

**Comment by lschriml** [comment]
see **host_sex in MIxS 6**, packages, row 208

[female|hermaphrodite|non-binary|male|transgender|transgender (female to male)|transgender (male to female)|undeclared]

**Comment by cmungall** [comment]
The term "all genders" is sometimes preferred over unisex
https://en.wikipedia.org/wiki/Unisex_public_toilet

I'm  not aware of public restrooms that segregate cis vs trans but I
suppose these could exist. Of course segregated bathrooms could vary in
degrees of trans inclusion vs exclusion.

**Comment by lschriml** [comment]
In Austin, Texas, law changed to require: all-gender

[[news article](https://www.shrm.org/resourcesandtools/legal-and-compliance/employment-law/pages/gender-neutral-bathrooms-in-the-workplace.aspx)]

[US bathroom access laws](https://ballotpedia.org/Transgender_bathroom_access_laws_in_the_United_States)

gender-neutral
[in Nevada ](https://www.reviewjournal.com/news/politics-and-government/2021-legislature/bill-would-require-single-stall-bathrooms-in-nevada-to-be-gender-neutral-2315661/)

**Comment by lschriml** [comment]
updated: [all gender|female|gender neurtral|male|male and female|unisex]
closing the ticket.

Cheers,
Lynn
