### ISSUE TITLE
MIXS terms that need a proper label term - with suggested label terms

### ISSUE THREAD

**Issue by Woolly-at-EBI** [GenomicsStandardsConsortium/mixs#708]
Are are  list of MIXS terms that need a proper label term and suggestion for what it could be:
In ENA we use the label=title term for our term labels and what the user sees. The following suggestions are what we are implementing in ENA.

- [ ] host_family_relationship: host family relationship
- [ ] x_16s_recover_software: x 16s recovery software
- [ ] salinity_meth: salinity method
- [ ] Food_source: food source
- [ ] non_mineral_nutr_regm: non-mineral nutrient regimen
- [ ] previous_land_use_meth: previous land use method
- [ ] tot_car: total carbon
- [ ] samp_stor_temp: sample storage temperature
- [ ] microbial_biomass_meth: microbial biomass method
- [ ] single_cell_lysis_prot: single cell or viral particle lysis kit protocol
- [ ] tot_phos: total phosphate
- [ ] Food_Product_type: food product type
- [ ] host_infra_specific_name: host infra-specific name
- [ ] samp_stor_loc: sample storage location
- [ ] samp_stor_dur:  sample storage duration
- [ ] sample_name: sample name
- [ ] single_cell_lysis_appr: single cell or viral particle lysis approach 
- [ ] texture_meth: soil texture method
- [ ] sample_collec_method: sample collection method
- [ ] samp_collec_device: sample collection device
- [ ] samp_salinity: sample salinity
- [ ] tot_n_meth: total nitrogen method
- [ ] salinity_meth: salinity method
- [ ] x_16s_recover: x 16S recovered
- [ ] soil_text_measure: soil texture measurement
- [ ] samp_collec_method: sample collection method
- [ ] host_infra_specific_rank: host infra-specific rank

**Comment by ramonawalls** [comment]
Thanks, Peter! Very helpful.

**Comment by only1chunts** [comment]
I'm sure it will be obvious when I get it, but at the moment I'm not understanding what this ticket actually means? 
As far as I can tell all our terms have both a full name (Title in linkML speak) and a short name (AKA structured comment name or just "name" in LinkML speak) so what is the question/suggestion here?
Lets take for example the first one in the list: [host_family_relationship](https://w3id.org/mixs/0000872) 
The full name is name: host family relationship
and the short name is: host_fam_rel
so where does "host_family_relationship" come from or suggested for?

**Comment by Woolly-at-EBI** [comment]
Thanks @only1chunts . You are perfectly correct. I am those closing this non-issue.

Apologies all, I should have double checked those on the web site. Like I did with spot check of definitions.

I had been using the JSON export from the linkml. The title for host_family_relationship is correct in that JSON export. Ummm. I have code error somewhere. I don't understand as for most of the 700+ MIxS terms, it was pulling out the correct title. And in the JSON no titles have "_"

**Comment by only1chunts** [comment]
@Woolly-at-EBI no worries, just glad I'm not missing something fundamental :-D
