### ISSUE TITLE
Should temperature (MIXS:0000113) be core?

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#71]
**Current term details**
```
Term name - temperature 
Term ID - MIXS:0000113
Structured comment name - temp 
Definition - Temperature of the sample at the time of sampling
Expected value - measurement value
Value syntax -{float}   {unit} 
Example -25 degree Celcius
Preferred unit - M
Package(s) - 16 packages
```

**Suggested update(s)**
As this item appears in 16 packages should we consider moving this term to the core set instead?

**Comment by lschriml** [comment]
Let's define together what we want in the core, as the concept of core has advanced over time, with the inclusion of additional checklists. 
I would like to be able to distinguish core - mandatory set of terms, as this set is used to assign GSC keyword in INSDC, then core terms - terms that are used across all checklists and environmental packages.
Also to consider how the core is put together: 
core for MIxS -- all checklists 
and core for specific packages. 

Perhaps have MIxS Core - mandatory & non-mandatory - to be used across all checklists and packages
then MIxS checklists - MIGS, MIMS, MIMARKS, MISAG, MIMAG, MIUViG 
    as a new tab for the release 

We could consider a tab for each checklist, as they are presented that was in the INSDC. 

Cheers,
Lynn

**Comment by only1chunts** [comment]
so the "Core" terms will be a very reduced set of terms compared to the current version? i.e. just the 10 terms that are mandatory.
```
submitted_to_insdc
investigation_type
project_name
lat_lon
geo_loc_name
collection_date
env_broad_scale
env_local_scale
env_medium
seq_meth
```
With 7 more that are "Conditional mandatory" for all checklists:
```
env_package
source_mat_id
nucl_acid_ext
nucl_acid_amp
adapters
url
sop
```

Currently, we have the designations about whether an item is mandatory (M), conditional mandatory (C), optional (X), environment-dependent (E) or not applicable (-). 
If a term is "E" surely that should be moved to the relevant environmental package(s)?
There are 3 terms that have "E" for all checklists
```
depth
alt
elev
```

Making the distinction between commonly used terms (non-mandatory) and those that could appear in any checklist and/or package is going to be a tricky thing to determine a rule for inclusion/exclusion. Could we simplify the system to:
 mandatory core terms + checklist core terms + packages
So each checklist group (MIGS, MIMS, MIMARKS, MISAG, MIMAG, MIUViG) has its own set of Core-recommended terms

e.g. an 16S rRNA study from Water would have:
12 core mandaotry fields (like all MIxS compliant sequences)
+

**Comment by pbuttigieg** [comment]
I would vote against having this in core, but agree there has to be some refinement of what the intent of core and each package is. 

The packages are suffering from a lack of orthogonality, which we can pick on in #77 or a broader issue.

**Comment by ramonawalls** [comment]
Core was originally intended as a guide for new package developers. Core is not really used except for package development.

Temperature is a widely used field that can be an optional field in core. @ramonawalls to update spreadsheet then close this ticket.

**Comment by lschriml** [comment]
Added to MIxS Core, as "E" environment dependent
