### ISSUE TITLE
Update definition of related terms MIXS:0000111 & MIXS:0000001

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#72]
**Current term details**
There is a difference between the terms, but I think it could be made clearer in the definitions.
Also should MIX:0000111 be made CORE as it appears in 16 packages anyway?
```
Term name - amount or size of sample collected
Term ID - MIXS:0000001
Structured comment name - samp_size
**Definition - Amount or size of sample (volume, mass or area) that was collected**
Expected value - measurement value
Value syntax - {float} {unit}
Example - 5 liter
Package(s) - CORE

AND

Term name - sample volume or weight for DNA extraction
Term ID - MIXS:0000111
Structured comment name - samp_vol_we_dna_ext 
**Definition - Volume (ml), weight (g) of processed sample, or surface area swabbed from sample for DNA extraction**
Expected value - measurement value
Value syntax -{float} {unit}
Example - 1500 milliliter
Preferred unit - millliter, gram, milligram, square centimeter
Package(s) - 16 Packages
```
**Suggested update**
```
Term ID - MIXS:0000001
Structured comment name - samp_size
**Definition - The total amount or size (volume (ml), mass (g) or area (m2) ) of sample collected.**

AND 

Term ID - MIXS:0000111
Structured comment name - samp_vol_we_dna_ext 
**Definition - Volume (ml) or mass (g) of total collected sample processed for DNA extraction. Note- total sample collected should be entered under the term Sample Size (MIXS:0000001).**
```

**Comment by msweetlove** [comment]
I think it's a good idea to make samp_vol_we_dna_ext[MIXS:0000011] a core term.

I would suggest for 
**Term ID =** MIXS:0000001
**Structured comment name =**  samp_size
**Definition =** The total amount (volume (ml), mass (g), individuals) or area (m2) of sample collected prior to any additional processing (e.g. addition of preservatives, buffers, drying or subsampling). Also see samp_vol_we_dna_ext[MIXS:0000111].

In this rationale samp_vol_we_dna_ext[MIXS:0000111] could then be used for samples that were already subjected to some form of further processing (e.g. adding RNALater or buffers in the field to stabilize the sample)

**Comment by only1chunts** [comment]
@msweetlove , thanks. I'd be happy with your suggestion of definition for MIXS:0000001, and for MIXS:0000011 to be in core
@lschriml @ramonawalls , are you OK with these two updates? If so, please go ahead and make them in the spreadsheet and move this ticket to done.

**Comment by ramonawalls** [comment]
Sounds good to me!

**Comment by lschriml** [comment]
Sounds good to me too.

**Comment by lschriml** [comment]
definition updated across core, packages, checklists, newly developed packages/checklists
     Term ID - MIXS:0000001
and MIXS:0000111
     Structured comment name - samp_size

added to core, as optional (X)
MIXS:0000111

Tasks completed.
