### ISSUE TITLE
reduce length of short name of x16s_recover_software [MIXS:0000066]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#742]
**Current term details**
```
Term name -  16S recovery software  
Term ID - MIXS:0000066
Structured comment name - x16s_recover_software
Definition - Tools used for 16S rRNA gene extraction
```

**Suggested update(s)**
```
Term name -  16S recovery software  
Term ID - MIXS:0000066
Structured comment name - recover_software_amp
Definition - Tools used for amplicon region extraction from sequences
```

**Additional context**
The addition of the preceding X made this term 21 char, the X was added for technical reasons to do with python and some other tools not liking term names starting with a number. The suggested name change here resolves the length and the starting with a number, it also follows the preference of GSC to use more generic terms were possible to allow greater inclusivity, i.e. its now not restricted to just 16S rRNA amplicons, it could be used for other amplicon sequencing experiments.

**Comment by turbomam** [comment]
or `amp_recover_software`, since we're trying to capture what software was used to recovery amplicons?

**Comment by only1chunts** [comment]
see #801
