### ISSUE TITLE
pcr_cond provides structure and example in description

### ISSUE THREAD

**Issue by mslarae13** [GenomicsStandardsConsortium/mixs#744]
Descriptions shouldn't have an example in it. 

"Description of reaction conditions and components of PCR in the form of 'initial denaturation:94degC_1.5min; annealing=...'"

recommended change

"Description of reaction conditions and components of polymerase chain reaction performed during library preparation'

**Comment by only1chunts** [comment]
I'm inclined to not go looking for things like this, but I agree with the principle of removing examples from descriptions when we have to make other updates to a term, or where the example is wrong or misleading. If the TWG want to include this minor update in the next PR/comit thats fine by me (as long as there is an example in the correct linkML field).

**Comment by mslarae13** [comment]
@only1chunts I'm happy to work on issues like this.

**Comment by mslarae13** [comment]
I would like to ask.. which example is right?

      - value: initial denaturation:94_3;annealing:50_1;elongation:72_1.5;final elongation:72_10;35
      - value: initial denaturation:94degC_1.5min

with our without degC?
