### ISSUE TITLE
merge salinity and sample_salinity

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#75]
**Current term details**
The terms **salinity** (MIXS:0000183) and **sample_salinity**(MIXS:0000109) appear to be identical and should be merged.
In addition, there is a 3rd term called **extreme_unusual_properties/salinity**(MIXS:0000651) which also provides a place to store salinity measurements
```
Term name - salinity
Term ID - MIXS:0000183
Structured comment name - salinity
Definition - Salinity is the total concentration of all dissolved salts in a water sample. While salinity can be measured by a complete chemical analysis, this method is difficult and time consuming. More often, it is instead derived from the conductivity measurement. This is known as practical salinity. These derivations compare the specific conductance of the sample to a salinity standard such as seawater
Expected value - measurement value
Value syntax - {float} {unit}
Example - 25 practical salinity unit
Preferred unit - practical salinity unit, percentage
Package(s) - 
   microbial mat/biofilm
   miscellaneous natural or artificial environment
   sediment
   water
```
AND
```
Term name - sample salinity
Term ID - MIXS:0000109
Structured comment name - samp_salinity
Definition - Salinity is the total concentration of all dissolved salts in a liquid or solid (in the form of an extract obtained by centrifugation) sample. While salinity can be measured by a complete chemical analysis, this method is difficult and time consuming. More often, it is instead derived from the conductivity measurement. This is known as practical salinity. These derivations compare the specific conductance of the sample to a salinity standard such as seawater
Expected value - measurement value
Value syntax - {float} {unit}
Example - 1 milligram per liter
Preferred unit - milligram per liter, practical salinity unit, percentage
Package(s) - 11 packages
```
AND
```
Term name - extreme_unusual_properties/salinity
Term ID - MIXS:0000651
Structured comment name - extreme_salinity
Definition - Measured salinity
Expected value - measurement value
Value syntax - {float} {unit}
Example -
Preferred unit - millisiemens per meter
Package(s) - soil 

Has second required term:
salinity_meth | extreme_unusual_properties/salinity method | Reference or method used in determining salinity | PMID,DOI   or url | {PMID}\|{DOI}\|{URL} | MIXS:0000341
```

**Suggested update(s)**

The packages that each of these terms relates to appear to be different, so merging all terms together as one, unifying the preferred units and then considering moving the new term to CORE?

**Comment by lschriml** [comment]
agreed, merge the terms. 
Lynn

**Comment by ramonawalls** [comment]
Agree they should be merged.

**Comment by only1chunts** [comment]
**Final consensus**
Deprecate term
--
Term name - extreme_unusual_properties/salinity
Term ID - MIXS:0000651
--

Deprecate term
--
Term name - sample salinity
Term ID - MIXS:0000109
--

Update term (definition)
--
Term name - salinity
Term ID - MIXS:0000183
Structured comment name - salinity
Definition - Salinity is the total concentration of all dissolved salts in a liquid or solid (in the form of an extract obtained by centrifugation) sample. While salinity can be measured by a complete chemical analysis, this method is difficult and time consuming. More often, it is instead derived from the conductivity measurement. This is known as practical salinity. These derivations compare the specific conductance of the sample to a salinity standard such as seawater.  _Consider the use of the metadata term salinity method._
Expected value - measurement value
Value syntax - {float} {unit}
Example - 25 practical salinity unit
Preferred unit - practical salinity unit, percentage
Packages - multiple
--

Replace both deprecated terms with "salinity [MIXS:0000183]"

**Comment by ramonawalls** [comment]
Deprecated all of the MIXS:0000109 terms.

**Comment by ramonawalls** [comment]
deprecated MIXS:0000651

**Comment by ramonawalls** [comment]
There is a term `extreme_unusual_properties/salinity method` that goes along with the deprecate term `extreme_unusual_properties/salinity`, but it is only used in the soil package at the moment. Since `extreme_unusual_properties/salinity` will be replaced by `salinity`, we should rename `extreme_unusual_properties/salinity method` to `salinity method`.

```
Term name - salinity method
Term ID - MIXS:0000341
Structured comment name - salinity_meth
Definition - Reference or method used in determining salinity
Expected value - PMID,DOI or url
Value syntax - {PMID}|{DOI}|{URL}
Example -
Preferred unit - 
Packages - soil
```

The only change is to the term name.

Done.

**Comment by ramonawalls** [comment]
Updated definition of salinity tp remove reference to method term, since most packages don't use it. Also got rid of "(in the form of an extract obtained by centrifugation)" which is too specific. 

Added salinity to the package that had `sample salinity`(MIXS:0000109) that was deprecated (air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids/swabs, plant-associated, wastewater/sludge).

```
Term name - salinity
Term ID - MIXS:0000183
Structured comment name - salinity
Definition - The total concentration of all dissolved salts in a liquid or solid sample. While salinity can be measured by a complete chemical analysis, this method is difficult and time consuming. More often, it is instead derived from the conductivity measurement. This is known as practical salinity. These derivations compare the specific conductance of the sample to a salinity standard such as seawater. 
Expected value - measurement value
Value syntax - {float} {unit}
Example - 25 practical salinity unit
Preferred unit - practical salinity unit, percentage
Packages - air, host-associated, human-associated, human-gut, human-oral, human-skin, human-vaginal, hydrocarbon resources-cores, hydrocarbon resources-fluids/swabs, microbial mat/biofilm, miscellaneous natural or artificial environment, plant-associated, wastewater/sludge, sediment, water
```

I made this change. This issue can be closed, unless there is disagreement about the changes.

**Comment by ramonawalls** [comment]
@only1chunts please close unless you disagree.

**Comment by only1chunts** [comment]
Thanks @ramonawalls , I agree with what you've done.
