### ISSUE TITLE
look through NCBI Biosample for usages of the nose, throat, teeth type terms

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#760]
regenerate BBOP's SQLite and repopulate our Postgres on SPIN? That take several hours but makes the usage easier for me. It can be shared publicly as the SQLite file, but there isn't any public Postgres endpoint yet.

**Comment by turbomam** [comment]
Build database according to https://github.com/turbomam/biosample-xmldb-sqldb
- high RAM and storage requirements
- takes ~ 24 hours

```sql
select
	distinct attribute_name,
	harmonized_name
from
	all_ncbi_attributes_long
where
	to_tsvector('english',
	attribute_name) 
	@@ phraseto_tsquery('english',
	'throat');
```

| attribute_name                 | harmonized_name                |
|--------------------------------|--------------------------------|
| covid_symptoms_sore_throat     |                                |
| nose mouth teeth throat disord | nose_mouth_teeth_throat_disord |
| nose_mouth_teeth_throat_disord | nose_mouth_teeth_throat_disord |
| nose_throat_disord             | nose_throat_disord             |
| Symptom: Sore throat           |                                |
| throat_bright                  |                                |

**Comment by lschriml** [comment]
As noted in the Feb 13th CIG notes: 
(Lynn): review of term usage:

→ Review notes below, I would say that we can merge these two terms.
New definition: History of nose,mouth, teeth, and/or throat disorders: can include multiple disorders.

→ and to add in the information for the source of the terms, where appropriate: 
The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org, lung disease (https://disease-ontology.org/?id=DOID:850), upper respiratory tract disease (https://disease-ontology.org/?id=DOID:974),
(https://disease-ontology.org/?id=DOID:2825), mouth disease (https://disease-ontology.org/?id=DOID:403), tooth disease (https://disease-ontology.org/?id=DOID:1091).


 MIXS:0000270 -  In the human-associated package: 
–Structured Comment (short name): nose_throat_disord	
– Package Name (long name):lung/nose-throat disorder
		-definition:
History of nose-throat disorders; can include multiple disorders,  The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org, lung disease (https://disease-ontology.org/?id=DOID:850), upper respiratory tract disease (https://disease-ontology.org/?id=DOID:974).

MIXS:0000283 -   In the human oral package: 

– Structured Comment (short name): nose_throat_disord
– Package Name (long name): nose/mouth/teeth/throat disorder
         – definition: 
History of nose/mouth/teeth/throat disorders; can include multiple disorders. The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org, nose disease (https://disease-ontology.org/?id=DOID:2825), mouth disease (https://disease-ontology.org/?id=DOID:403), tooth disease (https://disease-ontology.org/?id=DOID:1091), or upper respiratory tract disease (https://disease-ontology.org/?id=DOID:974).

**Comment by mslarae13** [comment]
Change to oral and add nose, throat, teeth to the desription?

**Comment by lschriml** [comment]
To be closed, see #743

**Comment by turbomam** [comment]
@lschriml I don't see the corresponding changes int eh mixs.yaml file

**Comment by turbomam** [comment]
Sorry, I see that you were encouraging activity to resume on #743
