### ISSUE TITLE
Add MIxS 6.0 Core and Packages excel docs to MIxS repo

### ISSUE THREAD

**Issue by lschriml** [GenomicsStandardsConsortium/mixs#764]
As we have discussed previously,
    We need to add back in the MIxSv6.0 release docs to this repository, 
    at the top of the repository. 

https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=178015749

**Comment by mslarae13** [comment]
Resolved with https://github.com/GenomicsStandardsConsortium/mixs/pull/850 
see on the github main page, release/excel
