### ISSUE TITLE
How do different INSDC repos use different linkml slots to key MIxS terms?

### ISSUE THREAD

**Issue by Woolly-at-EBI** [GenomicsStandardsConsortium/mixs#773]
**Describe the bug**
How do different INSDC repos use different linkml slots to key MIxS terms?

**Additional context**
ENA uses the "long name"(=title) to key MIxS terms
NCBI uses the "short name" to key MIxS terms

**Comment by cmungall** [comment]
Very interesting to see how MIxS put into practice!

What does it mean to key here specifically - I imagine it depends on the
context. Viewing on NCBI/EBI sample pages exposes one way of doing it,
creating a submission form another, downloading as XML another...?

**Comment by turbomam** [comment]
Thanks for the PR @sujaypatil96 

@Woolly-at-EBI and @cmungall I don't feel like we've really finished this discussion. Should we open this issue back up or start another one?

**Comment by cmungall** [comment]
One actionable way to reformulate this is to have an SOP markdown doc for making changes. E.g "if a long name is to be changed then groups <X, Y> need to informed since this is used as a primary key in their relational database"...
