### ISSUE TITLE
MIxS core geo_loc_nam - alignment with INSDC specification

### ISSUE THREAD

**Issue by lschriml** [GenomicsStandardsConsortium/mixs#79]
**Current term details**
Looks like we have, at some point, diverged in the formatting of this term, from the INSDC

geo_loc_nam is current (MIxS 5.0)
Expected Value:
country or sea name (INSDC or GAZ);region(GAZ);specific location name
value syntax: {term};{term};{text}

It should be colon, then comma, not semicolons to separate Country:region, specific location

as outlined here: 
country="<country_value>[:<region>][, <locality>]"

INSDC: http://www.insdc.org/files/feature_table.html#3.4

Term name - 
Term ID - [if known]
Structured comment name - 
Definition - 
Expected value - 
Value syntax -
Example -
Preferred unit - 
Package(s) - 
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):
```
Term name - 
Structured comment name - 
Definition - 
Expected value - 
Value syntax -
Example -
Preferred unit - 
Package(s) - 
```

**Additional context**
Add any other context about the update request here, e.g. why you think this needs to be updated.

**Comment by lschriml** [comment]
https://www.ncbi.nlm.nih.gov/genbank/collab/country/

**Comment by msweetlove** [comment]
suggested update for MIxS v6:

**Term name =** geo_loc_name
**Term ID =** MIXS:0000010
**Structured comment name =** geographic location (country and/or sea,region)
**Definition =** The geographical origin of the sample as defined by the country or sea name followed by a specific region and/or a location name. Country or sea names should be chosen from the INSDC country list (http://insdc.org/country.html), or the GAZ ontology (v 1.512) (http://purl.bioontology.org/ontology/GAZ)
**Expected value =** SeaOrCountry:Region, Specific location
**Value syntax =** {text}:{text}, {text}
**Example =** Belgium:Ghent, Bourgoyen nature reserve
**Preferred unit =** none
**Package(s) =** MIxS Core

**Comment by lschriml** [comment]
geo_loc_name has been updated across core and checklists.
I did remove the version of GAZ, as it is out of date and we are working on a new version currently. 

Cheers,
Lynn
