### ISSUE TITLE
Identify the @genomicstandardsconsortium and determine what their contributions can be

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs#824]
There is a @genomicstandardsconsortium GitHub user who has participated in this repo in the past 

https://github.com/GenomicsStandardsConsortium/mixs/blame/32ea6eb73eb44530c57bd1f41b6f48d65bd13d23/README.md

aka https://github.com/genomicstandardsconsortium?tab=overview&from=2017-12-01&to=2017-12-31

The user's page does not identify them as a human.

The TWG discussed this situation today 2024-07-16 and we hope that @genomicstandardsconsortium will respond to this issue

- who are you?
- are you willing to add personal information like name, institution etc to your GitHub profile?
- in what ways would you like to participate in this repo?

If there's no response or if the responses are no, I propose that we remove any admin privileges for this user in this repo

**Comment by lschriml** [comment]
Good Afternoon,
 @genomicstandardsconsortium  -- is the GSC executive group. 
We own the repo, our privileges will not be changed. 
   Point in fact, the exec is the group that controls access to the repo. 

I would like to hear how this came up and why this was proposed.
Lynn

**Comment by turbomam** [comment]
Thanks for responding @lschriml . @ramonawalls your comments in the Google Doc were helpful too.

@lschriml can you please give some other examples of GitHub projects where an individual or group of individuals has an account that bears the name of the organization? LinkML and NMDC don't do that, although they do have GitHub groups.

Who has the credentials for this GitHub user account? Can any member of the executive committee log in as that user any time they want and participate in discussions? It's only happened once before, but that's still very unusual. 

This user does have ownership privileges for the GenomicsStandardsConsortium organization. I have double checked with  some other colleagues and they are not able to see that but I am and I assume the both of you will see it if you follow this link: https://github.com/orgs/GenomicsStandardsConsortium/people?query=genomicstandardsconsortium

Deleting this account would not have any effects on any user, from the executive committee or otherwise, unless they do not have GItHub accounts of their own.

Here's a report of the people who are additional owners of  GenomicsStandardsConsortium now: https://github.com/orgs/GenomicsStandardsConsortium/people?query=role%3Aowner

Regarding 

> how this came up and why this was proposed

I saw that this user had made changes to the README.md, a file which is routinely discussed by TWG members as a part of continuous improvement. Since anonymous GitHUb users are not a common or beneficial practice, I raised it as a concern in the TWG meeting and other members agreed that it required further investigation.
