### ISSUE TITLE
structured comment name too long tot_nitro_content_meth

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#83]
**Current term details**
The length of structured comment names is supposed to be limited to 20char.

```
Term name - total nitrogen content method
Term ID - [if known] MIXS:0000338
Structured comment name - tot_nitro_content_meth
Definition - Reference or method used in determining the total nitrogen
Package(s) - Soil
```

**Suggested update(s)**
```
Structured comment name - tot_nitro_cont_meth
```

**Additional context**
there is a related term "total nitrogen content" which has the structured comment name "tot_nitro_content", it might seem reasonable to shorten "content" to "cont" in that structured comment name also?

**Comment by only1chunts** [comment]
this issue didn't get pulled into the mixv6 project so got missed, it needs addressing in v7

**Comment by ramonawalls** [comment]
Has this issue been fixed yet?

**Comment by only1chunts** [comment]
yes it appears to have been fixed by shortening content to cont  "tot_nitro_cont_meth" see https://genomicsstandardsconsortium.github.io/mixs/0000338/

**Comment by ramonawalls** [comment]
Discussion at TWG today.

Is this still a requirement for INSDC? It was required because of flat files, which are no longer a thing. Well, they still are, but they working to decouple the metadata

Assigned to @Woolly-at-EBI to investigate and respond in this thread.
