### ISSUE TITLE
structured comment names too long

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#84]
**Current term details**
A number of current terms exceed the max 20char of structured comment names:
```
heat_system_deliv_meth
room_architec_element
room_moist_damage_hist
shading_device_water_mold
host_family_relationship
host_infra_specific_name
host_infra_specific_rank
host_blood_press_diast
host_blood_press_syst
nose_mouth_teeth_throat_disord
tvdss_of_hcr_pressure
organism_count_qpcr_info
water_production_rate
chem_treatment_method
samp_collection_point
organism_count_qpcr_info
non_mineral_nutr_regm
previous_land_use_meth
water_content_soil_meth
tot_nitro_content_meth
microbial_biomass_meth

```

**Suggested update(s)**
We need to discuss these and agree on a shorter term for each.

**Comment by lschriml** [comment]
Reviewing, 
I propose:
heat_sys_deliv_meth
rm_architec_element
rm_moist_damage_hist
shad_dev_water_mold
host_fam_rel
host_infra_spec_name
host_infra_spec_rank
host_bl_press_diast
host_bl_press_syst
nose_oral_disord
true_depth_pressure
org_count_qpcr_info
water_prod_rate
chem_treat_method
samp_collection_pt
org_count_qpcr_info
non_min_nutr_regm
prev_land_use_meth
water_cont_soil_meth
tot_nitro_cont_meth
micro_biomass_meth

**Comment by only1chunts** [comment]
I think they all sound reasonable, please go ahead and make the changes in MIxS v6.0, 'MIxS6 packages - to edit'

**Comment by lschriml** [comment]
Updated. Char names all less than 20 char.
