### ISSUE TITLE
Need for a new field (ecosystem) to hold the environmental context at the highest level

### ISSUE THREAD

**Issue by jagadishcs** [GenomicsStandardsConsortium/mixs#87]
@ramonawalls
@TBKReddy
@cmungall
 
**New term details**
For us to assess a new term request we require the following details:
```
Term name - ecosystem 
Structured comment name - ecosystem
Definition - An environmental system which includes both living and non-living components
Expected value - enumeration
Value syntax - [aquatic ecosystem|atmosphere or air ecosystem|terrestrial ecosystem|engineered or manufactured|host-associated ecosystem]
Example - aquatic ecosystem 
Preferred unit -
Package(s) - MIxS core field (applicable to all MIxS packages)
```

**Additional context**
Add any other context about the new term here.
```
Rationale
A new field (ecosystem) is suggested to hold the environmental context at the highest level in the v6 of the MIxS packages.
In the current version of the MIxS packages, three terms have been given for environmental context,  broad-scale environmental context (biome), local environmental context (feature) and environmental medium (material) derived from EnvO, that are helpful to provide the environmental context of the biosample studied.
However, the broad-scale environmental context (biome) given in the ENVO are broad (ex: aquatic biome) at a high level but gets narrowed down to freshwater biome, freshwater lake biome to large lake biome or small lake biome. Availability of more granular terms at the broad-scale environmental context (biome) level will make it difficult to classify the data at the highest level of ecosystems such as aquatic or terrestrial.

In the v5 of MIxS, the field for the MIxS package name (env_package) solves this problem to an extent; however, the host-associated package and availability of six other specific host-associated packages (that is likely to grow) and water package and availability of other water-associated packages (sediment/ microbial mat/wastewater-sludge) are likely to add more granularity, hence, difficult to classify/hold the data at the highest level of the ecosystem using the env_package field as well.

Therefore, it may be useful to have one more field, ecosystem to hold the environmental context at the highest possible level.
```

**Comment by only1chunts** [comment]
Thanks for your comments @jagadishcs . My opinion would be that the use of Biome with ENVO terms more than covers the use case you are suggesting so I dont think we need the additional term of "ecosystem".
Additionally, it should be noted that the NCBI taxonomy also stratifies the sample type in a similar way.

**Comment by jagadishcs** [comment]
Thanks for your response, @only1chunts. I agree that currently available terms in the v5 of the MIxS are enough to identify/understand the biosamples environmental context.  

My goal for asking this term is that with available terms in v5 of the MIxS, it will be difficult to classify the biosamples at the higher level, say, aquatic or terrestrial.

Let me explain this with an example: the [Genomes Online Database (GOLD)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6323969/) has established a five-level Ecosystem classification path to describe the environmental context of the biosamples and organisms. 
The five-levels are: Ecosystem, Ecosystem Category, Ecosystem Type, Ecosystem Subtype and Specific Ecosystem; 
at the highest level, GOLD has three different Ecosystems - Environmental, Engineered and Host-associated; 
further, each Ecosystem is divided into different Ecosystem Categories; For example, ‘Environmental’ ecosystem is divided into Air, Aquatic and Terrestrial.

For a sediment biosample from a lake, the GOLD five-level ecosystem classification would be Environmental/Aquatic/Freshwater/Lake/Sediment, while the MIxS-EnvO triad can be freshwater lake biome (broad-scale environmental context), mesotrophic lake (local environmental context) and lake sediment (environmental medium).
When a biosample comes from any _aquatic_ ecosystem, the GOLD ecosystem classification captures it as _aquatic_ (at its _Ecosystem Category_ level) before giving any further details.

You can please refer [Uncovering Earth's virome](https://pubmed.ncbi.nlm.nih.gov/27533034/) where the availability of broad ecosystem terms in the GOLD facilitating data mining and analysis at higher level, aquatic, terrestrial and host-associated.

Availability of variety of terms under ‘broad-scale environmental context (biome)’ in EnvO to represent _aquatic/terrestrial_ ecosystems, helps to specify the environmental context of the studied biosamples, but on the other hand we would face difficulty to mine all the biosamples from a broad ecosystem, say, _aquatic_, because we do not, kind of, tie/bind them at the highest level. 

At present, we may have to look for multiple terms, and combine multiple fields of v5 MIxS if we have to select all aquatic or terrestrial biosamples.

Best

**Comment by only1chunts** [comment]
I think the use of the ENVO ontology (if used correctly) will cover all your use cases. 
e.g. "freshwater lake biome [ENVO_01000252]" is an "aquatic biome" [ENVO_00002030] thats part of its definition within ENVO.
Add to that the NCBI taxonomy also stratifying in a similar way to GOLD then I still think there is no need for an additional term to cover the same ground. 
But as this is just my opinion, hopefully some others from the GSC will chime in here to give theirs (@lschriml @pbuttigieg)

**Comment by ramonawalls** [comment]
I agree with @only1chunts that ENVO covers these high level terms. In order to search for all terms in, e.g., an aquatic biome, one would have to use the ontology to discover all responses under mixs:broad-scale environmental context (biome) that are subclasses (or part of) an 'aquatic biome'. 

I understand, @jagadishcs that it is much easier to just search on 'ecosystem', but then you are asking users to supply both the high level term and the specific term. I suspect that few of them will bother with the specific term in that case. The beauty of the ontology is that it covers all five of GOLD's levels with a single term.

I really want to avoid adding another term that is so close to an existing term, as it is likely to cause confusion. Can we find a way to facilitate the high level search without adding a new term?

**Comment by cmungall** [comment]
@jagadishcs:
> the broad-scale environmental context (biome) given in the ENVO are broad (ex: aquatic biome) at a high level but gets narrowed down to freshwater biome, freshwater lake biome [...]

if we look at 'freshwater lake biome' in ENVO we can see it sums up to the kind of high level grouping you are after:

![image](https://user-images.githubusercontent.com/50745/99729262-7e156580-2a6f-11eb-98ef-cc35f98913d0.png)

See https://www.ebi.ac.uk/ols/ontologies/envo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_01000252

But I think you have a point with the very-high level groupings 'engineered' and 'host-associated'. We are discussing the latter here: https://github.com/EnvironmentOntology/envo/issues/1029

It might be useful to look at the engineered terms in more detail as ENVO may need more work here

**Comment by lschriml** [comment]
Discussing during November CIG call
  - from EnvO perspective  - OK
  - from database perspective 
  - making the database aware of the hierarchy 
    should enable this data connection.

**Comment by pbuttigieg** [comment]
> from EnvO perspective - OK
    from database perspective
    making the database aware of the hierarchy
    should enable this data connection.

I don't understand this summary. 

I don't see any need to change the broad/local/medium triad in v6. 

>the very-high level groupings 'engineered' and 'host-associated'. 

These classes can be generated (although x-"associated" can mean anything, so that shouldn't be used IMO), and then slotted in to the env_local slot. the env_broad should always aim higher (e.g. what kind of environment did you find the organism that plays host in?).

**Comment by lschriml** [comment]
This topic was discussed at previous CIG call. 
The conclusion, if I recall correctly, was to not add a new field. 

Cheers,
Lynn
