### ISSUE TITLE
Consensus on ontology term format

### ISSUE THREAD

**Issue by raissameyer** [GenomicsStandardsConsortium/mixs#91]
**Describe the bug**
MIxS_v5 gives unclear guidance on ontology term formatting in the "Examples" column. The two formatting suggestions follow these structures [EFO:EFO_0001779] and [ENVO:00001998]. Such inconsistency in guidance, and thus in use, impedes automated analyses. Please decide which format should be followed and update the guidance accordingly. 

**To Reproduce**
1. Go to '[https://press3.mcs.anl.gov/gensc/mixs/](https://press3.mcs.anl.gov/gensc/mixs/)'
2. Download MIxS Checklist v5.0: [mixs_v5](http://press3.mcs.anl.gov/gensc/files/2020/02/mixs_v5.xlsx)
3. Open the downloaded file 'mixs_v5' and go to tab 'MIxS'
4. Scroll down to row 5 'experimental_factor', scroll right to column F 'Example'
5. Read the content of the field and note that it says "time series design **[EFO:EFO_0001779]**"
6. Scroll down to row 12 'env_brad_scale', scroll right to column F 'Example'
7. Read the content of the field and note that it says "forest biome **[ENVO:01000174]**"

**Expected behavior**
The suggested format would be expected to be consistent.

**Screenshots**
<img width="506" alt="image" src="https://user-images.githubusercontent.com/48056511/101468930-56197380-3944-11eb-9c20-5d291d221740.png">

**Additional context**
If you intend to allow users to also use terms that don't originate from the ontologies you propose but are imported into those, I'd suggest going with Example 1 [EFO:EFO_0001779]. Otherwise the restriction to not use imported terms should be communicated.

**Comment by lschriml** [comment]
Hello Raissa,
 Thank you for pointing out this inconsistency. 
We are currently preparing MIxS v6.0 and will address
this issue.

Cheers,
Lynn

**Comment by turbomam** [comment]
Excellent issue @raissameyer 

As of v6.2.0, the MIxS schema doesn't have any mechanism for validating the semantics of ontology term values in data. We do have a regular expression that looks for a label part followed by a term id part, enclosed in square brackets.

**Comment by ramonawalls** [comment]
This has been standardized through the use of LinkML. If additional work is needed, there should be a new issue.
