### ISSUE TITLE
names that begin with numbers

### ISSUE THREAD

**Issue by wdduncan** [GenomicsStandardsConsortium/mixs#92]
In the future we might want to abstain from begining names with a number. E.g.: The structured comment names:  16s_recover, 16s_recover_software

Many programing languages do not permit variables or function names to begin with a number. For example in the NMDC project, we are using the structured comment names to link samples to database values. But when using 16s_recover, we have to prepend an underscore ("_16s_recover"). Not a big deal, but something that the community might want to be aware of, and consider when adding new items.

I can't recall if all database engines allow for column names to begin with numbers.

**Comment by wdduncan** [comment]
@only1chunts The (core) terms `16s_recover` and `16s_recover_software` may cause problems with databases that don't allow column/field names to begin with a numbers. Although changing the terms may cause problems for systems already implemented this term.

Also row 274 has this as the `structured comment name`:
History of kidney disorders; can include multiple disorders. The terms should be chosen from the DO (Human Disease Ontology) at http://www.disease-ontology.org, kidney disease (https://disease-ontology.org/?id=DOID:557).

**Comment by ramonawalls** [comment]
We are not aware of this causing problems so far, so we will consider this further for MIxS7.

**Comment by wdduncan** [comment]
That is probably b/c people are doing work arounds :)

E.g., We prepend such terms with an underscore.

**Comment by mslarae13** [comment]
Closing this as duplicated by 
- https://github.com/GenomicsStandardsConsortium/mixs/issues/801
- https://github.com/GenomicsStandardsConsortium/mixs/issues/742

In general, when we update documentation for contributing to MIxS, we will include the rule about length & not starting slots with a number.
