### ISSUE TITLE
Update name and definition of chimera check [MIXS:0000052]

### ISSUE THREAD

**Issue by only1chunts** [GenomicsStandardsConsortium/mixs#97]
1 - This is currently in Core, but is only really for MIMARKS, should it be considered core or not?
2 - the current definition is just about "what is a chimera" it needs to include what the value of the term "chimera check" is meant to be?

**Current term details**
```
Term name - chimera check
Term ID - MIXS:0000052
Structured comment name - chimera_check 
Definition - A chimeric sequence, or chimera for short, is a sequence comprised of two or more phylogenetically distinct parent sequences. Chimeras are usually PCR artifacts thought to occur when a prematurely terminated amplicon reanneals to a foreign DNA strand and is copied to completion in the following PCR cycles. The point at which the chimeric sequence changes from one parent to the next is called the breakpoint or conversion point 
Expected value - name and version of software, parameters used
Value syntax - {software};{version};{parameters}
Example - uchime;v4.1;default parameters
Package(s) - core
```

**Suggested update(s)**
Please supply the new suggestions for any of the details listed below (only insert text to those details that should be updated):
```
Definition - A chimeric sequence, or chimera for short, is a sequence comprised of two or more phylogenetically distinct parent sequences. Chimeras are usually PCR artifacts. Please provide details of any checks performed on the sequence to discover and remove chimeric sequences.
Package(s) - ???
```

**Comment by jjkoehorst** [comment]
Discussion on zoom call 8th Feb:
This term is similar to other computational methods (e.g. assembly_software, 16s_recover_software, ...) and it would be good to remain consistent with the naming setup and it could then become "chimera_check_software" or "chimera_software" or something similar ending with _software.

For the definition we should become consistent with at least the initial sentence for _software related terms: _Tool(s) used for chimera checking, including version number and parameters._ After that we can go into the details of what the term is ment in more detail combined with the starter sentence:

Tool(s) used for chimera checking, including version number and parameters. A chimeric sequence, or chimera for short, is a sequence comprised of two or more phylogenetically distinct parent sequences.

**Comment by only1chunts** [comment]
**Suggested update(s)**
Following the previous discussion and notes above I suggest the name and definition are updated to:
```
Term name - chimera check software
Definition - Tool(s) used for chimera checking, including version number and parameters, to discover and remove chimeric sequences. A chimeric sequence is comprised of two or more phylogenetically distinct parent sequences.
```
All other fields remain unchanged.

**Comment by only1chunts** [comment]
Updated definition and name in v6 core to edit tab.
